### ISSUE TITLE
Error Occurred: Non-Zero Exit Code(1) in Pycharm

### ISSUE THREAD

**Issue by Kev-kutkin** [ludwig-ai/ludwig#1000]
**Error Occurred: Non-Zero Exit Code (1)**
I was unable to import and install ludwig library in my PyCharm Pro. This is because I received an error message saying 

> Error occurred when installing package 'ludwig'. Details: 

  Could not find a version that satisfies the requirement tensorflow>=2.2 (from ludwig) (from versions: 0.12.1, 1.0.0, 1.0.1, 1.1.0rc0, 1.1.0rc1, 1.1.0rc2, 1.1.0, 1.2.0rc0, 1.2.0rc1, 1.2.0rc2, 1.2.0, 1.2.1, 1.3.0rc0, 1.3.0rc1, 1.3.0rc2, 1.3.0, 1.4.0rc0, 1.4.0rc1, 1.4.0, 1.4.1, 1.5.0rc0, 1.5.0rc1, 1.5.0, 1.5.1, 1.6.0rc0, 1.6.0rc1, 1.6.0, 1.7.0rc0, 1.7.0rc1, 1.7.0, 1.7.1, 1.8.0rc0, 1.8.0rc1, 1.8.0, 1.9.0rc0, 1.9.0rc1, 1.9.0rc2, 1.9.0, 1.10.0rc0, 1.10.0rc1, 1.10.0, 1.10.1, 1.11.0rc0, 1.11.0rc1, 1.11.0rc2, 1.11.0, 1.12.0rc0, 1.12.0rc1, 1.12.0rc2, 1.12.0, 1.12.2, 1.12.3, 1.13.0rc0, 1.13.0rc1, 1.13.0rc2, 1.13.1, 1.13.2, 1.14.0rc0, 1.14.0rc1, 1.14.0, 2.0.0a0, 2.0.0b0, 2.0.0b1)
No matching distribution found for tensorflow>=2.2 (from ludwig)
You are using pip version 8.1.1, however version 20.2.4 is available.
You should consider upgrading via the 'pip install --upgrade pip' command. 

Please provide code, yaml config file and a sample of data in order to entirely reproduce the issue. 
I will provide the full details of the command output as below.

Command Output from the Pycharm:
Collecting ludwig
  Using cached https://files.pythonhosted.org/packages/af/74/d6a9ac8e5a9ffc485bef7fa3fef3f116d258c50d06afb8744d49377b9d39/ludwig-0.3.tar.gz
Collecting Cython>=0.25 (from ludwig)
  Using cached https://files.pythonhosted.org/packages/19/49/91ebe4a00bf894d08dd9680cd9dfb05936eb2848eebd9402b43885aa74cf/Cython-0.29.21-cp36-cp36m-manylinux1_x86_64.whl
Collecting h5py>=2.6 (from ludwig)
  Using cached https://files.pythonhosted.org/packages/70/7a/e53e500335afb6b1aade11227cdf107fca54106a1dca5c9d13242a043f3b/h5py-3.1.0-cp36-cp36m-manylinux1_x86_64.whl
Collecting numpy>=1.15 (from ludwig)
  Using cached https://files.pythonhosted.org/packages/a6/fc/36e52d0ae2aa502b211f1bcd2fdeec72d343d58224eabcdddc1bcb052db1/numpy-1.19.4-cp36-cp36m-manylinux1_x86_64.whl
Collecting pandas>=0.19 (from ludwig)
  Using cached https://files.pythonhosted.org/packages/4d/51/bafcff417cd857bc6684336320863b5e5af280530213ef8f534b6042cfe6/pandas-1.1.4-cp36-cp36m-manylinux1_x86_64.whl
Collecting scipy>=0.18 (from ludwig)
  Using cached https://files.pythonhosted.org/packages/c8/89/63171228d5ced148f5ced50305c89e8576ffc695a90b58fe5bb602b910c2/scipy-1.5.4-cp36-cp36m-manylinux1_x86_64.whl
Collecting tabulate>=0.7 (from ludwig)
  Using cached https://files.pythonhosted.org/packages/c4/f4/770ae9385990f5a19a91431163d262182d3203662ea2b5739d0fcfc080f1/tabulate-0.8.7-py3-none-any.whl
Collecting scikit-learn (from ludwig)
  Using cached https://files.pythonhosted.org/packages/5c/a1/273def87037a7fb010512bbc5901c31cfddfca8080bc63b42b26e3cc55b3/scikit_learn-0.23.2-cp36-cp36m-manylinux1_x86_64.whl
Collecting tqdm (from ludwig)
  Using cached https://files.pythonhosted.org/packages/93/3a/96b3dc293aa72443cf9627444c3c221a7ba34bb622e4d8bf1b5d4f2d9d08/tqdm-4.51.0-py2.py3-none-any.whl
Collecting tensorflow>=2.2 (from ludwig)

  Could not find a version that satisfies the requirement tensorflow>=2.2 (from ludwig) (from versions: 0.12.1, 1.0.0, 1.0.1, 1.1.0rc0, 1.1.0rc1, 1.1.0rc2, 1.1.0, 1.2.0rc0, 1.2.0rc1, 1.2.0rc2, 1.2.0, 1.2.1, 1.3.0rc0, 1.3.0rc1, 1.3.0rc2, 1.3.0, 1.4.0rc0, 1.4.0rc1, 1.4.0, 1.4.1, 1.5.0rc0, 1.5.0rc1, 1.5.0, 1.5.1, 1.6.0rc0, 1.6.0rc1, 1.6.0, 1.7.0rc0, 1.7.0rc1, 1.7.0, 1.7.1, 1.8.0rc0, 1.8.0rc1, 1.8.0, 1.9.0rc0, 1.9.0rc1, 1.9.0rc2, 1.9.0, 1.10.0rc0, 1.10.0rc1, 1.10.0, 1.10.1, 1.11.0rc0, 1.11.0rc1, 1.11.0rc2, 1.11.0, 1.12.0rc0, 1.12.0rc1, 1.12.0rc2, 1.12.0, 1.12.2, 1.12.3, 1.13.0rc0, 1.13.0rc1, 1.13.0rc2, 1.13.1, 1.13.2, 1.14.0rc0, 1.14.0rc1, 1.14.0, 2.0.0a0, 2.0.0b0, 2.0.0b1)
No matching distribution found for tensorflow>=2.2 (from ludwig)
You are using pip version 8.1.1, however version 20.2.4 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Expected behavior**
My expectation is the installation of ludwig in pycharm is successful. 

**Screenshots**
![error_ludwig](https://user-images.githubusercontent.com/25189239/98428910-abeec780-20c9-11eb-85e3-27b8ee016373.png)

**Environment (please complete the following information):**
 - OS: Ubuntu 16.04, 64-bit
- Python 3.6
- Ludwig 0.3 (shown in the Pycharm's available package)

**Additional context**

**Comment by carlogrisetti** [comment]
Could you try updating PIP as suggested by the commandline?
`pip install --upgrade pip`

It's a very old version, and it might be that it lacks references to newer packages and\or has bugs with specific systems, or in any case this would be the first thing to try in my opinion.

**Comment by w4nderlust** [comment]
Agree with @carlogrisetti , this part of the error message is the key:
```
You are using pip version 8.1.1, however version 20.2.4 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```
Pretty sure that is you install the new version of pip it will be able to find TF2.

**Comment by ihamieh** [comment]
i dont think upgrading pip would solve this issue as I tried it! I'm having the same issue!!

**Comment by carlogrisetti** [comment]
Just to double-check the command line now no longer prompts you to upgrade pip and now shows a much newer version than 8.x?

All the other info are still the same?

Can you try manually issuing a `pip install ludwig` from the command line and seeing if this changes anything?

Bye

**Comment by w4nderlust** [comment]
@ihamieh latest releases should have solved this. Can you please run `pip install ludwig` now and check if the issue is sovled?
