### ISSUE TITLE
hyperopts overtraining

### ISSUE THREAD

**Issue by ifokeev** [ludwig-ai/ludwig#1039]
Is it possible to tune `hyperopts` based on `test` or `validation` loss? I'm getting overtraining due to good params for `train` but it's moving crazy on `test`

train stats:

<img width="732" alt="Screen Shot 2020-12-02 at 21 22 39" src="https://user-images.githubusercontent.com/2017148/100914748-84cac080-34e4-11eb-954e-e89779ef032a.png">

test stats:

<img width="741" alt="Screen Shot 2020-12-02 at 21 20 54" src="https://user-images.githubusercontent.com/2017148/100914548-459c6f80-34e4-11eb-8433-0d93f18c4065.png">

**Comment by michaelbzhu** [comment]
What does your configuration look like?
Under the hyperopt section you can specify the split that you want to use
Also, I think `hyperopt` and `train` should normally use validation metrics by default

```
config = {
    'hyperopt': {
        'split': 'validation',   # this should be set to 'validation' by default, but you can also select 'training' or 'test'
        'goal': 'minimize',
        'output_feature': 'label',
        'metric': 'loss',
        'parameters': {
...
```
Hope this helps!

**Comment by w4nderlust** [comment]
@michaelbzhu 's answer is correct. let me know if that soulds your issue @ifokeev .
You cal also set what validation metric to use for determining early stopping within each single run of the hyperopt (for early stopping purposes).
