### ISSUE TITLE
undefined symbol: encountered while training model in Docker container.

### ISSUE THREAD

**Issue by avinashkurup** [ludwig-ai/ludwig#1057]
Hi,
    Im facing an issue for the last 2 days while running a training model using Ludwig which gives me errors as shown in the attachment. It looks like a version mismatch between tensorflow and tensorflow-addons. Could you please suggest a fix for this issue.

[Ludwig-Dockerbuild-issue.txt](https://github.com/uber/ludwig/files/5703694/Ludwig-Dockerbuild-issue.txt)
[requirements.txt](https://github.com/uber/ludwig/files/5703703/requirements.txt)

**Comment by tgaddair** [comment]
Hey @avinashkurup, thanks for including the log output.  Looks like there are two things here:

1. `tfa-nightly` needs to be updated for the TensorFlow 2.4.0 release.  You can do this by running `pip install tfa-nightly==0.12.0.dev20201215223743` (unfortunately, they have not yet released an official version with TF 2.4.0 support).  I am also bumping this version in #1058.
2. Looks like Horovod also needs to be updated since you upgraded TensorFlow.  You can do this as follows:

```
pip uninstall -y horovod
[include any optional Horovod environment variables here] pip install --no-cache-dir horovod
```

**Comment by avinashkurup** [comment]
Hi Travis, Thank you for your reply. I added the versions to the requirements.txt but the issue still persists. I see the following lines in the log.

[2020-12-17T16:05:13.199Z] [PID 23218] [614468 ms] ERROR: tensorflow 2.4.0 has requirement absl-py~=0.10, but you'll have absl-py 0.9.0 which is incompatible.
ERROR: tensorflow 2.4.0 has requirement numpy~=1.19.2, but you'll have numpy 1.18.1 which is incompatible.
ERROR: ludwig 0.3.1 has requirement tfa-nightly==0.12.0.dev20200820045606, but you'll have tfa-nightly 0.12.0.dev20201215223743 which is incompatible.

I tried resolving the version dependency of absl-py, but the undefined symbol is still encountered.

I tried this version of tfa-nightly==0.12.0.dev20200820045606 as well with tensorflow==2.3.1.

[ludwig-error-log.txt](https://github.com/ludwig-ai/ludwig/files/5710715/ludwig-error-log.txt)
[requirements.txt](https://github.com/ludwig-ai/ludwig/files/5710724/requirements.txt)

**Comment by tgaddair** [comment]
Hey @avinashkurup please try building from master, which includes the changes in #1058.

Also, it looks like your Docker image comes with an old version of TensorFlow (v2.1).  Can you try using a newer Docker image or uninstalling TensorFlow before installing Ludwig?  The core issue here is that Horovod is installing with the old version of TensorFlow, which is later overwritten.
