### ISSUE TITLE
Unable to train the modelwith Ludwig v0.3.1

### ISSUE THREAD

**Issue by mithila2806** [ludwig-ai/ludwig#1064]
**Describe the bug**
Getting 'Value Error' while training my model using Ludwig.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'https://github.com/mithila2806/Automate-Title-with-Ludwig.git'
2. Find the code - 'Automate Title with Ludwig(From SEJ Article).ipynb'
3. Run all the cells.
4. Scroll down to '.ludwig train --dataset hootsuite_titles.csv --config config.yaml'
5. See error
**Error Log File:**
[Error Log file.txt](https://github.com/ludwig-ai/ludwig/files/5721351/Error.Log.file.txt)

Note:
Input File: 
https://gist.githubusercontent.com/hamletbatista/5f6718a653acf8092144c37007f0d063/raw/84d17c0460b8914f4b76a8699ba0743b3af279d5/hootsuite_titles.csv

**YAML Code:**
yaml_config="""
input_features:
    -
        name: Original_Title
        type: text
        level: word
        encoder: t5
        reduce_output: null
    -
        name: Keyword
        type: text
        level: word
        tied_weights: Original_Title
        encoder: t5
        reduce_output: null
output_features:
    -
        name: Optimized_Title
        type: sequence
        level: word
        decoder: generator
"""

with open("config.yaml", "w") as f:
  f.write(yaml_config)

**Expected behaviour**
The model should be trained with Ludwig. Getting Value Errors:(Screenshots)

**Screenshots**
<img width="885" alt="Train Model" src="https://user-images.githubusercontent.com/66806398/102721501-0bf4a280-42f3-11eb-9b32-aa31479d5fb1.png">
<img width="862" alt="Error - part 1" src="https://user-images.githubusercontent.com/66806398/102721504-0f882980-42f3-11eb-9d24-3688d10ce7a3.png">
<img width="772" alt="Error - part 2" src="https://user-images.githubusercontent.com/66806398/102721505-1151ed00-42f3-11eb-8eb9-9c2fd9c927f6.png">
<img width="690" alt="Error - part 3" src="https://user-images.githubusercontent.com/66806398/102721508-131bb080-42f3-11eb-882f-45b475db7210.png">

**Environment (please complete the following information):**
 - OS: Windows 
- Python version 3.6
- Ludwig version 0.3.1

**Additional context**
I was getting TensorFlow-Ludwig compatibility issues earlier. So I changed the TensorFlow version to 2.3.1 as the default was not working.

**Comment by w4nderlust** [comment]
Thanks forletting us know @mithila2806 . It's an issue related specifically to T5 that happens with the newest version fo transformers. Will fix it soon, in the meantime please try using transformers < 4 and this should work.

**Comment by mithila2806** [comment]
@w4nderlust Thanks very much, WIll try doing that:)

**Comment by w4nderlust** [comment]
@mithila2806 this should be fixed now, so I'm closing, please let me know if you still ahve problems and i can reopen.
