### ISSUE TITLE
Ludwig train NOT executing. Ludwig0.3.2-dev1 KeyError: 'content'

### ISSUE THREAD

**Issue by khaliljouma** [ludwig-ai/ludwig#1065]
**Describe the bug**
Getting KeyError: 'content' while training CSV using Ludwig0.3.2-dev1.

**To Reproduce**
1. Go to 'https://github.com/khaliljouma/trainingLudwig/blob/main/log'
2. Click on 'log'
3. Scroll down to 'KeyError: 'content''

Input File:
https://github.com/khaliljouma/trainingLudwig/blob/main/Tweets.csv

YAML Code:
https://github.com/khaliljouma/trainingLudwig/blob/main/model_definition.yaml

**Expected behavior**
The model should be trained with Ludwig. > But getting 

C:\Users\MyUser\AppData\Roaming\Python\Python38\site-packages\typeguard\__init__.py:885: UserWarning: no type annotations present -- not typechecking tensorflow_addons.layers.max_unpooling_2d.MaxUnpooling2D.__init__
  warn('no type annotations present -- not typechecking {}'.format(function_name(func)))

Traceback (most recent call last):
  File "C:\Users\MyUser\AppData\Roaming\Python\Python38\Scripts\ludwig-script.py", line 11, in <module>
    load_entry_point('ludwig==0.3.2.dev1', 'console_scripts', 'ludwig')()

**Screenshots**
![image](https://user-images.githubusercontent.com/35195808/102825349-a20df300-43ef-11eb-9589-43ec9fe5bffc.png)
![image](https://user-images.githubusercontent.com/35195808/102825492-eac5ac00-43ef-11eb-9a44-b94d801aaac6.png)

**Environment:**
 - OS: Windows 10
- Python version 3.8.2
- Ludwig version v0.3.2-dev1

**Additional context**
Tensorflow v2.4.0
Please help!

**Comment by w4nderlust** [comment]
Hi khaliljouma . It seems you have no column in your data named `content`, but you have one named `text` so i suppose that's the one you want to use. Let me know if it fixes the issue.

**Comment by khaliljouma** [comment]
Thank you so much @w4nderlust !
