### ISSUE TITLE
Broken link on website

### ISSUE THREAD

**Issue by SabineMa** [ludwig-ai/ludwig#1071]
**Describe the bug**
Here  [https://ludwig-ai.github.io/ludwig-docs/community/ ](https://ludwig-ai.github.io/ludwig-docs/community/ ) s a link to [https://gitq.com/ludwig-ai/ludwig](https://gitq.com/ludwig-ai/ludwig) which does not work

**Comment by jimthompson5802** [comment]
@SabineMa   Thank you for point this out.  We are looking into this issue.

**Comment by w4nderlust** [comment]
We moved the discussion to GitHub now, so this is fixed.
