### ISSUE TITLE
Addition of Point Clouds feature type

### ISSUE THREAD

**Issue by omshinde** [ludwig-ai/ludwig#1072]
Hello Team,
Thank you for the amazing work. I really appreciate the efforts in making the development so seamless and easy to use. I just tried the visual question-answering example with images and it saves so much more time in implementation. 

I would be grateful to know about the addition of point cloud feature type, I could see it as mentioned in the [What additional features are you working on?](https://ludwig-ai.github.io/ludwig-docs/faq/#what-additional-features-are-you-working-on) page on docs but could not find it any of the earlier [releases](https://github.com/ludwig-ai/ludwig/releases) or on the [Github Projects Page](https://github.com/ludwig-ai/ludwig/projects/1).

**Describe the use case**
I feel, 3D Point cloud support (in general nD support) could be a great addition and would help in accelerating 3D research.  

**Describe the solution you'd like**
I work with 3D lidar data so support for input of `.las`, `.PLY`, `.OBJ`, `.laz`, `.xyz` would be very much helpful. Otherwise, if it is possible to use other availble input feature type which can be used for point clouds and I am not aware of then please enlighten me.

**Describe alternatives you've considered**
I am exploring if the point cloud input is possible as HDF5 or TSVs or arrays or tensors (would take some time in exploring all the examples :)). I would be grateful to get more insights regarding this.

Also, if the work is in progress for the point cloud feature type and if there is a room for contribution, I would love to be a part of it. Thanks!

**Comment by jimthompson5802** [comment]
@omshinde   Thank you for suggestion.  We'll note this as a feature request and your feedback will help prioritize our backlog.   

Would gladly accept contributions in regards to this request.

**Comment by omshinde** [comment]
@jimthompson5802 Thank you! :)

**Comment by w4nderlust** [comment]
I can add that this is something we already wanted to have since quite a while and that I believe it's a useful and exciing feature :)

Adding a set of tensors, or even a set of vectors as input datatype should be pretty straightforward, and we could reuse the same encoders we have for set features, but skipping the embedding layer.
Plus we could also have an approach like we do for images and audio where the input value is a path to a file on disk that is loaded.

**Comment by omshinde** [comment]
Thank you very much for the insightful comment. Yes, I agree, plethora of opportunities with this feature. :)

Re using set of tensors or vectors: Yes, that's what I could think of as it is very much possible due to the modularity of the code (Special thanks :)). It would also be generalised and not restricted to specific 3D file formats and other unstructured data (maybe for using graphs as input in future...)

For beginning, I am exploring to add a new feature registry [here](https://github.com/ludwig-ai/ludwig/tree/master/ludwig/features) taking examples from the exisiting [image_feature.py](https://github.com/ludwig-ai/ludwig/blob/master/ludwig/features/image_feature.py) as mentioned in the developer docs and also as mentioned in the last comment. I really found it convenient and super easy to provide path to file as input while working on the Visual QA example with images and to have something similar for the pointsets would be amazing. Will keep posting the updates on this thread (also the doubts :D).
