### ISSUE TITLE
hdf5 being rebuilt too often

### ISSUE THREAD

**Issue by carlogrisetti** [ludwig-ai/ludwig#1078]
ludwig from master (and since 0.3.2 at least), on different systems

when changing the config.yaml file, even just changing the dropout values (which nothing has to do with the hdf5 preprocessed file), Ludwig says that the checksum has changed, hence it has to rebuild the hdf5 file.
This happens also switching the batch size parameter, for example. I am suspecting it happened to me also without changing any parameter whatsoever.

I will look into that, but wanted to keep track of this, since I don't know how much time I will have to do this in the next few days, and maybe that's already a known issue (i have found no issues regarding this, anyway).

**Comment by carlogrisetti** [comment]
Just happened with the same exact data, config, etc.
Might have something to do with the fact that I'm working on image data in input?

I will find the time to debug this

**Comment by w4nderlust** [comment]
The logic is the following: https://github.com/ludwig-ai/ludwig/blob/master/ludwig/data/preprocessing.py#L1798-L1811
which means the data is preprocessed when the following things change:
- ludwig version
- dataset modification date
- any parameter in the preprocessing section of the config
- any name or type of any feature
- any preprocessing section of any feature

If a feature parameter like dropout or a training parameter like batch size are changed, the preprocessing should not be triggered again (they are not used to compute the checksum, so checksum is identical and so the preprocessing should not be triggered, the relevant piece of code is: https://github.com/ludwig-ai/ludwig/blob/576b74b26cf7c289761ee3c6fcb45bef732ba8ce/ludwig/data/preprocessing.py#L1313-L1334 )

Let me know if you can figure out what triggers the spurious recreation of the cache.

**Comment by carlogrisetti** [comment]
Here it is...
when checking the config, the `'preprocessing': {'in_memory': False, 'num_processes': 6}` i specified gets thrown out, and that line 1313 only looks at a config that has `'preprocessing': {}` in it, hence being different from the actual one.
When saving the meta.json file, in row 1591, the full config (including `'preprocessing': {'in_memory': False, 'num_processes': 6}`) gets passed and hashed.

You should be able to repro with a model definition like this one
[config.txt](https://github.com/ludwig-ai/ludwig/files/5827355/config.txt)

**Comment by carlogrisetti** [comment]
Ok... needed some sleep :)
The part that changes in the info dataset you're building before calculating the hash is the last bit:

`'feature_preprocessing': [{}, {}, {}, {}]}` (when comparing to decide whether to rebuild)
https://github.com/ludwig-ai/ludwig/blob/576b74b26cf7c289761ee3c6fcb45bef732ba8ce/ludwig/data/preprocessing.py#L1313
vs

`'feature_preprocessing': [{}, {'in_memory': False, 'num_processes': 6}, {}, {}]}` (when saving meta.json)
https://github.com/ludwig-ai/ludwig/blob/576b74b26cf7c289761ee3c6fcb45bef732ba8ce/ludwig/data/preprocessing.py#L1591

Since that `'in_memory': False, 'num_processes': 6` is specified at the global level, I expect not to find those at the feature level (or to be copied in both the check and the json saving)

The "merging" happens here:
https://github.com/ludwig-ai/ludwig/blob/576b74b26cf7c289761ee3c6fcb45bef732ba8ce/ludwig/data/preprocessing.py#L1132-L1161

**Comment by carlogrisetti** [comment]
@w4nderlust I don't know how to manage this without breaking that last code... I'd say I'm passing this to you guys hehe :)
The issue should be easily reproducible. If not, just ask me for more details.

**Comment by w4nderlust** [comment]
Looks liek a bug then, will look into it!

**Comment by w4nderlust** [comment]
Working on it #1114

**Comment by carlogrisetti** [comment]
Never saw this message, sorry @w4nderlust . It does indeed fix the issue. I just had it resurface in a non-master updated install... and as soon as I updated to master it worked flawessly

**Comment by w4nderlust** [comment]
great to hear!
