### ISSUE TITLE
Dask Scalar is not json serializable when generating dataset metadata on a dask dataframe

### ISSUE THREAD

**Issue by zhisbug** [ludwig-ai/ludwig#1132]
**Describe the bug**
When calling the `precompute_fill_value` during generating the dataset metadata, if the `dataset_df` is a dask.dataframe (which is a requirement when running distributed ludwig on Ray), calling `df.mean()` for FILL_WITH_MEAN returns a symbolic value, which later cannot be serialized into JSON. 

**To Reproduce**
See my repo on running ludwig on ray with the petfinder dataset:
https://github.com/zhisbug/ludwig-petfinder/blob/dask-df/petfinder-adoption-prediction/train.py#L16

**Expected behavior**
Dask dataframe is lazy. We should check whether the dataframe is a dask.dataframe, and if it is, call `.compute()` to calculate the metadata value.

**Environment (please complete the following information):**
 - OS: Ubuntu 18
- Python version: 3.7
- Ludwig version: master

**Comment by zhisbug** [comment]
#1133 should fix it.

**Comment by tgaddair** [comment]
Fixed by #1133.
