### ISSUE TITLE
Parquet dataset does not have a `self.features` attribute, which is needed in the IterableBatcher

### ISSUE THREAD

**Issue by zhisbug** [ludwig-ai/ludwig#1134]
**Describe the bug**

The `IterableBatcher` will loop through all the features of a dataset (see[ this line of code](https://github.com/ludwig-ai/ludwig/blob/master/ludwig/data/batcher/iterable.py#L40)) object via an attribute `self.features` of a `Dataset` object

When the dataset is a parquet dataset (a new feature merged to master in [PR#1090](https://github.com/ludwig-ai/ludwig/commit/01d114ba76667dc52d1673d9be0809ee1e58087c)) (note that parquet is a required format when running ludwig on Ray), the `IteratableBatcher` cannot find this attribute `self.features`.

By going through the code of `parquet.py` I wasn't able to fnd a `self.features` attributes. There is only a self.reshape_features, which does not seem to be compatible with `IterableBatcher`.

**To Reproduce**
See my code on petfinder dataset: https://github.com/zhisbug/ludwig-petfinder/blob/master/petfinder-adoption-prediction/train.py#L11

**Expected behavior**
I guess a fix is needed to make IteratableBatcher compatible with ParquetDataset?

**Environment (please complete the following information):**
 - OS: Ubuntu 18
- Python version: 3.6
- Ludwig version: master

**Additional context**

**Comment by tgaddair** [comment]
Hey @zhisbug, thanks for the detailed repro. Can you try #1138 and see if it fixes the issue?

**Comment by zhisbug** [comment]
yes, #1138 fixed it.
