### ISSUE TITLE
The `self.reshape_features` is empty when working on petfinder dataset

### ISSUE THREAD

**Issue by zhisbug** [ludwig-ai/ludwig#1135]
**Describe the bug**
This issue is related with #1134.

I tried to replace the `reshape_features` with `features` to workaround the bug caused by `IteratableBatcher` (see #1134  for the detailed descriptions about the issue), but when working on the petfinder dataset, the `self.reshapes_features` is empty after applying the following code between L35-L39 of [parquet.py](https://github.com/ludwig-ai/ludwig/blob/master/ludwig/data/dataset/parquet.py#L35):

```python
self.reshape_features = {
    feature[PROC_COLUMN]: list((-1, *training_set_metadata[feature[NAME]]['reshape']))
    for feature in features
    if 'reshape' in training_set_metadata[feature[NAME]]
}
```

**To Reproduce**
Use my experiment script on petfinder dataset here: https://github.com/zhisbug/ludwig-petfinder/blob/master/petfinder-adoption-prediction/train.py

Try to print `self.reshaped_features` and you will see it is an empty dict.

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
- Python version
- Ludwig version

**Additional context**

**Comment by zhisbug** [comment]
See PR#1136 my workaround on this

**Comment by tgaddair** [comment]
Hey @zhisbug, are you running with image features? If not, then it's expected that `rehshape_features` should be empty (as there are no features that need to be reshaped when loaded from the Parquet file). Is this still an issue after applying #1138?

**Comment by zhisbug** [comment]
Yep seems that #1138  fixed it!

**Comment by zhisbug** [comment]
Yes!
