### ISSUE TITLE
Ludwig silently fails after first epoch (best_increase_batch_size_eval_metric": Infinity)

### ISSUE THREAD

**Issue by mangleddata** [ludwig-ai/ludwig#1142]
I have a dataset with timeseries data and my run silently fails after first epoch (i.e my overnight run just got killed with no specific error in any of the logs). Poking around, I see training_progress.json has this.
```
    "best_increase_batch_size_eval_metric": Infinity,
    "best_reduce_learning_rate_eval_metric": Infinity,
    "epoch": 1,
```
I couldn't tell if this is after first epoch or has anything to do with the run failure (for example, it does look like it is initialized that way). Just pointing it out, if anyone has any inputs on debugging this further.

**Comment by ifokeev** [comment]
check your memory, possible OOM

**Comment by mangleddata** [comment]
> check your memory, possible OOM

Not memory because if I run it again with preloading the last saved model, it runs again for few epochs. Plus I use small batch size and don't see memory usage getting close.

**Comment by jimthompson5802** [comment]
@mangleddata   we need more information to help identify the error.  Please post the following:
* The command used to start Ludwig 
* complete log output where the error occurred
* the config.yam file
* sample of training data

Thank you.

**Comment by mangleddata** [comment]
@jimthompson5802 I will look into generating a synthetic data set that would show this issue (I need to clean up things). My command typically looks like this -

``` horovodrun -np 2 --stall-check-shutdown-time-seconds 300 ludwig train --training_set train.csv --validation_set valid.csv --random_seed 42 -cf model.yaml -uh --model_name train_model  >> runlog/train_model.log ```

And when it fails, I don't see much in the log. 
``` 
$tail -10 runlog/train_model.log 
[1,0]<stdout>: 
[1,0]<stdout>:
[1,0]<stdout>:╒══════════╕
[1,0]<stdout>:│ TRAINING │
[1,0]<stdout>:╘══════════╛
[1,0]<stdout>:
[1,0]<stdout>:
[1,0]<stdout>:Epoch   1
Training: 100% 6490/6490 [1:37:28<00:00,  1.11it/s][1,0]<stdout>:
Evaluation train:  81% 5236/6490 [22:25<05:09,  4.05it/s]
```

Are there any additional debug knobs I could turn on to see more log ?

**Comment by jimthompson5802** [comment]
@mangleddata  thank you for the command and log output.  When you have a synthetic data set and `model.yaml` ready, please post.

**Comment by w4nderlust** [comment]
It would be great to be able to replicate with the synth data to figure out what is actually happening. It's pretty weird that there is no error and the process dies silently.

**Comment by tgaddair** [comment]
Hey @mangleddata, looks like you're only redirecting stdout to the log file. Can you try also redirecting stderr and then sharing the full log output when it crashes?

https://stackoverflow.com/questions/876239/how-to-redirect-and-append-both-stdout-and-stderr-to-a-file-with-bash

**Comment by dalianaliu** [comment]
Hi @mangleddata, I'm closing this issue for now. Please re-open if you need more help.
