### ISSUE TITLE
The directory used for HDF5 cache is not configurable as a preprocessing property

### ISSUE THREAD

**Issue by marcmm** [ludwig-ai/ludwig#1144]
**Is your feature request related to a problem? Please describe.**
This is causing problems in cloud environment like Azure ML, because input datasets are stored in read-only location.

**Describe the use case**
It would be great to be able to pass a separate directory path to use for the HDF5 data preprocessing cache and not choose to write it in the same folder as the input data.

**Describe the solution you'd like**
Enable parameters like these so all feature types can be persisted in a folder other than the input data one:

model_config["preprocessing"]["image"]["**preprocessing_output**"] = output_folder
model_config["preprocessing"]["**preprocessing_output**"] = output_folder

**Describe alternatives you've considered**
I tried to save the feature data output of processing step which was easy for tabular data, but requires some code for image data. 

**Additional context**
NA

**Comment by tgaddair** [comment]
Hey @marcmm, thanks for the feature request. This is actually something we have planned to do for the next release. There's a programmatic implementation in #1164 that works like this:

```
backend = LocalBackend(cache_dir='/path/to/some/directory')
model = LudwigModel(..., backend=backend)
```

In a follow-up PR, we'll add the ability to specify the cache directory in the config file so this works with the `ludwig` CLI as well. Also, the above PR should also simplify the process of reading / writing to ADLS and other cloud object stores, in case that's of interest.

**Comment by dalianaliu** [comment]
Hi @marcmm, I'm closing this issue for now. Please re-open if it hasn't been resolved by the new release of Ludwig.
