### ISSUE TITLE
TabNet combiner test failing on nightly

### ISSUE THREAD

**Issue by tgaddair** [ludwig-ai/ludwig#1147]
There was a changed pushed at https://github.com/ludwig-ai/ludwig/commit/1f32d282957a14a804de0a5a60dec4d92771fca5 that broke the `test_tabnet_combiner` tests, and thereby caused CI to fail.

Will temporarily disable this test.

**Comment by w4nderlust** [comment]
Yes will fix later today, it was a little interface change that was not reflected in the test.
