### ISSUE TITLE
Load a model from a SavedModel file 

### ISSUE THREAD

**Issue by jorgegarcia197** [ludwig-ai/ludwig#1154]
Hello, 
  I was able to train several models using the Ludwig API but I was wondering if currently I can load a LudwigModel object by just the path of the SavedModel file instead or it only works with a model folder. 

Hope you can help me out! 
Thanks in advance

**Comment by jimthompson5802** [comment]
@jorgegarcia197 If I understand your question correctly, I think the answer is the model can be loaded from any directory as long as the contents of that directory is consistent to the file structure that is created when Ludwig saves the model.

For example if you recursively copied the contents of the `model` folder to another location, e.g., `new_model_dir`, I believe you should be able to load the model from `new_model_dir`.  

If this does not work, please post the commands you executed along with any log file contents.

OTOH, if I mis-understood your question, I need more context on what you are trying to do.

Let me know if this helped or not.

**Comment by jorgegarcia197** [comment]
@jimthompson5802  what I am trying to do is to create a script that trains the model and just saves the .pb file with `LudwigModel.save_savedmodel(path)` but what I was wondering if when a do `LudwigModel.load(path)` can I reference the SavedModel path file generated by the prior command or is it only with the `model` folder path.

**Comment by jimthompson5802** [comment]
@jorgegarcia197   AFAIK, what you want do is possible.  

Have you tried it and did it fail?  If that is the case, please post the log file and minimal code to recreate the problem.

**Comment by w4nderlust** [comment]
@jorgegarcia197 Unfortunately no, you can't load the SavedModel as a Ludwig model. The SavedModel format lacks many pieces of information needed for building a proper Ludwig model (preprocessing and postprocessing for instance). So we consider it only a one way export format.
