### ISSUE TITLE
Can't install latest version on macOS

### ISSUE THREAD

**Issue by victoriayue** [ludwig-ai/ludwig#1208]
**Describe the bug**
I follow the installation guide to install Ludwig using a virtual environment. But the version I can only install is 0.1.0. 
I try to use `pip install --upgrade ludwig`, but the ludwig version didn't change
and I try to use `ludwig experiment` like the first example, it's also not working.

**To Reproduce**
1. `virtualenv -p python3 venv`
2. (after activate virtual environment) `pip install ludwig`
3. `pip list` to check the version of ludwig, it shows 0.1.0
4. try cmd `ludwig train`, it said: "ModuleNotFoundError: No module named 'tensorflow.contrib' " 
5. try cmd `ludwig experiment`, it said: "ModuleNotFoundError: No module named 'tensorflow.contrib' " 

**Expected behavior**
install latest version of ludwig and run successfully

**Screenshots**
% ludwig experiment \
> --dataset text_example.csv \
> --config_file config.yaml
Traceback (most recent call last):
  File "/Users/vyue/Desktop/folder1/venv/bin/ludwig", line 5, in <module>
    from ludwig.cli import main
  File "/Users/vyue/Desktop/folder1/venv/lib/python3.9/site-packages/ludwig/__init__.py", line 16, in <module>
    from ludwig.api import LudwigModel
  File "/Users/vyue/Desktop/folder1/venv/lib/python3.9/site-packages/ludwig/api.py", line 39, in <module>
    from ludwig.data.postprocessing import postprocess_df, postprocess
  File "/Users/vyue/Desktop/folder1/venv/lib/python3.9/site-packages/ludwig/data/postprocessing.py", line 19, in <module>
    from ludwig.features.feature_registries import output_type_registry
  File "/Users/vyue/Desktop/folder1/venv/lib/python3.9/site-packages/ludwig/features/feature_registries.py", line 25, in <module>
    from ludwig.features.bag_feature import BagBaseFeature
  File "/Users/vyue/Desktop/folder1/venv/lib/python3.9/site-packages/ludwig/features/bag_feature.py", line 24, in <module>
    from ludwig.features.base_feature import BaseFeature
  File "/Users/vyue/Desktop/folder1/venv/lib/python3.9/site-packages/ludwig/features/base_feature.py", line 21, in <module>
    from ludwig.models.modules.recurrent_modules import reduce_sequence
  File "/Users/vyue/Desktop/folder1/venv/lib/python3.9/site-packages/ludwig/models/modules/recurrent_modules.py", line 20, in <module>
    from tensorflow.contrib.rnn import MultiRNNCell, LSTMStateTuple
ModuleNotFoundError: No module named 'tensorflow.contrib'

**Environment (please complete the following information):**
 - OS: macOS Big Sur
 - Version 11.4
- Python version 3.9.5
- Ludwig version 0.1.0

**Additional context**

**Comment by jimthompson5802** [comment]
@victoriayue  Sorry to hear you're having trouble installing Ludwig.  To be able to assist you, I need a better understanding of the situation.
* You write about installing Ludwig v0.1.0.  The current release of Ludwig is v0.3.3.  Is there a reason you're installing an older version?
* You identify the OS as MacOS Big Sur.  I just want to confirm the hardware platform.  Is your Mac based on the Intel processor or Apple's new M1 ARM processor?  The reason I ask is there are known issues, beyond our control, for running Ludwig on the M1 ARM processor at this time.

**Comment by victoriayue** [comment]
Thanks for the quick reply! @jimthompson5802 

* because I would like to install the latest version which is v0.3.3, but when I type cmd `pip install ludwig`, it install the version v0.1.0 automatically. I don't know which part was wrong.
* the processor is Intel Core i9

**Comment by jimthompson5802** [comment]
One thing you can try is to be explicit on the version, e.g., `pip install ludwig==0.3.3`  

Let me know if this helps.

**Comment by victoriayue** [comment]
@jimthompson5802 I just try the cmd, here is the result looks like

> % pip install ludwig==0.3.3
Collecting ludwig==0.3.3
  Using cached ludwig-0.3.3.tar.gz (233 kB)
Requirement already satisfied: Cython>=0.25 in ./venv/lib/python3.9/site-packages (from ludwig==0.3.3) (0.29.23)
Collecting h5py<2.11.0,>=2.6
  Using cached h5py-2.10.0.tar.gz (301 kB)
Requirement already satisfied: numpy>=1.15 in ./venv/lib/python3.9/site-packages (from ludwig==0.3.3) (1.19.5)
Collecting pandas<1.1.5,>=0.19
  Using cached pandas-1.1.4-cp39-cp39-macosx_10_9_x86_64.whl (10.3 MB)
Requirement already satisfied: scipy>=0.18 in ./venv/lib/python3.9/site-packages (from ludwig==0.3.3) (1.6.3)
Requirement already satisfied: tabulate>=0.7 in ./venv/lib/python3.9/site-packages (from ludwig==0.3.3) (0.8.9)
Requirement already satisfied: scikit-learn in ./venv/lib/python3.9/site-packages (from ludwig==0.3.3) (0.24.2)
Requirement already satisfied: tqdm in ./venv/lib/python3.9/site-packages (from ludwig==0.3.3) (4.61.1)
Requirement already satisfied: tensorflow>=2.3.1 in ./venv/lib/python3.9/site-packages (from ludwig==0.3.3) (2.5.0)
ERROR: Could not find a version that satisfies the requirement tfa-nightly==0.12.0.dev20201215223743 (from ludwig) (from versions: 0.13.0.dev20210514172808, 0.13.0.dev20210514175928, 0.13.0.dev20210515174335, 0.14.0.dev20210515174343, 0.14.0.dev20210515190502, 0.14.0.dev20210528092347, 0.14.0.dev20210529132209, 0.14.0.dev20210605230927)
ERROR: No matching distribution found for tfa-nightly==0.12.0.dev20201215223743

**Comment by jimthompson5802** [comment]
@victoriayue   I ran the `pip install` command you tried and was able to install ludwig 0.3.3.  I noticed from the install log provided, some of the components appear to be already stored in the local pip cache.  In my case, I'm installing into an empty environment and all components are downloaded.

As a test can you try an install that bypasses the local pip cache, i.e., force a download of all components.
```
pip install --no-cache-dir install ludwig==0.3.3
```

Let me how if this works for you.

**Comment by victoriayue** [comment]
@jimthompson5802  :(

 % pip install --no-cache-dir ludwig==0.3.3

Collecting ludwig==0.3.3

  Downloading ludwig-0.3.3.tar.gz (233 kB)
     |████████████████████████████████| 233 kB 1.6 MB/s 
Requirement already satisfied: Cython>=0.25 in ./venv/lib/python3.9/site-packages (from ludwig==0.3.3) (0.29.23)
Collecting h5py<2.11.0,>=2.6
  Downloading h5py-2.10.0.tar.gz (301 kB)
     |████████████████████████████████| 301 kB 10.3 MB/s 
Requirement already satisfied: numpy>=1.15 in ./venv/lib/python3.9/site-packages (from ludwig==0.3.3) (1.19.5)
Collecting pandas<1.1.5,>=0.19
  Downloading pandas-1.1.4-cp39-cp39-macosx_10_9_x86_64.whl (10.3 MB)
     |████████████████████████████████| 10.3 MB 6.4 MB/s 
Requirement already satisfied: scipy>=0.18 in ./venv/lib/python3.9/site-packages (from ludwig==0.3.3) (1.6.3)
Requirement already satisfied: tabulate>=0.7 in ./venv/lib/python3.9/site-packages (from ludwig==0.3.3) (0.8.9)
Requirement already satisfied: scikit-learn in ./venv/lib/python3.9/site-packages (from ludwig==0.3.3) (0.24.2)
Requirement already satisfied: tqdm in ./venv/lib/python3.9/site-packages (from ludwig==0.3.3) (4.61.1)
Requirement already satisfied: tensorflow>=2.3.1 in ./venv/lib/python3.9/site-packages (from ludwig==0.3.3) (2.5.0)
ERROR: Could not find a version that satisfies the requirement tfa-nightly==0.12.0.dev20201215223743 (from ludwig) (from versions: 0.13.0.dev20210514172808, 0.13.0.dev20210514175928, 0.13.0.dev20210515174335, 0.14.0.dev20210515174343, 0.14.0.dev20210515190502, 0.14.0.dev20210528092347, 0.14.0.dev20210529132209, 0.14.0.dev20210605230927)
ERROR: No matching distribution found for tfa-nightly==0.12.0.dev20201215223743

**Comment by jimthompson5802** [comment]
For some reason, the pip install does not seem to be able to pickup `tfa-nightly==0.12.0.dev20201215223743`, which is one of the dependencies for ludwig 0.3.3.  

As a separate test, please try this pip install command.  We're now trying to see if there is a problem in installing that dependency.  
```
pip install tfa-nightly==0.12.0.dev20201215223743
```

**Comment by victoriayue** [comment]
@jimthompson5802 looks like the tfa-nightly doesn't have 0.12.0.dev20201215223743 version? just guess


pip install tfa-nightly==0.12.0.dev20201215223743

ERROR: Could not find a version that satisfies the requirement tfa-nightly==0.12.0.dev20201215223743 (from versions: 0.13.0.dev20210514172808, 0.13.0.dev20210514175928, 0.13.0.dev20210515174335, 0.14.0.dev20210515174343, 0.14.0.dev20210515190502, 0.14.0.dev20210528092347, 0.14.0.dev20210529132209, 0.14.0.dev20210605230927)
ERROR: No matching distribution found for tfa-nightly==0.12.0.dev20201215223743

**Comment by jimthompson5802** [comment]
@victoriayue   I may have an explanation. 

the `tfa-nightly` dependency is for the `tensorflow_addons` package.  It appears that this version of the package was built for only Python 3.6, 3.7 and 3.8.  Here is a screenshot of the [available downloads](https://pypi.org/project/tfa-nightly/0.12.0.dev20201215223743/#files) for this package:
<img width="881" alt="image" src="https://user-images.githubusercontent.com/1425269/121951135-880ef680-cd28-11eb-8524-58d2bcaa951e.png">

As you can see there is package file with the designation of `cp39`.  The highest is `cp38`.

From your initial posting,  you indicated your Python version is 3.9.  To install Ludwig 0.3.3, you'll have to create a virtual environment with Python 3.8 and install Ludwig in there.   FWIW...I've been using Python 3.6 without issues.

Let me know if this makes sense and if it helps you install ludwig.

**Comment by victoriayue** [comment]
@jimthompson5802 Thanks for the help. I try python 3.8 and it works!
