### ISSUE TITLE
can the sparse vector be the input

### ISSUE THREAD

**Issue by victoriayue** [ludwig-ai/ludwig#1218]
**Describe the bug**
Hello! I'm trying to input a list of sparse vectors and train a model. I don't know whether it's okay to do that or I need to convert that to a dense vector. And if that's acceptable, where should I put the shape, indices, and values of the sparse vector. 

(I don't know whether the bug report is the correct label. Please help me correct it if I use the wrong label. )

**Expected behavior**
training a model use list of sparse vector

**Environment (please complete the following information):**
 - OS: macOS
- Python version
- Ludwig version

**Comment by jimthompson5802** [comment]
@victoriayue If I understand your question, I believe you need to convert the sparse vector to a dense one.  Ludwig's Vector input Feature is a space delimited series of numbers.  Here is an example of a csv training dataset composed of a Vector Feature (vector_feature) and Binary Feature (binary_feature)
```
vector_feature,binary_feature
51.38606270274413 80.73319573085358 62.7727403279983 4.587607099598379 15.24970144929445,False
29.803288243709638 60.08213100193599 73.73784652333664 21.93298694366893 29.292694305468025,False
38.646278239925365 15.161082475268495 86.21106291062964 78.38362860932817 99.15160760017719,True
23.46773993845719 33.10421719416071 33.89892724515482 46.37575540075459 49.90850782689279,True
59.35601981291549 42.92168639560112 10.290440009017289 56.203608643716215 14.242072583576848,False
```

As you can see, the vector feature is a series of floating point numbers separated by a space (" ").   This is the link to Ludwig's User Guide on vector features: https://ludwig-ai.github.io/ludwig-docs/user_guide/configuration/#vector-features

Does this answer your question?

**Comment by victoriayue** [comment]
ok, I got it! Thanks for the help!
