### ISSUE TITLE
Why create a MultiHeadSelfAttention class instead of using tf.keras.layers.MultiHeadAttention

### ISSUE THREAD

**Issue by ericxsun** [ludwig-ai/ludwig#1221]
In attention_modules, why could we create a new class **[MultiHeadSelfAttention](https://github.com/ludwig-ai/ludwig/blob/b1bfb823d2dbfe638e859f4140dbcbe689b9a06e/ludwig/modules/attention_modules.py#L40)**, but does not use the implementation in **tf.keras.layers.MultiHeadAttention(ref [doc](https://www.tensorflow.org/api_docs/python/tf/keras/layers/MultiHeadAttention), [code](https://github.com/tensorflow/tensorflow/blob/v2.5.0/tensorflow/python/keras/layers/multi_head_attention.py#L124-L516))**

Is there any difference or something make sense?

**Comment by w4nderlust** [comment]
THat class was introduced in TF 2.5 and we want to be compatible with older versions too at the moment. When we'll get to the point where 2.5 is the minimum version we support, then we can do the switch. Anyway, there should not be any functional difference between our implementation and the TF one.
