### ISSUE TITLE
Image segmentation

### ISSUE THREAD

**Issue by rolisz** [ludwig-ai/ludwig#129]
Is there any architectural/technical limitation why Ludwig is not able to perform image segmentation? Or is it just not yet implemented?

**Comment by w4nderlust** [comment]
The output type of image segmentation is a matrix of class ids of the same size of the input image. That input type is not supported yet. But there is nothing preventing you from adding it. It is on our roadmap, but it may take a while to be implemented. We welcome contributions.

**Comment by slavakurilyak** [comment]
Any updates on semantic segmentation?

**Comment by w4nderlust** [comment]
@slavakurilyak Answering the same thing I answered for the GAN feature request.
