### ISSUE TITLE
Unable to generate predictions "OSError: [Errno 22] Invalid argument"

### ISSUE THREAD

**Issue by WhereAmO** [ludwig-ai/ludwig#1296]
Everytime I train a model and then try to run "ludwig predict", it does everything seemingly normally then suddenly throws an error at the end stating "OSError: [Errno 22] Invalid argument: 'results\\experiment_run_0\\Answers_probabilities_<UNK>.npy". It generates .npy files but they are all only 1kb. Any help?

**Comment by jimthompson5802** [comment]
@WhereAmO   More information is needed about the issue you are encountering.  Please provide the following:
* the exact command you are executing.
* the `config.yaml` file describing the network model
* most importantly, the log file from a failing run.

**Comment by WhereAmO** [comment]
Scratch that, I manged to get it working. I think I was using "category" wrong in the config, I should've been using binary. Though now after fixing that I am running into a completely different issue, there is no generated .csv file when it finishes doing the prediction. Everything else generates, including "predictions.parquet", but no generates .csv file. This was my config, also logs are below.

--------------------------
 input_features:
    -
        name: Questions
        type: text
        level: word

output_features:
    -
        name: Answers
        type: binary
--------------------------

[logs.zip](https://github.com/ludwig-ai/ludwig/files/7140985/logs.zip)

**Comment by w4nderlust** [comment]
@WhereAmO thanks for posting the details!
We are running into a bit of confusion as the docs haven't been updated yet, but right now there is not CSV that gets generated, only the parquet file. The contents are the same though, so if you load the parquet file with pandas for instance, you will find the predictions in there.
There's ongoing work to reinstitute the CSV output too: https://github.com/ludwig-ai/ludwig/pull/1236
And that's the reason why the docs have not been updated, csv will come back.
In the meantime, et me know if you can open the parquet file and if it contains the binary predictions for the Answers output feature.

**Comment by WhereAmO** [comment]
It indeed contained the predictions, I managed to convert the .parquet file to a .csv and it worked perfectly.

**Comment by w4nderlust** [comment]
Great to hear!
Will keep you posted regarding the final solution to the issue though!

**Comment by manivannansp** [comment]
I am new to python and using Ludwig. i am just trying your test sample 

ludwig train --dataset C:\data\train.csv --config "{input_features: [{name: doc_text, type: text}], output_features: [{name: class, type: category}]}"

Created the model

When i execute

ludwig predict --dataset C:\data\data.csv --model_path "C:\results\experiment_run\model" --output_directory "C:\data\predictions"

Getting below error:

Traceback (most recent call last):
  Traceback (most recent call last):
  File "C:\Users\Python\Python38\Scripts\ludwig-script.py", line 33, in <module>
    sys.exit(load_entry_point('ludwig==0.4', 'console_scripts', 'ludwig')())
  File "c:\users\python\python38\lib\site-packages\ludwig\cli.py", line 136, in main
    CLI()
  File "c:\users\python\python38\lib\site-packages\ludwig\cli.py", line 71, in __init__
    getattr(self, args.command)()
  File "c:\users\python\python38\lib\site-packages\ludwig\cli.py", line 79, in predict
    predict.cli(sys.argv[2:])
  File "c:\users\python\python38\lib\site-packages\ludwig\predict.py", line 268, in cli
    predict_cli(**vars(args))
  File "c:\users\python\python38\lib\site-packages\ludwig\predict.py", line 112, in predict_cli
    model.predict(
  File "c:\users\python\python38\lib\site-packages\ludwig\api.py", line 716, in predict
    postproc_predictions = postprocess(
  File "c:\users\python\python38\lib\site-packages\ludwig\data\postprocessing.py", line 56, in postprocess
    _save_as_numpy(predictions, output_directory, saved_keys)
  File "c:\users\python\python38\lib\site-packages\ludwig\data\postprocessing.py", line 70, in _save_as_numpy
    np.save(npy_filename.format(k), v)
  File "<__array_function__ internals>", line 5, in save
  File "c:\users\python\python38\lib\site-packages\numpy\lib\npyio.py", line 524, in save
    file_ctx = open(file, "wb")
OSError: [Errno 22] Invalid argument: 'C:\\data\\predictions\\class_probabilities_<UNK>.npy'

using your training data

doc_text,class
Former president Barack Obama ,	politics
Juventus hired Cristiano Ronaldo ,	sport
LeBron James joins the Lakers ,	spor

**Comment by w4nderlust** [comment]
@manivannansp this looks like a separate issue, would you be so kind to open a new one for it? Thank you.

**Comment by connor-mccorm** [comment]
Closing as the original issue has been resolved.
