### ISSUE TITLE
OSError: [Errno 22] Invalid argument: 'C:\data\predictions\class_probabilities.npy'

### ISSUE THREAD

**Issue by manivannansp** [ludwig-ai/ludwig#1334]
**Describe the bug**
I am new to python and using Ludwig. i am just trying your test sample

ludwig train --dataset C:\data\train.csv --config "{input_features: [{name: doc_text, type: text}], output_features: [{name: class, type: category}]}"

Created the model

When i execute

ludwig predict --dataset C:\data\data.csv --model_path "C:\results\experiment_run\model" --output_directory "C:\data\predictions"

Getting below error:

Traceback (most recent call last):
Traceback (most recent call last):
File "C:\Users\Python\Python38\Scripts\ludwig-script.py", line 33, in
sys.exit(load_entry_point('ludwig==0.4', 'console_scripts', 'ludwig')())
File "c:\users\python\python38\lib\site-packages\ludwig\cli.py", line 136, in main
CLI()
File "c:\users\python\python38\lib\site-packages\ludwig\cli.py", line 71, in init
getattr(self, args.command)()
File "c:\users\python\python38\lib\site-packages\ludwig\cli.py", line 79, in predict
predict.cli(sys.argv[2:])
File "c:\users\python\python38\lib\site-packages\ludwig\predict.py", line 268, in cli
predict_cli(**vars(args))
File "c:\users\python\python38\lib\site-packages\ludwig\predict.py", line 112, in predict_cli
model.predict(
File "c:\users\python\python38\lib\site-packages\ludwig\api.py", line 716, in predict
postproc_predictions = postprocess(
File "c:\users\python\python38\lib\site-packages\ludwig\data\postprocessing.py", line 56, in postprocess
_save_as_numpy(predictions, output_directory, saved_keys)
File "c:\users\python\python38\lib\site-packages\ludwig\data\postprocessing.py", line 70, in save_as_numpy
np.save(npy_filename.format(k), v)
File "<array_function internals>", line 5, in save
File "c:\users\python\python38\lib\site-packages\numpy\lib\npyio.py", line 524, in save
file_ctx = open(file, "wb")
OSError: [Errno 22] Invalid argument: 'C:\data\predictions\class_probabilities.npy'

using your training data

doc_text,class
Former president Barack Obama , politics
Juventus hired Cristiano Ronaldo , sport
LeBron James joins the Lakers , spor

**To Reproduce**
I did the same setup as described in your document, but in windows

 

**Environment (please complete the following information):**
 - OS: Windows Server 2019
 
- Python version :3.8.10
- Ludwig version: 0.4

**Comment by w4nderlust** [comment]
Thanks for posting it in a separate Issue, will try to replicate and get back to you soon.

**Comment by maragato2000** [comment]
Hello same here with not a very different and simple model. In my case the error shows OSError: [Errno 22] Invalid argument: 'results\\class_probabilities_<UNK>.npy'

**the exact command I am executing >>>>**   (ludwigenv) C:\Users\GT>ludwig predict --dataset C:/GT/TestKyri/Jan2018AplicarMod.csv --model_path C:/Users/GT/results/experiment_run/model

**the config.yaml file describing the network model >>>>**{input_features: [{name: doc_text, type: text}], output_features: [{name: class, type: category}]}


[logs.zip](https://github.com/ludwig-ai/ludwig/files/7566997/logs.zip)
**most importantly, the log file from a failing run >>>>**


Evaluation: 100%|
C:\Users\GT\Anaconda3\envs\ludwigenv\lib\site-packages\sklearn\metrics\_classification.py:1308: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\GT\Anaconda3\envs\ludwigenv\lib\site-packages\sklearn\metrics\_classification.py:1308: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
Traceback (most recent call last):
  File "C:\Users\GT\Anaconda3\envs\ludwigenv\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\GT\Anaconda3\envs\ludwigenv\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\GT\Anaconda3\envs\ludwigenv\Scripts\ludwig.exe\__main__.py", line 7, in <module>
  File "C:\Users\GT\Anaconda3\envs\ludwigenv\lib\site-packages\ludwig\cli.py", line 136, in main
    CLI()
  File "C:\Users\GT\Anaconda3\envs\ludwigenv\lib\site-packages\ludwig\cli.py", line 71, in __init__
    getattr(self, args.command)()
  File "C:\Users\GT\Anaconda3\envs\ludwigenv\lib\site-packages\ludwig\cli.py", line 83, in evaluate
    evaluate.cli(sys.argv[2:])
  File "C:\Users\GT\Anaconda3\envs\ludwigenv\lib\site-packages\ludwig\evaluate.py", line 295, in cli
    evaluate_cli(**vars(args))
  File "C:\Users\GT\Anaconda3\envs\ludwigenv\lib\site-packages\ludwig\evaluate.py", line 122, in evaluate_cli
    model.evaluate(
  File "C:\Users\GT\Anaconda3\envs\ludwigenv\lib\site-packages\ludwig\api.py", line 871, in evaluate
    postproc_predictions = postprocess(
  File "C:\Users\GT\Anaconda3\envs\ludwigenv\lib\site-packages\ludwig\data\postprocessing.py", line 56, in postprocess
    _save_as_numpy(predictions, output_directory, saved_keys)
  File "C:\Users\GT\Anaconda3\envs\ludwigenv\lib\site-packages\ludwig\data\postprocessing.py", line 69, in _save_as_numpy
    np.save(npy_filename.format(k), v)
  File "<__array_function__ internals>", line 5, in save
  File "C:\Users\GT\Anaconda3\envs\ludwigenv\lib\site-packages\numpy\lib\npyio.py", line 525, in save
    file_ctx = open(file, "wb")
OSError: [Errno 22] Invalid argument: 'results\\class_probabilities_<UNK>.npy'

**Comment by maragato2000** [comment]
OSError: [Errno 22] Invalid argument: 'results\\class_probabilities_<UNK>.npy'
Please read the erro as follows instead as UNK and signes does not show up in the posted text  >>>>   OSError: [Errno 22] Invalid argument: 'results\\class_probabilities_"smaller than sign" UNK "bigger than sign".npy'

**Comment by w4nderlust** [comment]
@maragato2000 getting back to this now, sorry for the delay. Can yo utry with the current 0.5rc2 version? It hsoudl have fixed the issue.

**Comment by maragato2000** [comment]
Hello Piero,

Thanks for your reply. Once installed the new version i now have
another issue.  I have tried re-installing Pytorch, but no difference...

ModuleNotFoundError: No module named 'torchvision'

(LudwigEnv) C:\Users\GT>ludwig train --dataset
C:/GT/TestKyri/2017KYRILABEL.csv --config "{input_features: [{name:
doc_text, type: text}], output_features: [{name: class, type: category}]}"
NumExpr defaulting to 8 threads.
Traceback (most recent call last):
  File "C:\Users\GT\Anaconda3\envs\LudwigEnv\lib\runpy.py", line 194, in
_run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\GT\Anaconda3\envs\LudwigEnv\lib\runpy.py", line 87, in
_run_code
    exec(code, run_globals)
  File
"C:\Users\GT\Anaconda3\envs\LudwigEnv\Scripts\ludwig.exe\__main__.py", line
7, in <module>
  File
"C:\Users\GT\Anaconda3\envs\LudwigEnv\lib\site-packages\ludwig\cli.py",
line 157, in main
    CLI()
  File
"C:\Users\GT\Anaconda3\envs\LudwigEnv\lib\site-packages\ludwig\cli.py",
line 62, in __init__
    getattr(self, args.command)()
  File
"C:\Users\GT\Anaconda3\envs\LudwigEnv\lib\site-packages\ludwig\cli.py",
line 65, in train
    from ludwig import train
  File
"C:\Users\GT\Anaconda3\envs\LudwigEnv\lib\site-packages\ludwig\train.py",
line 23, in <module>
    from ludwig.api import LudwigModel
  File
"C:\Users\GT\Anaconda3\envs\LudwigEnv\lib\site-packages\ludwig\api.py",
line 38, in <module>
    from ludwig.backend import Backend, initialize_backend
  File
"C:\Users\GT\Anaconda3\envs\LudwigEnv\lib\site-packages\ludwig\backend\__init__.py",
line 20, in <module>
    from ludwig.backend.base import Backend, LocalBackend
  File
"C:\Users\GT\Anaconda3\envs\LudwigEnv\lib\site-packages\ludwig\backend\base.py",
line 24, in <module>
    from ludwig.models.ecd import ECD
  File
"C:\Users\GT\Anaconda3\envs\LudwigEnv\lib\site-packages\ludwig\models\ecd.py",
line 10, in <module>
    from ludwig.combiners.combiners import Combiner, get_combiner_class
  File
"C:\Users\GT\Anaconda3\envs\LudwigEnv\lib\site-packages\ludwig\combiners\combiners.py",
line 28, in <module>
    from ludwig.encoders.sequence_encoders import ParallelCNN, StackedCNN,
StackedCNNRNN, StackedParallelCNN, StackedRNN
  File
"C:\Users\GT\Anaconda3\envs\LudwigEnv\lib\site-packages\ludwig\encoders\__init__.py",
line 8, in <module>
    import ludwig.encoders.image_encoders
  File
"C:\Users\GT\Anaconda3\envs\LudwigEnv\lib\site-packages\ludwig\encoders\image_encoders.py",
line 24, in <module>
    from ludwig.modules.convolutional_modules import Conv2DStack, ResNet
  File
"C:\Users\GT\Anaconda3\envs\LudwigEnv\lib\site-packages\ludwig\modules\convolutional_modules.py",
line 22, in <module>
    from ludwig.utils.image_utils import get_img_output_shape
  File
"C:\Users\GT\Anaconda3\envs\LudwigEnv\lib\site-packages\ludwig\utils\image_utils.py",
line 26, in <module>
    import torchvision.transforms.functional as F
ModuleNotFoundError: No module named 'torchvision'


Best
MaraGato

Le sam. 26 mars 2022 à 00:41, Piero Molino ***@***.***> a
écrit :

**Comment by w4nderlust** [comment]
@maragato2000 we are going to change the dependency structure to have torchvision, torchtext and torchaudio as main dependencies, but for the time being those dependencies are part of subpackages. Fort torchvision in particular the `[image]` subpackage contains it. I suggest you create a new env for ludwig 0.5rc2, if you install from a local git clone, I'd do `pip install .[image]` for instance.

**Comment by maragato2000** [comment]
Thank you Piero,
I made to run... now I am phasing another issue on which i need your help.
This has already been raised and i believe it will be quickly be fixed.

While trying to prejudice on  a text classification with this:

 If i* run it without a slash before de model_path  *(LudwigEnv)
C:\Users\GT>ludwig
predict --dataset C:/GT/TestKyri/Jan2018AplicarMod.csv --model_path
C:/Users/GT/results/experiment_run_3/model
>> i obtain this error message:  OSError: [Errno 22] Invalid argument:
'C:/Users/GT/results/class_probabilities_<UNK>.csv'

So UNK appears unresolved  on the results probabilities instead of the 3
value i would have expected to see ...

If i* run it with a slash before de model_path*         (LudwigEnv)
C:\Users\GT>ludwig predict --dataset C:/GT/TestKyri/Jan2018AplicarMod.csv
--model_path */*C:/Users/GT/results/experiment_run_3/model
>> I obtain this error message:  OSError: [Errno 22] Invalid argument:
'/C:/Users/GT/results/experiment_run_3/model\\model_weights'

So what (other) command should be run to get it working correctly ?

Thanks !
Mara

Le dim. 17 avr. 2022 à 02:28, Piero Molino ***@***.***> a
écrit :

**Comment by w4nderlust** [comment]
@maragato2000 it seems to me you are on a windows machine, judging from the prompt, have you tried using regular windows paths? The error `'/C:/Users/GT/results/experiment_run_3/model\\model_weights'` suggests that the directory model_weigths is added to the path correctly following the windows convention, but the path up to that point was not, which is the one you provided.

So can you try just:
```
C:\Users\GT>ludwig predict --dataset C:\GT\TestKyri\Jan2018AplicarMod.csv
--model_path C:\Users\GT\results\experiment_run_3\model
```
?

**Comment by maragato2000** [comment]
Im afraid it throws still the same similar error:  OSError: [Errno 22]
Invalid argument: 'C:/Users/GT/results/class_probabilities_<UNK>.

I am using Windows yes  as i you say but something tells me your code takes
this as a string with an embedded variable to handle the number of run, and
executes in Python which has the slash convention different from the
windows path.  Something indeed goes wrong on your python code when
handling this... Maybe linked to the fact that the mode_path requires to
start with a /

The closer i get is when using ludwig predict --dataset
C:/GT/TestKyri/Jan2018AplicarMod.csv --model_path
/C:/Users/GT/results/experiment_run_3/model/

But still getting OSError: [Errno 22] Invalid argument:
'/C:/Users/GT/results/experiment_run_3/model/model_weights'


Best Regards,
GT

Thank you Piero and Ba

Le mer. 20 avr. 2022 à 01:35, Piero Molino ***@***.***> a
écrit :

**Comment by w4nderlust** [comment]
@maragato2000 we try to use OS safe functions in Python everywhere in the codebase to deal with paths, so directory dividers shouldn't be an issue.
Looking at the code, it looks to me there should be no issue:
https://github.com/ludwig-ai/ludwig/blob/a8165d07a07f41ddee6b1051e37479369c1e40e7/ludwig/data/postprocessing.py#L59

In order to help you out and try to debug then, it would be great if you could provide a small script that can replicate the issue. You can use `synthesyze_dataset` for creting a small dataset programmatically within your script.

@brightsparc FYI as I believe you debugged a similar windows issue in the past.

**Comment by brightsparc** [comment]
Yes the PR #1830 was aimed at resolving this issues for artefacts created from URL paths on windows machines. This looks like a different code path but the fix might be similar once we can repo issue.

**Comment by dalianaliu** [comment]
Closing this issue @manivannansp, please re-open if you still have questions. Thanks!
