### ISSUE TITLE
REFS_OK flag was not enabled

### ISSUE THREAD

**Issue by sizhky** [ludwig-ai/ludwig#1390]
**Issue**
I'm getting above error on trying to train mnist in colab

Here's the last stack trace - 
```
File "/usr/local/lib/python3.7/dist-packages/ludwig/utils/data_utils.py", line 368, in save_array
    for x in np.nditer(array):
TypeError: Iterator operand or requested dtype holds references, but the REFS_OK flag was not enabled
``` 

**To Reproduce**
Run this notebook - https://gist.github.com/sizhky/adac2821f76335cb0f72592ab332673a

**Environment (please complete the following information):**
 - Whatever is the latest in google colab

**Comment by tgaddair** [comment]
Hey @sizhky, sorry for the late reply. Do you also get this error when you run the official mnist example [here](https://github.com/ludwig-ai/ludwig/tree/master/examples/mnist)?
