### ISSUE TITLE
Eval batch size does not scale at runtime with train batch size

### ISSUE THREAD

**Issue by tgaddair** [ludwig-ai/ludwig#1403]
The eval batch size is only set once at the beginning of training. However, the train batch size can scale up during training. When this happens, we should also increase the eval batch size, if possible, as any batch size that works for training should also work for inference.

https://github.com/ludwig-ai/ludwig/blob/master/ludwig/models/trainer.py#L909

Specifically:

```
eval_batch_size = max(eval_batch_size, progress_tracker.batch_size)
```

See #1389.

cc @carlogrisetti

**Comment by w4nderlust** [comment]
Makes total sense.
