### ISSUE TITLE
Allow eval_batch_size=auto in the config

### ISSUE THREAD

**Issue by tgaddair** [ludwig-ai/ludwig#1404]
The eval batch size can be set arbitrarily large without consequence in most cases, particularly if the user has a GPU. We just need to make sure we don't OOM. Similar to supporting this for the train batch size, we should support setting it for the eval batch size as well.

```
{
    'training': {
        'eval_batch_size': 'auto'
    }
}
```

See #1389.

**Comment by w4nderlust** [comment]
Also this one makes a lot of sense. because of the lack of gradients i expect the eval batch size could grow to up to 2x the the already optimized train batch size.
