### ISSUE TITLE
MAPE MeanAbsolutePercentageError 

### ISSUE THREAD

**Issue by PeterPirog** [ludwig-ai/ludwig#1501]
In some cases in regression if values range is wide, the best option is to use MeanAbsolutePercentageError.
For example , sometimes I have to  predict output values in  range from 1 do 1000 and my error is about 2.

So:
for 1,  value 2 is 200 %  error
for 1000, value 2 is 0.2 %  error

If the  high values are fitted very well,  low values fitting is terrible.

Source:
[https://en.wikipedia.org/wiki/Mean_absolute_percentage_error](https://en.wikipedia.org/wiki/Mean_absolute_percentage_error)
[https://www.tensorflow.org/api_docs/python/tf/keras/metrics/MeanAbsolutePercentageError](https://www.tensorflow.org/api_docs/python/tf/keras/metrics/MeanAbsolutePercentageError)

Is possible to define own error function and add it to the ludwig?

**Comment by tgaddair** [comment]
Hey @PeterPirog, yes, it is possible to add new loss functions and metrics to Ludwig. Currently it involves making a couple changes to the Ludwig code base, but we're working on ways to make it more easily extensible in the future.

Here is where losses are defined: [loss_modules.py](https://github.com/ludwig-ai/ludwig/blob/master/ludwig/modules/loss_modules.py)
And here is where metrics are defined: [metric_modules.py](https://github.com/ludwig-ai/ludwig/blob/master/ludwig/modules/metric_modules.py)
And here's where the loss is registered to the feature type: [numerical_feature.py](https://github.com/ludwig-ai/ludwig/blob/master/ludwig/features/numerical_feature.py#L302)

Note that the master branch of Ludwig is using the unreleased PyTorch backend. If you want to make this change for TensorFlow, there is a [tf-legacy](https://github.com/ludwig-ai/ludwig/tree/tf-legacy) branch from which we will release v0.4.1.

**Comment by PeterPirog** [comment]
@tgaddair  I try to add MAPE error, but there are some errors:

```
  File "g:\pycharmremote\ludwig\ludwig\features\feature_registries.py", line 18, in <module>
    from ludwig.features.audio_feature import AudioFeatureMixin, AudioInputFeature

  File "g:\pycharmremote\ludwig\ludwig\features\audio_feature.py", line 27, in <module>
    from ludwig.features.sequence_feature import SequenceInputFeature

  File "g:\pycharmremote\ludwig\ludwig\features\sequence_feature.py", line 29, in <module>
    from ludwig.modules.metric_modules import EditDistanceMetric, \

  File "g:\pycharmremote\ludwig\ludwig\modules\metric_modules.py", line 52, in <module>
    MEAN_ABSOLUTE_PERCENTAGE_ERROR,
NameError: name 'MEAN_ABSOLUTE_PERCENTAGE_ERROR' is not defined
```


[https://github.com/PeterPirog/ludwig/blob/add_mape/ludwig/modules/metric_modules.py](https://github.com/PeterPirog/ludwig/blob/add_mape/ludwig/modules/metric_modules.py)
[https://github.com/PeterPirog/ludwig/blob/add_mape/ludwig/modules/loss_modules.py](https://github.com/PeterPirog/ludwig/blob/add_mape/ludwig/modules/loss_modules.py)
[https://github.com/PeterPirog/ludwig/blob/add_mape/ludwig/features/numerical_feature.py](https://github.com/PeterPirog/ludwig/blob/add_mape/ludwig/features/numerical_feature.py)
