### ISSUE TITLE
Training on GPU throws "Expected all tensors to be on the same device" error

### ISSUE THREAD

**Issue by smiralr** [ludwig-ai/ludwig#1534]
**Describe the bug**
Env: ludwigai/ludwig-gpu:master Docker container
on a GPU AWS Instance with all drivers working and GPU Accessible within the docker container
According to documentation ludwigmodel takes gpus param as gpus="0"
According to documentation model.train takes gpus param as gpus="0"
Exception thrown:
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument index in method wrapper__index_select)

**To Reproduce**
1. spin up a ludwigai/ludwig-gpu:master Docker container with jupyter
2. Intialize config data for parallel cnn + glove embeddings
3. Declare and train model with :
model = LudwigModel(model_definition,gpus="0",logging_level=logging.DEBUG)
parallel_cnn_glove_embeds_train_stats, _, _ = model.train(dataset=training_df,experiment_name=experiment_name, model_name=model_name, output_directory=output_directory, gpus="0")

**Expected behavior**
Train on gpu start

**Environment (please complete the following information):**
- Python 3.7.11 (default, Jul 27 2021, 14:32:16) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
- ludwigai/ludwig-gpu:master env

**Additional context**
Stacktrace:
Experiment name: ParallelCNN_GLOVE_1
Model name: ParallelCNN_GloveEmbeddings
Output directory: models/results/ParallelCNN_GLOVE_1_ParallelCNN_GloveEmbeddings

ludwig_version: '0.5.dev0'
command: ('/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py -f '
 '/root/.local/share/jupyter/runtime/kernel-65fbea1a-50d2-4c5f-932b-2895ea7abbc9.json')
random_seed: 42
data_format: "<class 'pandas.core.frame.DataFrame'>"
config: {   'combiner': {'type': 'concat'},
    'input_features': [   {   'column': 'clean_title',
                              'embedding_size': 300,
                              'encoder': 'parallel_cnn',
                              'level': 'word',
                              'name': 'clean_title',
                              'preprocessing': {   'word_vocab_file': '../embeddings/glove/glove.6B.300d.txt'},
                              'pretrained_embeddings': '../embeddings/glove/glove.6B.300d.txt',
                              'proc_column': 'clean_title_Um5Kye',
                              'tied': None,
                              'type': 'text'}],
    'output_features': [   {   'column': 'category',
                               'dependencies': [],
                               'loss': {   'class_similarities_temperature': 0,
                                           'class_weights': 1,
                                           'confidence_penalty': 0,
                                           'labels_smoothing': 0,
                                           'robust_lambda': 0,
                                           'type': 'softmax_cross_entropy',
                                           'weight': 1},
                               'name': 'category',
                               'proc_column': 'category_mZFLky',
                               'reduce_dependencies': 'sum',
                               'reduce_input': 'sum',
                               'top_k': 3,
                               'type': 'category'}],
    'preprocessing': {   'audio': {   'audio_feature': {'type': 'raw'},
                                      'audio_file_length_limit_in_s': 7.5,
                                      'in_memory': True,
                                      'missing_value_strategy': 'backfill',
                                      'norm': None,
                                      'padding_value': 0},
                         'bag': {   'fill_value': '<UNK>',
                                    'lowercase': False,
                                    'missing_value_strategy': 'fill_with_const',
                                    'most_common': 10000,
                                    'tokenizer': 'space'},
                         'binary': {   'fill_value': 0,
                                       'missing_value_strategy': 'fill_with_const'},
                         'category': {   'fill_value': '<UNK>',
                                         'lowercase': False,
                                         'missing_value_strategy': 'fill_with_const',
                                         'most_common': 10000},
                         'date': {   'datetime_format': None,
                                     'fill_value': '',
                                     'missing_value_strategy': 'fill_with_const'},
                         'force_split': True,
                         'h3': {   'fill_value': 576495936675512319,
                                   'missing_value_strategy': 'fill_with_const'},
                         'image': {   'in_memory': True,
                                      'infer_image_dimensions': True,
                                      'infer_image_max_height': 256,
                                      'infer_image_max_width': 256,
                                      'infer_image_num_channels': True,
                                      'infer_image_sample_size': 100,
                                      'missing_value_strategy': 'backfill',
                                      'num_processes': 1,
                                      'resize_method': 'interpolate',
                                      'scaling': 'pixel_normalization'},
                         'numerical': {   'fill_value': 0,
                                          'missing_value_strategy': 'fill_with_const',
                                          'normalization': None},
                         'sequence': {   'fill_value': '<UNK>',
                                         'lowercase': False,
                                         'missing_value_strategy': 'fill_with_const',
                                         'most_common': 20000,
                                         'padding': 'right',
                                         'padding_symbol': '<PAD>',
                                         'sequence_length_limit': 256,
                                         'tokenizer': 'space',
                                         'unknown_symbol': '<UNK>',
                                         'vocab_file': None},
                         'set': {   'fill_value': '<UNK>',
                                    'lowercase': False,
                                    'missing_value_strategy': 'fill_with_const',
                                    'most_common': 10000,
                                    'tokenizer': 'space'},
                         'split_probabilities': [0.7, 0.1, 0.2],
                         'stratify': 'category',
                         'text': {   'char_most_common': 70,
                                     'char_sequence_length_limit': 1024,
                                     'char_tokenizer': 'characters',
                                     'char_vocab_file': None,
                                     'fill_value': '<UNK>',
                                     'lowercase': True,
                                     'missing_value_strategy': 'fill_with_const',
                                     'padding': 'right',
                                     'padding_symbol': '<PAD>',
                                     'pretrained_model_name_or_path': None,
                                     'unknown_symbol': '<UNK>',
                                     'word_most_common': 20000,
                                     'word_sequence_length_limit': 256,
                                     'word_tokenizer': 'space_punct',
                                     'word_vocab_file': None},
                         'timeseries': {   'fill_value': '',
                                           'missing_value_strategy': 'fill_with_const',
                                           'padding': 'right',
                                           'padding_value': 0,
                                           'timeseries_length_limit': 256,
                                           'tokenizer': 'space'},
                         'vector': {   'fill_value': '',
                                       'missing_value_strategy': 'fill_with_const'}},
    'training': {   'batch_size': 128,
                    'bucketing_field': None,
                    'decay': True,
                    'decay_rate': 0.96,
                    'decay_steps': 10000,
                    'early_stop': 5,
                    'epochs': 12,
                    'eval_batch_size': None,
                    'gradient_clipping': None,
                    'increase_batch_size_on_plateau': 0,
                    'increase_batch_size_on_plateau_max': 512,
                    'increase_batch_size_on_plateau_patience': 5,
                    'increase_batch_size_on_plateau_rate': 2,
                    'learning_rate': 0.001,
                    'learning_rate_warmup_epochs': 1,
                    'optimizer': {   'betas': (0.9, 0.999),
                                     'eps': 1e-08,
                                     'type': 'adam'},
                    'reduce_learning_rate_on_plateau': 0,
                    'reduce_learning_rate_on_plateau_patience': 5,
                    'reduce_learning_rate_on_plateau_rate': 0.5,
                    'regularization_lambda': 0,
                    'regularization_type': 'l2',
                    'staircase': False,
                    'validation_field': 'category',
                    'validation_metric': 'accuracy'}}
torch_version: '1.10.0'

Using full dataframe
Building dataset (it may take a while)
cast columns
build metadata
build data
get split
split on split column
cache processed data
Writing preprocessed training set cache
Writing preprocessed test set cache
Writing preprocessed validation set cache
Writing train set metadata
create training dataset
create validation dataset
create test dataset
Training set: 27445
Validation set: 3838
Test set: 7768

╒═══════╕
│ MODEL │
╘═══════╛

Input text feature clean_title
 ParallelCNN
  EmbedSequence
  Loading Glove format file ../embeddings/glove/glove.6B.300d.txt
  400000 embeddings loaded
  ParallelConv1D
   parallel layer 0
   Conv1d
   ReLU
ParallelConv1D layer 0, input shape torch.Size([256, 300]), output shape torch.Size([256, 256])
   parallel layer 1
   Conv1d
   ReLU
ParallelConv1D layer 1, input shape torch.Size([256, 300]), output shape torch.Size([256, 256])
   parallel layer 2
   Conv1d
   ReLU
ParallelConv1D layer 2, input shape torch.Size([256, 300]), output shape torch.Size([256, 256])
   parallel layer 3
   Conv1d
   ReLU
ParallelConv1D layer 3, input shape torch.Size([256, 300]), output shape torch.Size([256, 256])
  FCStack
Combiner concat
 ConcatCombiner
  FCStack
Output category feature category
 output feature fully connected layers
  FCStack
 Classifier
  Dense

╒══════════╕
│ TRAINING │
╘══════════╛

Epoch  1
Training:   0%|                                                                                                                                     | 0/215 [00:00<?, ?it/s]
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
/tmp/ipykernel_12/4050990918.py in <module>
      1 #training the model
      2 model = LudwigModel(model_definition,gpus="0",logging_level=logging.DEBUG)
----> 3 parallel_cnn_glove_embeds_train_stats, _, _ = model.train(dataset=training_df,experiment_name=experiment_name, model_name=model_name, output_directory=output_directory, gpus="0")

/opt/conda/lib/python3.7/site-packages/ludwig/api.py in train(self, dataset, training_set, validation_set, test_set, training_set_metadata, data_format, experiment_name, model_name, model_resume_path, skip_save_training_description, skip_save_training_statistics, skip_save_model, skip_save_progress, skip_save_log, skip_save_processed_input, output_directory, random_seed, debug, **kwargs)
    551                         validation_set=validation_set,
    552                         test_set=test_set,
--> 553                         save_path=model_dir,
    554                     )
    555 

/opt/conda/lib/python3.7/site-packages/ludwig/models/trainer.py in train(self, model, training_set, validation_set, test_set, save_path, **kwargs)
    888                         model,
    889                         inputs,
--> 890                         targets,
    891                     )
    892 

/opt/conda/lib/python3.7/site-packages/ludwig/models/trainer.py in train_step(self, model, inputs, targets)
    312 
    313         # Obtain model predictions and loss
--> 314         model_outputs = model((inputs, targets))
    315         loss, all_losses = model.train_loss(
    316             targets,

/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
   1100         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1101                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1102             return forward_call(*input, **kwargs)
   1103         # Do not call functions when jit is used
   1104         full_backward_hooks, non_full_backward_hooks = [], []

/opt/conda/lib/python3.7/site-packages/ludwig/models/ecd.py in forward(self, inputs, mask)
    138         for input_feature_name, input_values in inputs.items():
    139             encoder = self.input_features[input_feature_name]
--> 140             encoder_output = encoder(input_values)
    141             encoder_outputs[input_feature_name] = encoder_output
    142 

/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
   1100         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1101                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1102             return forward_call(*input, **kwargs)
   1103         # Do not call functions when jit is used
   1104         full_backward_hooks, non_full_backward_hooks = [], []

/opt/conda/lib/python3.7/site-packages/ludwig/features/text_feature.py in forward(self, inputs, mask)
    278         inputs_exp = inputs.type(torch.int32)
    279         lengths = torch.sum(inputs_mask.type(torch.int32), dim=1)
--> 280         encoder_output = self.encoder_obj(inputs_exp, mask=inputs_mask)
    281         encoder_output[LENGTHS] = lengths
    282 

/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
   1100         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1101                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1102             return forward_call(*input, **kwargs)
   1103         # Do not call functions when jit is used
   1104         full_backward_hooks, non_full_backward_hooks = [], []

/opt/conda/lib/python3.7/site-packages/ludwig/encoders/sequence_encoders.py in forward(self, inputs, mask)
    498         # ================ Embeddings ================
    499         if self.should_embed:
--> 500             embedded_sequence = self.embed_sequence(inputs, mask=mask)
    501         else:
    502             embedded_sequence = inputs

/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
   1100         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1101                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1102             return forward_call(*input, **kwargs)
   1103         # Do not call functions when jit is used
   1104         full_backward_hooks, non_full_backward_hooks = [], []

/opt/conda/lib/python3.7/site-packages/ludwig/modules/embedding_modules.py in forward(self, inputs, mask)
    417             )
    418 
--> 419         embedded = self.embeddings(inputs)
    420         if self.dropout:
    421             embedded = self.dropout(embedded)

/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
   1100         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1101                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1102             return forward_call(*input, **kwargs)
   1103         # Do not call functions when jit is used
   1104         full_backward_hooks, non_full_backward_hooks = [], []

/opt/conda/lib/python3.7/site-packages/torch/nn/modules/sparse.py in forward(self, input)
    158         return F.embedding(
    159             input, self.weight, self.padding_idx, self.max_norm,
--> 160             self.norm_type, self.scale_grad_by_freq, self.sparse)
    161 
    162     def extra_repr(self) -> str:

/opt/conda/lib/python3.7/site-packages/torch/nn/functional.py in embedding(input, weight, padding_idx, max_norm, norm_type, scale_grad_by_freq, sparse)
   2042         # remove once script supports set_grad_enabled
   2043         _no_grad_embedding_renorm_(weight, input, max_norm, norm_type)
-> 2044     return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
   2045 
   2046 

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument index in method wrapper__index_select)

### **GPU Command outputs:**
!nvidia-smi
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 495.29.05    Driver Version: 495.29.05    CUDA Version: 11.5     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            On   | 00000000:00:1E.0 Off |                    0 |
| N/A   25C    P8     9W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

!/usr/local/cuda/bin/nvcc --version

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Mon_May__3_19:15:13_PDT_2021
Cuda compilation tools, release 11.3, V11.3.109
Build cuda_11.3.r11.3/compiler.29920130_0

**Comment by tgaddair** [comment]
cc @ShreyaR 

Thanks for reporting @smiralr. The GPU support for PyTorch on master is still a work in progress, and will be fixed by #1508. In the meantime, if you want to use something more stable, the `tf-legacy` branch should work as expected (though it uses tensorflow).

**Comment by smiraldr** [comment]
Still facing the same issue for ludwigai/ludwig-gpu:master
DIGEST:sha256:28cb0c32af7f2bbab6b6f008626ae17259c31753c5e93babe0f9ee337d53b5f2

Logs:

ludwig_version: '0.5.dev0'
command: ('/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py -f '
 '/root/.local/share/jupyter/runtime/kernel-03774536-4fca-4ef9-a720-4faa191ca7d0.json')
random_seed: 42
data_format: "<class 'pandas.core.frame.DataFrame'>"
config: {   'combiner': {'type': 'concat'},
    'input_features': [   {   'column': 'clean_title',
                              'encoder': 'electra',
                              'level': 'word',
                              'name': 'clean_title',
                              'proc_column': 'clean_title_mZFLky',
                              'tied': None,
                              'type': 'text'}],
    'output_features': [   {   'column': 'category',
                               'dependencies': [],
                               'loss': {   'class_similarities_temperature': 0,
                                           'class_weights': 1,
                                           'confidence_penalty': 0,
                                           'labels_smoothing': 0,
                                           'robust_lambda': 0,
                                           'type': 'softmax_cross_entropy',
                                           'weight': 1},
                               'name': 'category',
                               'proc_column': 'category_mZFLky',
                               'reduce_dependencies': 'sum',
                               'reduce_input': 'sum',
                               'top_k': 3,
                               'type': 'category'}],
    'preprocessing': {   'audio': {   'audio_feature': {'type': 'raw'},
                                      'audio_file_length_limit_in_s': 7.5,
                                      'in_memory': True,
                                      'missing_value_strategy': 'backfill',
                                      'norm': None,
                                      'padding_value': 0},
                         'bag': {   'fill_value': '<UNK>',
                                    'lowercase': False,
                                    'missing_value_strategy': 'fill_with_const',
                                    'most_common': 10000,
                                    'tokenizer': 'space'},
                         'binary': {   'fill_value': 0,
                                       'missing_value_strategy': 'fill_with_const'},
                         'category': {   'fill_value': '<UNK>',
                                         'lowercase': False,
                                         'missing_value_strategy': 'fill_with_const',
                                         'most_common': 10000},
                         'date': {   'datetime_format': None,
                                     'fill_value': '',
                                     'missing_value_strategy': 'fill_with_const'},
                         'force_split': True,
                         'h3': {   'fill_value': 576495936675512319,
                                   'missing_value_strategy': 'fill_with_const'},
                         'image': {   'in_memory': True,
                                      'infer_image_dimensions': True,
                                      'infer_image_max_height': 256,
                                      'infer_image_max_width': 256,
                                      'infer_image_num_channels': True,
                                      'infer_image_sample_size': 100,
                                      'missing_value_strategy': 'backfill',
                                      'num_processes': 1,
                                      'resize_method': 'interpolate',
                                      'scaling': 'pixel_normalization'},
                         'numerical': {   'fill_value': 0,
                                          'missing_value_strategy': 'fill_with_const',
                                          'normalization': None},
                         'sequence': {   'fill_value': '<UNK>',
                                         'lowercase': True,
                                         'missing_value_strategy': 'fill_with_const',
                                         'most_common': 20000,
                                         'padding': 'right',
                                         'padding_symbol': '<PAD>',
                                         'sequence_length_limit': 128,
                                         'tokenizer': 'space',
                                         'unknown_symbol': '<UNK>',
                                         'vocab_file': None},
                         'set': {   'fill_value': '<UNK>',
                                    'lowercase': False,
                                    'missing_value_strategy': 'fill_with_const',
                                    'most_common': 10000,
                                    'tokenizer': 'space'},
                         'split_probabilities': [0.8, 0.1, 0.1],
                         'stratify': 'category',
                         'text': {   'char_most_common': 70,
                                     'char_sequence_length_limit': 1024,
                                     'char_tokenizer': 'characters',
                                     'char_vocab_file': None,
                                     'fill_value': '<UNK>',
                                     'lowercase': True,
                                     'missing_value_strategy': 'fill_with_const',
                                     'padding': 'right',
                                     'padding_symbol': '<PAD>',
                                     'pretrained_model_name_or_path': None,
                                     'unknown_symbol': '<UNK>',
                                     'word_most_common': 20000,
                                     'word_sequence_length_limit': 128,
                                     'word_tokenizer': 'space_punct',
                                     'word_vocab_file': None},
                         'timeseries': {   'fill_value': '',
                                           'missing_value_strategy': 'fill_with_const',
                                           'padding': 'right',
                                           'padding_value': 0,
                                           'timeseries_length_limit': 256,
                                           'tokenizer': 'space'},
                         'vector': {   'fill_value': '',
                                       'missing_value_strategy': 'fill_with_const'}},
    'training': {   'batch_size': 64,
                    'bucketing_field': None,
                    'decay': True,
                    'decay_rate': 0.96,
                    'decay_steps': 10000,
                    'early_stop': 5,
                    'epochs': 10,
                    'eval_batch_size': None,
                    'gradient_clipping': None,
                    'increase_batch_size_on_plateau': 0,
                    'increase_batch_size_on_plateau_max': 512,
                    'increase_batch_size_on_plateau_patience': 5,
                    'increase_batch_size_on_plateau_rate': 2,
                    'learning_rate': 2e-05,
                    'learning_rate_warmup_epochs': 1,
                    'optimizer': {   'betas': (0.9, 0.999),
                                     'eps': 1e-08,
                                     'lr': 2e-05,
                                     'type': 'adam'},
                    'reduce_learning_rate_on_plateau': 0,
                    'reduce_learning_rate_on_plateau_patience': 5,
                    'reduce_learning_rate_on_plateau_rate': 0.5,
                    'regularization_lambda': 0,
                    'regularization_type': 'l2',
                    'staircase': False,
                    'trainable': True,
                    'validation_field': 'combined',
                    'validation_metric': 'loss'}}
torch_version: '1.10.1+cu102'
compute: {'gpu_type': 'Tesla T4', 'gpus_per_node': 1, 'num_nodes': 1}


Using training dataframe
Building dataset (it may take a while)
Downloading: 100%
181/181 [00:00<00:00, 8.81kB/s]
Downloading: 100%
572/572 [00:00<00:00, 23.1kB/s]
Downloading: 100%
593k/593k [00:00<00:00, 510kB/s]
Downloading: 100%
112/112 [00:00<00:00, 5.63kB/s]
Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.
Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.
Writing preprocessed training set cache
Writing preprocessed test set cache
Writing preprocessed validation set cache
Writing train set metadata
Training set: 121653
Validation set: 15432
Test set: 15041
Downloading: 100%
56.2M/56.2M [00:00<00:00, 61.6MB/s]
Some weights of the model checkpoint at monsoon-nlp/hindi-bert were not used when initializing ElectraModel: ['discriminator_predictions.dense_prediction.weight', 'discriminator_predictions.dense.weight', 'discriminator_predictions.dense_prediction.bias', 'discriminator_predictions.dense.bias']
- This IS expected if you are initializing ElectraModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing ElectraModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).

╒══════════╕
│ TRAINING │
╘══════════╛


Epoch  1
Training: 100%|███████████████████████████████████████████████████████████████████████████████████████████████| 1901/1901 [07:40<00:00,  4.13it/s]
Evaluation train:   0%|                                                                                                  | 0/1901 [00:00<?, ?it/s]training exception: issue is :Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
Evaluation train:   0%|                                                                                                  | 0/1901 [00:00<?, ?it/s]
