### ISSUE TITLE
Docker Image for ludwig uses pytorch as default and Pip installing ludwig package uses tensorflow as default. Is this the expected behavior

### ISSUE THREAD

**Issue by smiralr** [ludwig-ai/ludwig#1536]
**Describe the bug**
Docker Image for ludwig uses pytorch as default and Pip installing ludwig package uses tensorflow as default. Is this the expected behavior

**To Reproduce**
1. Pull and run ludwigai/ludwig:master , try running the examples notebook. Pytorch is default for backend
2. Pip install ludwig on google colab or local , try running the examples notebook tensorflow is default for backend

**Comment by tgaddair** [comment]
Hey @smiralr, yes this is expected, as we are in process of migrating from TensorFlow to PyTorch. The PyTorch migration has been landed to master, so the Docker images built off master also use PyTorch.

We do have other Docker images that map to released versions of Ludwig:

- `ludwigai/ludwig:latest` -> latest released version (v0.4)
- `ludwigai/ludwig:tf-legacy` -> release branch for v0.4.1, which will be the last version to support TensorFlow

Let me know if you have any additional questions.
