### ISSUE TITLE
AttributeError: module 'tensorflow.python.keras.layers.normalization' has no attribute 'BatchNormalizationBase'

### ISSUE THREAD

**Issue by aminaBm** [ludwig-ai/ludwig#1580]
I used to work with Ludwig and it works great I don't know what happened so I can't even import the package  
`from ludwig.api import LudwigModel`
it shows this error 
`AttributeError: module 'tensorflow.python.keras.layers.normalization' has no attribute 'BatchNormalizationBase'`

**Comment by tgaddair** [comment]
Hey @aminaBm, what versions of TensorFlow and Ludwig are you using? Can you also provide the full stack trace?

**Comment by aminaBm** [comment]
> 
@tgaddair 
sorry for the delay
`Version: 1.14.0`
I did pip upgrade and now it shows 

`module 'tensorflow.python.framework.ops' has no attribute 'RegisterShape'`

**Comment by w4nderlust** [comment]
@aminaBm this issue shoudl not be relevant anymore with the current 0.5rc2 release as it is based on PyTorch. Can you try to train the same model with the current version?
