### ISSUE TITLE
Training fails when using column names which conflict with PyTorch ModuleDict attributes e.x. 'to'

### ISSUE THREAD

**Issue by dantreiman** [ludwig-ai/ludwig#1653]
I'm training a Ludwig Model on an email dataset, which contains colums ['from', 'to', 'date', 'subject', etc...]

Training fails with error (python stack trace attached):
```
KeyError: 'An input feature has a name that conflicts with a class attribute of torch\'s ModuleDict: "attribute \'to\' already exists"'
```

It appears that the column 'to' is conflicting with a builtin attribute name. 

### Config
```
config = {
    'input_features': [
        {'name':'label', 'type':'category'},
        {'name':'from', 'type':'text'},
#        {'name':'to', 'type':'text'},  # With this line commented out, training works.
        {'name':'subject', 'type':'text'},
        {'name':'body', 'type':'text'},
        {'name':'x_mailer', 'type':'text'},
    ],
    'output_features': [
        {'name':'label', 'type':'category'}
    ],
}
```

### Stack Trace
[key_error_trace.txt](https://github.com/ludwig-ai/ludwig/files/7824178/key_error_trace.txt)

**Comment by dantreiman** [comment]
Just noticed @justinxzhao has a PR open for this: https://github.com/ludwig-ai/ludwig/pull/1651

**Comment by justinxzhao** [comment]
Thanks for filing an issue! I'm expecting the PR to be in a merge-ready state today or tomorrow.
