### ISSUE TITLE
Torch tests that depend on image and audio packages don't work on Apple M1 ARM64

### ISSUE THREAD

**Issue by justinxzhao** [ludwig-ai/ludwig#1671]
On Apple M1, basic ludwig functionality, most integration, and most unit tests seem to work with either @nickovs' [pip-based installation](https://github.com/ludwig-ai/ludwig/issues/1101#issuecomment-1009483450) or with @dantreiman's [conda-based installation](https://github.com/predibase/develop-env-tools).

However, images and audio packages are still broken.

> pytest tests/integration_tests/test_experiment.py::test_basic_image_feature

```RuntimeError: No such operator image::read_file ../mambaforge/envs/ludwig/lib/python3.8/site-packages/torch/_ops.py:63: RuntimeError```

> pytest tests/integration_tests/test_experiment.py::test_experiment_audio_inputs

```OSError: cannot load library '/Users/justinzhao/mambaforge/envs/ludwig/lib/python3.8/site-packages/_soundfile_data/libsndfile.dylib': dlopen(/Users/justinzhao/mambaforge/envs/ludwig/lib/python3.8/site-packages/_soundfile_data/libsndfile.dylib, 0x0002): tried: '/Users/justinzhao/mambaforge/envs/ludwig/lib/python3.8/site-packages/_soundfile_data/libsndfile.dylib' (no such file), '/usr/local/lib/libsndfile.dylib' (no such file), '/usr/lib/libsndfile.dylib' (no such file)```

@dantreiman reports that the audio packages issues can be mitigated by running

> brew install libsndfile

and then manually copying the installed library files into my python environment’s lib directory, i.e.

> cp /opt/homebrew/Cellar/libsndfile/1.0.31/lib/* <path_to_python_env>/lib/

The image problem remains to be fixed, though we suspect it is caused by a version mismatch with `libjpeg`.

**Comment by nickovs** [comment]
@justinxzhao Thanks for running these tests. Regarding the libsndfile issue, did you do the `brew install libsndfile` before or after installing the `requirements_audio.txt` dependencies? I suspect that if you (a) install the library before installing the dependencies and (b) ensure that the _setup_ for the Python module that is going to use it knows where to find it, then you won't need to do that file copy manually.
