### ISSUE TITLE
ieee_fraud automl type selection on master fails in preprocessing

### ISSUE THREAD

**Issue by amholler** [ludwig-ai/ludwig#1679]
Problem can be reproduced by running:
https://github.com/ludwig-ai/experiments/blob/main/automl/heuristics/ieee_fraud/run_auto_train_1hr.py

which produces this stack trace:
```
Traceback (most recent call last):
  File "run_auto_train_1hr.py", line 13, in <module>
    tune_for_memory=False
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ludwig/automl/automl.py", line 103, in auto_train
    return train_with_config(dataset, config, output_directory=output_directory, random_seed=random_seed, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ludwig/automl/automl.py", line 172, in train_with_config
    config, dataset, output_directory=output_directory, model_name=model_name, random_seed=random_seed, **kwargs
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ludwig/automl/automl.py", line 262, in _train
    **kwargs,
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ludwig/hyperopt/run.py", line 292, in hyperopt
    random_seed=random_seed,
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ludwig/api.py", line 1279, in preprocess
    callbacks=self.callbacks,
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ludwig/data/preprocessing.py", line 1403, in preprocess_for_training
    callbacks=callbacks,
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ludwig/data/preprocessing.py", line 231, in preprocess_for_training
    callbacks=callbacks,
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ludwig/data/preprocessing.py", line 1559, in _preprocess_df_for_training
    mode="training",
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ludwig/data/preprocessing.py", line 1054, in build_dataset
    metadata = build_metadata(metadata, dataset_cols, feature_configs, global_preprocessing_parameters, backend)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ludwig/data/preprocessing.py", line 1159, in build_metadata
    column, preprocessing_parameters, backend
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ludwig/features/binary_feature.py", line 101, in get_feature_meta
    f"Binary feature column {column.name} expects 2 distinct values, "
ValueError: Binary feature column M1 expects 2 distinct values, found: ['T', '0', 'F']
```

**Comment by amholler** [comment]
Note that this problem does not occur on tf-legacy, where AutoML infers the column M1 as category.

BTW, only minor differences in AutoML type inference between tf-legacy and master are observed for other datasets,
but for this dataset, there are a large number of differences, listed below.  It would be good to understand the reasons
for this; the tf-legacy AutoML type inference code was tuned to produce types consistent with experts for each dataset.

(base) ray@ip-172-31-30-163:~/experiments/automl/heuristics/ieee_fraud$ diff auto_config.json.automl auto_config.json.automl.master 
105c106
<                      'type': 'category'},
---
>                      'type': 'text'},
108c109
<                      'type': 'category'},
---
>                      'type': 'text'},
138,140c139,141
<                     {'column': 'M1', 'name': 'M1', 'type': 'category'},
<                     {'column': 'M2', 'name': 'M2', 'type': 'category'},
<                     {'column': 'M3', 'name': 'M3', 'type': 'category'},
---
>                     {'column': 'M1', 'name': 'M1', 'type': 'binary'},
>                     {'column': 'M2', 'name': 'M2', 'type': 'binary'},
>                     {'column': 'M3', 'name': 'M3', 'type': 'binary'},
142,161c143,162
<                     {'column': 'M5', 'name': 'M5', 'type': 'category'},
<                     {'column': 'M6', 'name': 'M6', 'type': 'category'},
<                     {'column': 'M7', 'name': 'M7', 'type': 'category'},
<                     {'column': 'M8', 'name': 'M8', 'type': 'category'},
<                     {'column': 'M9', 'name': 'M9', 'type': 'category'},
<                     {'column': 'V1', 'name': 'V1', 'type': 'numerical'},
<                     {'column': 'V2', 'name': 'V2', 'type': 'numerical'},
<                     {'column': 'V3', 'name': 'V3', 'type': 'numerical'},
<                     {'column': 'V4', 'name': 'V4', 'type': 'numerical'},
<                     {'column': 'V5', 'name': 'V5', 'type': 'numerical'},
<                     {'column': 'V6', 'name': 'V6', 'type': 'numerical'},
<                     {'column': 'V7', 'name': 'V7', 'type': 'numerical'},
<                     {'column': 'V8', 'name': 'V8', 'type': 'numerical'},
<                     {'column': 'V9', 'name': 'V9', 'type': 'numerical'},
<                     {'column': 'V10', 'name': 'V10', 'type': 'numerical'},
<                     {'column': 'V11', 'name': 'V11', 'type': 'numerical'},
<                     {'column': 'V12', 'name': 'V12', 'type': 'numerical'},
<                     {'column': 'V13', 'name': 'V13', 'type': 'numerical'},
<                     {'column': 'V14', 'name': 'V14', 'type': 'numerical'},
<                     {'column': 'V15', 'name': 'V15', 'type': 'numerical'},
---
>                     {'column': 'M5', 'name': 'M5', 'type': 'binary'},
>                     {'column': 'M6', 'name': 'M6', 'type': 'binary'},
>                     {'column': 'M7', 'name': 'M7', 'type': 'binary'},
>                     {'column': 'M8', 'name': 'M8', 'type': 'binary'},
>                     {'column': 'M9', 'name': 'M9', 'type': 'binary'},
>                     {'column': 'V1', 'name': 'V1', 'type': 'binary'},
>                     {'column': 'V2', 'name': 'V2', 'type': 'category'},
>                     {'column': 'V3', 'name': 'V3', 'type': 'category'},
>                     {'column': 'V4', 'name': 'V4', 'type': 'category'},
>                     {'column': 'V5', 'name': 'V5', 'type': 'category'},
>                     {'column': 'V6', 'name': 'V6', 'type': 'category'},
>                     {'column': 'V7', 'name': 'V7', 'type': 'category'},
>                     {'column': 'V8', 'name': 'V8', 'type': 'category'},
>                     {'column': 'V9', 'name': 'V9', 'type': 'category'},
>                     {'column': 'V10', 'name': 'V10', 'type': 'category'},
>                     {'column': 'V11', 'name': 'V11', 'type': 'category'},
>                     {'column': 'V12', 'name': 'V12', 'type': 'category'},
>                     {'column': 'V13', 'name': 'V13', 'type': 'category'},
>                     {'column': 'V14', 'name': 'V14', 'type': 'binary'},
>                     {'column': 'V15', 'name': 'V15', 'type': 'category'},
163,165c164,166
<                     {'column': 'V17', 'name': 'V17', 'type': 'numerical'},
<                     {'column': 'V18', 'name': 'V18', 'type': 'numerical'},
<                     {'column': 'V19', 'name': 'V19', 'type': 'numerical'},
---
>                     {'column': 'V17', 'name': 'V17', 'type': 'category'},
>                     {'column': 'V18', 'name': 'V18', 'type': 'category'},
>                     {'column': 'V19', 'name': 'V19', 'type': 'category'},
167,170c168,171
<                     {'column': 'V21', 'name': 'V21', 'type': 'numerical'},
<                     {'column': 'V22', 'name': 'V22', 'type': 'numerical'},
<                     {'column': 'V23', 'name': 'V23', 'type': 'numerical'},
<                     {'column': 'V24', 'name': 'V24', 'type': 'numerical'},
---
>                     {'column': 'V21', 'name': 'V21', 'type': 'category'},
>                     {'column': 'V22', 'name': 'V22', 'type': 'category'},
>                     {'column': 'V23', 'name': 'V23', 'type': 'category'},
>                     {'column': 'V24', 'name': 'V24', 'type': 'category'},
175c176
<                     {'column': 'V29', 'name': 'V29', 'type': 'numerical'},
---
>                     {'column': 'V29', 'name': 'V29', 'type': 'category'},
177c178
<                     {'column': 'V31', 'name': 'V31', 'type': 'numerical'},
---
>                     {'column': 'V31', 'name': 'V31', 'type': 'category'},
181,182c182,183
<                     {'column': 'V35', 'name': 'V35', 'type': 'numerical'},
<                     {'column': 'V36', 'name': 'V36', 'type': 'numerical'},
---
>                     {'column': 'V35', 'name': 'V35', 'type': 'category'},
>                     {'column': 'V36', 'name': 'V36', 'type': 'category'},
185c186
<                     {'column': 'V39', 'name': 'V39', 'type': 'numerical'},
---
>                     {'column': 'V39', 'name': 'V39', 'type': 'category'},
187,189c188,190
<                     {'column': 'V41', 'name': 'V41', 'type': 'numerical'},
<                     {'column': 'V42', 'name': 'V42', 'type': 'numerical'},
<                     {'column': 'V43', 'name': 'V43', 'type': 'numerical'},
---
>                     {'column': 'V41', 'name': 'V41', 'type': 'binary'},
>                     {'column': 'V42', 'name': 'V42', 'type': 'category'},
>                     {'column': 'V43', 'name': 'V43', 'type': 'category'},
192c193
<                     {'column': 'V46', 'name': 'V46', 'type': 'numerical'},
---
>                     {'column': 'V46', 'name': 'V46', 'type': 'category'},
194,197c195,198
<                     {'column': 'V48', 'name': 'V48', 'type': 'numerical'},
<                     {'column': 'V49', 'name': 'V49', 'type': 'numerical'},
<                     {'column': 'V50', 'name': 'V50', 'type': 'numerical'},
<                     {'column': 'V51', 'name': 'V51', 'type': 'numerical'},
---
>                     {'column': 'V48', 'name': 'V48', 'type': 'category'},
>                     {'column': 'V49', 'name': 'V49', 'type': 'category'},
>                     {'column': 'V50', 'name': 'V50', 'type': 'category'},
>                     {'column': 'V51', 'name': 'V51', 'type': 'category'},
199,201c200,202
<                     {'column': 'V53', 'name': 'V53', 'type': 'numerical'},
<                     {'column': 'V54', 'name': 'V54', 'type': 'numerical'},
<                     {'column': 'V55', 'name': 'V55', 'type': 'numerical'},
---
>                     {'column': 'V53', 'name': 'V53', 'type': 'category'},
>                     {'column': 'V54', 'name': 'V54', 'type': 'category'},
>                     {'column': 'V55', 'name': 'V55', 'type': 'category'},
203,222c204,223
<                     {'column': 'V57', 'name': 'V57', 'type': 'numerical'},
<                     {'column': 'V58', 'name': 'V58', 'type': 'numerical'},
<                     {'column': 'V59', 'name': 'V59', 'type': 'numerical'},
<                     {'column': 'V60', 'name': 'V60', 'type': 'numerical'},
<                     {'column': 'V61', 'name': 'V61', 'type': 'numerical'},
<                     {'column': 'V62', 'name': 'V62', 'type': 'numerical'},
<                     {'column': 'V63', 'name': 'V63', 'type': 'numerical'},
<                     {'column': 'V64', 'name': 'V64', 'type': 'numerical'},
<                     {'column': 'V65', 'name': 'V65', 'type': 'numerical'},
<                     {'column': 'V66', 'name': 'V66', 'type': 'numerical'},
<                     {'column': 'V67', 'name': 'V67', 'type': 'numerical'},
<                     {'column': 'V68', 'name': 'V68', 'type': 'numerical'},
<                     {'column': 'V69', 'name': 'V69', 'type': 'numerical'},
<                     {'column': 'V70', 'name': 'V70', 'type': 'numerical'},
<                     {'column': 'V71', 'name': 'V71', 'type': 'numerical'},
<                     {'column': 'V72', 'name': 'V72', 'type': 'numerical'},
<                     {'column': 'V73', 'name': 'V73', 'type': 'numerical'},
<                     {'column': 'V74', 'name': 'V74', 'type': 'numerical'},
<                     {'column': 'V75', 'name': 'V75', 'type': 'numerical'},
<                     {'column': 'V76', 'name': 'V76', 'type': 'numerical'},
---
>                     {'column': 'V57', 'name': 'V57', 'type': 'category'},
>                     {'column': 'V58', 'name': 'V58', 'type': 'category'},
>                     {'column': 'V59', 'name': 'V59', 'type': 'category'},
>                     {'column': 'V60', 'name': 'V60', 'type': 'category'},
>                     {'column': 'V61', 'name': 'V61', 'type': 'category'},
>                     {'column': 'V62', 'name': 'V62', 'type': 'category'},
>                     {'column': 'V63', 'name': 'V63', 'type': 'category'},
>                     {'column': 'V64', 'name': 'V64', 'type': 'category'},
>                     {'column': 'V65', 'name': 'V65', 'type': 'binary'},
>                     {'column': 'V66', 'name': 'V66', 'type': 'category'},
>                     {'column': 'V67', 'name': 'V67', 'type': 'category'},
>                     {'column': 'V68', 'name': 'V68', 'type': 'category'},
>                     {'column': 'V69', 'name': 'V69', 'type': 'category'},
>                     {'column': 'V70', 'name': 'V70', 'type': 'category'},
>                     {'column': 'V71', 'name': 'V71', 'type': 'category'},
>                     {'column': 'V72', 'name': 'V72', 'type': 'category'},
>                     {'column': 'V73', 'name': 'V73', 'type': 'category'},
>                     {'column': 'V74', 'name': 'V74', 'type': 'category'},
>                     {'column': 'V75', 'name': 'V75', 'type': 'category'},
>                     {'column': 'V76', 'name': 'V76', 'type': 'category'},
225c226
<                     {'column': 'V79', 'name': 'V79', 'type': 'numerical'},
---
>                     {'column': 'V79', 'name': 'V79', 'type': 'category'},
228,231c229,232
<                     {'column': 'V82', 'name': 'V82', 'type': 'numerical'},
<                     {'column': 'V83', 'name': 'V83', 'type': 'numerical'},
<                     {'column': 'V84', 'name': 'V84', 'type': 'numerical'},
<                     {'column': 'V85', 'name': 'V85', 'type': 'numerical'},
---
>                     {'column': 'V82', 'name': 'V82', 'type': 'category'},
>                     {'column': 'V83', 'name': 'V83', 'type': 'category'},
>                     {'column': 'V84', 'name': 'V84', 'type': 'category'},
>                     {'column': 'V85', 'name': 'V85', 'type': 'category'},
234,240c235,241
<                     {'column': 'V88', 'name': 'V88', 'type': 'numerical'},
<                     {'column': 'V89', 'name': 'V89', 'type': 'numerical'},
<                     {'column': 'V90', 'name': 'V90', 'type': 'numerical'},
<                     {'column': 'V91', 'name': 'V91', 'type': 'numerical'},
<                     {'column': 'V92', 'name': 'V92', 'type': 'numerical'},
<                     {'column': 'V93', 'name': 'V93', 'type': 'numerical'},
<                     {'column': 'V94', 'name': 'V94', 'type': 'numerical'},
---
>                     {'column': 'V88', 'name': 'V88', 'type': 'binary'},
>                     {'column': 'V89', 'name': 'V89', 'type': 'category'},
>                     {'column': 'V90', 'name': 'V90', 'type': 'category'},
>                     {'column': 'V91', 'name': 'V91', 'type': 'category'},
>                     {'column': 'V92', 'name': 'V92', 'type': 'category'},
>                     {'column': 'V93', 'name': 'V93', 'type': 'category'},
>                     {'column': 'V94', 'name': 'V94', 'type': 'category'},
244c245
<                     {'column': 'V98', 'name': 'V98', 'type': 'numerical'},
---
>                     {'column': 'V98', 'name': 'V98', 'type': 'category'},
250c251
<                     {'column': 'V104', 'name': 'V104', 'type': 'numerical'},
---
>                     {'column': 'V104', 'name': 'V104', 'type': 'category'},
253,271c254,272
<                     {'column': 'V107', 'name': 'V107', 'type': 'numerical'},
<                     {'column': 'V108', 'name': 'V108', 'type': 'numerical'},
<                     {'column': 'V109', 'name': 'V109', 'type': 'numerical'},
<                     {'column': 'V110', 'name': 'V110', 'type': 'numerical'},
<                     {'column': 'V111', 'name': 'V111', 'type': 'numerical'},
<                     {'column': 'V112', 'name': 'V112', 'type': 'numerical'},
<                     {'column': 'V113', 'name': 'V113', 'type': 'numerical'},
<                     {'column': 'V114', 'name': 'V114', 'type': 'numerical'},
<                     {'column': 'V115', 'name': 'V115', 'type': 'numerical'},
<                     {'column': 'V116', 'name': 'V116', 'type': 'numerical'},
<                     {'column': 'V117', 'name': 'V117', 'type': 'numerical'},
<                     {'column': 'V118', 'name': 'V118', 'type': 'numerical'},
<                     {'column': 'V119', 'name': 'V119', 'type': 'numerical'},
<                     {'column': 'V120', 'name': 'V120', 'type': 'numerical'},
<                     {'column': 'V121', 'name': 'V121', 'type': 'numerical'},
<                     {'column': 'V122', 'name': 'V122', 'type': 'numerical'},
<                     {'column': 'V123', 'name': 'V123', 'type': 'numerical'},
<                     {'column': 'V124', 'name': 'V124', 'type': 'numerical'},
<                     {'column': 'V125', 'name': 'V125', 'type': 'numerical'},
---
>                     {'column': 'V107', 'name': 'V107', 'type': 'binary'},
>                     {'column': 'V108', 'name': 'V108', 'type': 'category'},
>                     {'column': 'V109', 'name': 'V109', 'type': 'category'},
>                     {'column': 'V110', 'name': 'V110', 'type': 'category'},
>                     {'column': 'V111', 'name': 'V111', 'type': 'category'},
>                     {'column': 'V112', 'name': 'V112', 'type': 'category'},
>                     {'column': 'V113', 'name': 'V113', 'type': 'category'},
>                     {'column': 'V114', 'name': 'V114', 'type': 'category'},
>                     {'column': 'V115', 'name': 'V115', 'type': 'category'},
>                     {'column': 'V116', 'name': 'V116', 'type': 'category'},
>                     {'column': 'V117', 'name': 'V117', 'type': 'category'},
>                     {'column': 'V118', 'name': 'V118', 'type': 'category'},
>                     {'column': 'V119', 'name': 'V119', 'type': 'category'},
>                     {'column': 'V120', 'name': 'V120', 'type': 'category'},
>                     {'column': 'V121', 'name': 'V121', 'type': 'category'},
>                     {'column': 'V122', 'name': 'V122', 'type': 'category'},
>                     {'column': 'V123', 'name': 'V123', 'type': 'category'},
>                     {'column': 'V124', 'name': 'V124', 'type': 'category'},
>                     {'column': 'V125', 'name': 'V125', 'type': 'category'},
287,288c288,289
<                     {'column': 'V141', 'name': 'V141', 'type': 'numerical'},
<                     {'column': 'V142', 'name': 'V142', 'type': 'numerical'},
---
>                     {'column': 'V141', 'name': 'V141', 'type': 'category'},
>                     {'column': 'V142', 'name': 'V142', 'type': 'category'},
299,300c300,301
<                     {'column': 'V153', 'name': 'V153', 'type': 'numerical'},
<                     {'column': 'V154', 'name': 'V154', 'type': 'numerical'},
---
>                     {'column': 'V153', 'name': 'V153', 'type': 'category'},
>                     {'column': 'V154', 'name': 'V154', 'type': 'category'},
319,321c320,322
<                     {'column': 'V173', 'name': 'V173', 'type': 'numerical'},
<                     {'column': 'V174', 'name': 'V174', 'type': 'numerical'},
<                     {'column': 'V175', 'name': 'V175', 'type': 'numerical'},
---
>                     {'column': 'V173', 'name': 'V173', 'type': 'category'},
>                     {'column': 'V174', 'name': 'V174', 'type': 'category'},
>                     {'column': 'V175', 'name': 'V175', 'type': 'category'},
330c331
<                     {'column': 'V184', 'name': 'V184', 'type': 'numerical'},
---
>                     {'column': 'V184', 'name': 'V184', 'type': 'category'},
340,341c341,342
<                     {'column': 'V194', 'name': 'V194', 'type': 'numerical'},
<                     {'column': 'V195', 'name': 'V195', 'type': 'numerical'},
---
>                     {'column': 'V194', 'name': 'V194', 'type': 'category'},
>                     {'column': 'V195', 'name': 'V195', 'type': 'category'},
343c344
<                     {'column': 'V197', 'name': 'V197', 'type': 'numerical'},
---
>                     {'column': 'V197', 'name': 'V197', 'type': 'category'},
369c370
<                     {'column': 'V223', 'name': 'V223', 'type': 'numerical'},
---
>                     {'column': 'V223', 'name': 'V223', 'type': 'category'},
393c394
<                     {'column': 'V247', 'name': 'V247', 'type': 'numerical'},
---
>                     {'column': 'V247', 'name': 'V247', 'type': 'category'},
396,397c397,398
<                     {'column': 'V250', 'name': 'V250', 'type': 'numerical'},
<                     {'column': 'V251', 'name': 'V251', 'type': 'numerical'},
---
>                     {'column': 'V250', 'name': 'V250', 'type': 'category'},
>                     {'column': 'V251', 'name': 'V251', 'type': 'category'},
406c407
<                     {'column': 'V260', 'name': 'V260', 'type': 'numerical'},
---
>                     {'column': 'V260', 'name': 'V260', 'type': 'category'},
430c431
<                     {'column': 'V284', 'name': 'V284', 'type': 'numerical'},
---
>                     {'column': 'V284', 'name': 'V284', 'type': 'category'},
432c433
<                     {'column': 'V286', 'name': 'V286', 'type': 'numerical'},
---
>                     {'column': 'V286', 'name': 'V286', 'type': 'category'},
434,435c435,436
<                     {'column': 'V288', 'name': 'V288', 'type': 'numerical'},
<                     {'column': 'V289', 'name': 'V289', 'type': 'numerical'},
---
>                     {'column': 'V288', 'name': 'V288', 'type': 'category'},
>                     {'column': 'V289', 'name': 'V289', 'type': 'category'},
443c444
<                     {'column': 'V297', 'name': 'V297', 'type': 'numerical'},
---
>                     {'column': 'V297', 'name': 'V297', 'type': 'category'},
446,448c447,449
<                     {'column': 'V300', 'name': 'V300', 'type': 'numerical'},
<                     {'column': 'V301', 'name': 'V301', 'type': 'numerical'},
<                     {'column': 'V302', 'name': 'V302', 'type': 'numerical'},
---
>                     {'column': 'V300', 'name': 'V300', 'type': 'category'},
>                     {'column': 'V301', 'name': 'V301', 'type': 'category'},
>                     {'column': 'V302', 'name': 'V302', 'type': 'category'},
450,451c451,452
<                     {'column': 'V304', 'name': 'V304', 'type': 'numerical'},
<                     {'column': 'V305', 'name': 'V305', 'type': 'numerical'},
---
>                     {'column': 'V304', 'name': 'V304', 'type': 'category'},
>                     {'column': 'V305', 'name': 'V305', 'type': 'category'},
471c472
<                     {'column': 'V325', 'name': 'V325', 'type': 'numerical'},
---
>                     {'column': 'V325', 'name': 'V325', 'type': 'category'},
473,474c474,475
<                     {'column': 'V327', 'name': 'V327', 'type': 'numerical'},
<                     {'column': 'V328', 'name': 'V328', 'type': 'numerical'},
---
>                     {'column': 'V327', 'name': 'V327', 'type': 'category'},
>                     {'column': 'V328', 'name': 'V328', 'type': 'category'},
515c516
<                     {'column': 'id_30', 'name': 'id_30', 'type': 'category'},
---
>                     {'column': 'id_30', 'name': 'id_30', 'type': 'text'},
518c519
<                     {'column': 'id_33', 'name': 'id_33', 'type': 'category'},
---
>                     {'column': 'id_33', 'name': 'id_33', 'type': 'text'},
520,523c521,524
<                     {'column': 'id_35', 'name': 'id_35', 'type': 'category'},
<                     {'column': 'id_36', 'name': 'id_36', 'type': 'category'},
<                     {'column': 'id_37', 'name': 'id_37', 'type': 'category'},
<                     {'column': 'id_38', 'name': 'id_38', 'type': 'category'},
---
>                     {'column': 'id_35', 'name': 'id_35', 'type': 'binary'},
>                     {'column': 'id_36', 'name': 'id_36', 'type': 'binary'},
>                     {'column': 'id_37', 'name': 'id_37', 'type': 'binary'},
>                     {'column': 'id_38', 'name': 'id_38', 'type': 'binary'},
529c530
<                      'type': 'category'}],
---
>                      'type': 'text'}],

**Comment by tgaddair** [comment]
We've definitely run into issues like this before with binary cols. In this case, the column is binary, but the missing values are being coerced incorrectly (they should be coerced to `F`, not `0`).

@w4nderlust @justinxzhao
