### ISSUE TITLE
Specify the cache_dir for huggingface transformer models

### ISSUE THREAD

**Issue by danielduckworth** [ludwig-ai/ludwig#1680]
**Is your feature request related to a problem? Please describe.**
I've been experimenting with various huggingface models. On Windows, the default cache directory for the models is on C:\ drive. It quickly runs out of storage for me.

**Describe the solution you'd like**
A CLI or yaml config parameter to specify a new cache directory for the downloaded models. Cache_dir is an optional parameter for 
[.Pretrained](https://huggingface.co/docs/transformers/master/en/main_classes/configuration#transformers.PretrainedConfig.from_pretrained.cache_dir).

**Describe alternatives you've considered**
I can set an [environment variable as discussed here](https://stackoverflow.com/questions/63312859/how-to-change-huggingface-transformers-default-cache-directory).

**Comment by tgaddair** [comment]
Hey @danielduckworth, thanks for raising this issue. This should be relatively straightforward to implement. Something like:

```
input_features:
    name: sentence
    type: text
    encoder:
        type: bert
        cache_dir: ...
```

**Comment by justinxzhao** [comment]
+1. Seems like the right place to put the `cache_dir` parameter.

Couple more pointers for how to add this to Ludwig:
- Add `cache_dir` as a param to the text encoder constructor, i.e. https://github.com/ludwig-ai/ludwig/blob/master/ludwig/encoders/text_encoders.py#L41
- Change the instantiation of the huggingface model to use `cache_dir`: https://github.com/ludwig-ai/ludwig/blob/master/ludwig/encoders/text_encoders.py#L82

**Comment by tgaddair** [comment]
Another option we can consider to make this very general is have a Dict param called `pretrained_kwargs` that can then be passed opaquely to the `from_pretrained` call. This would then allow us to support all the kwargs. So:

```
encoder:
    type: bert
    use_pretrained: true
    pretrained_kwargs:
        cache_dir: ...
```

The code then becomes:

```
if use_pretrained:
            pretrained_kwargs = pretrained_kwargs or {}
            self.transformer = BertModel.from_pretrained(pretrained_model_name_or_path, **pretrained_kwargs)
```
