### ISSUE TITLE
It would be nice if ludwig serve populated the FastAPI automatic docs with sample paramters

### ISSUE THREAD

**Issue by danielduckworth** [ludwig-ai/ludwig#1681]
**Is your feature request related to a problem? Please describe.**
When looking at the automatic docs generated by FastAPI on the Ludwig serve API, no parameters are included so the 'Try it out' function doesn't work. This would be useful for public facing models served as an API.

**Describe the use case**
Automatic interactive API docs for Ludwig serve so developers can use the API.

https://fastapi.tiangolo.com/#interactive-api-docs

**Describe the solution you'd like**
In the Ludwig serve module, add some parameters based on the model description so the automatic docs work.

**Describe alternatives you've considered**
Manually writing API docs.

**Additional context**
Maybe this is a bug?
Looking the serve.py, root should return JSONResponse({"message": "Ludwig server is up"}). However I get 'Internal Server Error'.
I could have a go at developing this.

**Comment by danielduckworth** [comment]
I saw in the stack trace, "AttributeError: module 'anyio' has no attribute 'to_thread'" when trying to access root.

I forgot to mention, /predict using POST works as expected.

**Comment by tgaddair** [comment]
Good suggestion, @danielduckworth, this should be a simple matter of adding the Pydantic model to the endpoints in serve.py.

**Comment by danielduckworth** [comment]
I did a fresh install of ludwig and tensorflow, re-trained the model and ran the ludwig serve tool again. The internal server error is gone and it's working as expected now. The request response time also decreased by 50% which is nice.

**Comment by tgaddair** [comment]
Glad to hear the issue went away on its own after resetting the environment. Definitely we'll want to improve the documentation here to hopefully prevent issues like this in the future.

**Comment by danielduckworth** [comment]
I also noticed that I had to manually install petastorm to get the serve tool working. Perhaps it needs to be included in the requirements for the serve module?

**Comment by tgaddair** [comment]
This was actually a bug that will be fixed in v0.4.1 (released next week). Petastorm isn't strictly needed, but it was being imported as part of the serve code path by mistake.

**Comment by dalianaliu** [comment]
Hi @danielduckworth, has it been fixed with the Ludwig update?
