### ISSUE TITLE
Error when trying to Join predict results with DataFrame

### ISSUE THREAD

**Issue by MarijnQ** [ludwig-ai/ludwig#1767]
**Describe the bug**
On command
`dft.join(predictions)`
I get 
AttributeError: 'builtin_function_or_method' object has no attribute 'is_unique'

**A copy of my code:**
**INSTALLS**
```
!pip install tensorflow-gpu
!pip install ludwig
import pandas as pd
from datetime import datetime as dt
import numpy as np
from google.colab import drive
from google.colab import files
drive.mount('drive')
from google.colab import files
```

**UPLOADS**
```
uploaded = files.upload()
for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))
df = pd.read_csv("Question_Classification_Dataset.csv", index_col=0)

from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

dft = pd.read_csv("Question Report Signable 2022_Page 1_Table.csv")

model_definition="""
input_features:
    -
        name: Questions
        type: text
        level: word
        encoder: parallel_cnn
output_features:
    -
        name: Category0
        type: category
"""
with open("model_definition.yaml", "w") as f:
  f.write(model_definition)
```

START EXPERIMENT
```
!ludwig experiment \
 --dataset Question_Classification_Dataset.csv\
 --config_file model_definition.yaml
```

**START PREDICT**
```
from ludwig.api import LudwigModel
model = LudwigModel.load("results/experiment_run_3/model")
predictions = model.predict(dft.rename(columns={'Query': 'Questions'} ))
```

**ERROR HAPPENS**
```
dft.join(predictions)
AttributeError: 'builtin_function_or_method' object has no attribute 'is_unique'
```

What I want to happen
I would like to add the results of predictions to the data frame I did the testing on so I can see what the results are.
As far as I can see, I get a tuple as result which has all the answers in a single cell and not in a data frame model.

**Environment (please complete the following information):**

- OS: MAC, Chrome, Google Colab
- Python version 3.7
- Ludwig version 2.1.3

Sorry if this explanation was too excessive, I've been looking at this for three days now and I cant figure it out.

**Comment by w4nderlust** [comment]
@MarijnQ can you please provide an example of the contents of both dft and predictions? The issue may be related with the lack of unique index.

**Comment by MarijnQ** [comment]
> 

Hiya, Sure I can.
dft is a csv with 3 columns called "Query"(text) "URL Clicks"(int) and "Impressions"(int)
predictions is defined as a tuple value when I research it in python. but it seems like all the data is locked up in 1 cell and I cant extract it.

**Comment by w4nderlust** [comment]
Can you post here the prints of those two dataframes? (the first few lines)
If there's sensible data, you redact it. It's just for understanding better the contents of both of them.

**Comment by MarijnQ** [comment]
> 

Aha, yes sure.
so dft is like this
Query,Url Clicks,Impressions
what is a wet signature,320,41835
signing for someone else with permission uk,118,1026
is an electronic signature legal uk,87,735
what should your signature be,77,1153

and predictions is:
(      Category0_predictions  ... Category0_probabilities_ABBREVIATION
 0               DESCRIPTION  ...                             0.011631
 1               DESCRIPTION  ...                             0.021409
 2                    ENTITY  ...                             0.125703
 3                    ENTITY  ...                             0.119312
 4                    ENTITY  ...                             0.068843
 ...                     ...  ...                                  ...
 11196           DESCRIPTION  ...                             0.011269
 11197                 HUMAN  ...                             0.034313
 11198           DESCRIPTION  ...                             0.019942
 11199                ENTITY  ...                             0.119312
 11200                ENTITY  ...                             0.005736
 
 [11201 rows x 10 columns], 'results')

**Comment by w4nderlust** [comment]
@MarijnQ And both DFs have the same number of rows, and what you are trying to obtain is a signle df with the the union of the columns of both right?
In that case, I believe you may want to cancatenate them
```
pd.concat([dft, predictions.reindex(dft.index)], axis=1)
```
as explained here: https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html (cell 12)

**Comment by MarijnQ** [comment]
@w4nderlust Thanks for the quick response. I just ran the code again and got the following error
```AttributeError: 'tuple' object has no attribute 'reindex'```

When I take a look at the predictions file, I get the 10 columns and the 11k rows. however, all the info seemed to be clustered in cell A1 and the rest is empty. Would this be the issue?

**Comment by w4nderlust** [comment]
@MarijnQ I'm not sure i understand what you mean by "When I take a look at the predictions file, I get the 10 columns and the 11k rows. however, all the info seemed to be clustered in cell A1 and the rest is empty"

Can you actually paste the contents of predictions (first 6 rows) in a code block here?

**Comment by MarijnQ** [comment]
@w4nderlust the dataset is in a different format now compared to when I did it first. However, the merge still doesn't want to work.


Category0_predictions | Category0_probabilities | Category2_predictions | Category2_probabilities | Category0_probability | Category0_probabilities_<UNK> | Category0_probabilities_ENTITY | Category0_probabilities_HUMAN | Category0_probabilities_DESCRIPTION | Category0_probabilities_NUMERIC | ... | Category2_probabilities_symbol | Category2_probabilities_weight | Category2_probabilities_instru | Category2_probabilities_letter | Category2_probabilities_speed | Category2_probabilities_code | Category2_probabilities_temp | Category2_probabilities_ord | Category2_probabilities_religion | Category2_probabilities_currency
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
ENTITY | [2.952353986285239e-11, 0.9831990599632263, 0.... | cremat | [2.1355752236051906e-11, 0.08688811957836151, ... | 0.983199 | 2.952354e-11 | 9.831991e-01 | 1.679150e-02 | 1.227618e-06 | 3.550630e-08 | ... | 4.569295e-06 | 8.756627e-09 | 5.103667e-04 | 1.792344e-05 | 2.937561e-08 | 4.563263e-06 | 1.992187e-06 | 2.264519e-07 | 2.993290e-05 | 3.996156e-05
LOCATION | [1.1421776662245975e-06, 0.013896584510803223,... | other | [8.044471755397353e-09, 0.00019625862478278577... | 0.897827 | 1.142178e-06 | 1.389658e-02 | 4.262314e-04 | 8.442399e-02 | 6.225748e-04 | ... | 1.831643e-04 | 1.072783e-06 | 7.179040e-04 | 9.659077e-05 | 4.157167e-05 | 7.290675e-04 | 2.445421e-04 | 1.735126e-05 | 1.085888e-03 | 2.010195e-04
DESCRIPTION | [2.432461076013249e-17, 1.1186459536460802e-09... | reason | [3.9185060229574945e-21, 1.416687405407513e-13... | 1.000000 | 2.432461e-17 | 1.118646e-09 | 2.022765e-12 | 1.000000e+00 | 7.333033e-12 | ... | 8.520395e-14 | 2.387633e-15 | 1.729473e-09 | 4.165319e-14 | 1.321149e-11 | 1.168125e-11 | 9.920127e-11 | 3.400962e-15 | 2.749342e-13 | 1.038334e-10
HUMAN | [5.569419928632422e-15, 1.8011108977589174e-06... | ind | [7.062399777946378e-16, 0.9958555102348328, 9.... | 0.999998 | 5.569420e-15 | 1.801111e-06 | 9.999982e-01 | 1.069619e-08 | 1.352811e-08 | ... | 1.611124e-11 | 3.731057e-11 | 1.820006e-06 | 3.665723e-08 | 2.459580e-12 | 3.165923e-10 | 1.742926e-09 | 1.592500e-10 | 5.449889e-09 | 6.204095e-08
HUMAN | [1.574987563328703e-13, 0.0041975295171141624,... | gr | [2.902269624713988e-13, 0.015315561555325985, ... | 0.995790 | 1.574988e-13 | 4.197530e-03 | 9.957897e-01 | 5.112311e-10 | 1.285818e-05 | ... | 6.827471e-09 | 4.435966e-08 | 1.238697e-05 | 1.358520e-06 | 2.194725e-10 | 2.462821e-08 | 8.201413e-08 | 8.046493e-09 | 3.293777e-08 | 1.190593e-06

**Comment by connor-mccorm** [comment]
> @w4nderlust Thanks for the quick response. I just ran the code again and got the following error `AttributeError: 'tuple' object has no attribute 'reindex'`
> 
> When I take a look at the predictions file, I get the 10 columns and the 11k rows. however, all the info seemed to be clustered in cell A1 and the rest is empty. Would this be the issue?

Hi @MarijnQ, I'm here to help you solve the issue you are dealing with.  I think what is happening here is that the model.predict function returns a tuple object containing the predictions and an output directory. When the predictions variable is assigned to this tuple object, if you call .reindex, you will get the error you saw above. The way to get this to work is to assign the predictions variable like this `predictions, _ = model.predict(dft.rename(columns={'Query': 'Questions'} ))`. This will assign a pandas DataFrame to the predictions variable which you can then call .reindex() on while concatenating the predictions and training df. If you try `pd.concat([dft, predictions.reindex(dft.index)], axis=1)` after assigning predictions in the manner mentioned above, you should be able to combine the predictions and training DataFrame. Let me know if this works for you!

**Comment by w4nderlust** [comment]
@connor-mccorm that's a good call, silly of me not realizing it :)

**Comment by MarijnQ** [comment]
@connor-mccorm I could kiss you! This was the fix I was looking for!

**Comment by connor-mccorm** [comment]
I am closing this issue as it appears to have been solved. If the issue persists, feel free to reopen and I can help with whatever is needed!
