### ISSUE TITLE
Documentation bug: TensorFlow or PyTorch?

### ISSUE THREAD

**Issue by rasbt** [ludwig-ai/ludwig#1833]
Just flipping through the Readme, I see it says that "It is built on top of PyTorch." But then I was watching the video at ludwig.ai (https://ludwig-ai.github.io/ludwig-docs/0.4/) and it says that it is a toolbox based on TensorFlow. I think the video maybe needs to be updated.

**Comment by w4nderlust** [comment]
@rasbt that's a very legitimate question.
The current version of Ludwig on pypi is 0.4.1 and is indeed based on ToensorFlow. We have been hard at work in the last 6 months to do a full porting to PyTorch. The code in the main branch + the recent 0.5rcX releases are all PyTorch based. We will soon release the final 0.5 and update the documentation and the video accordingly.
