### ISSUE TITLE
Convert dict and tuple return values to structured, documented alternatives

### ISSUE THREAD

**Issue by dantreiman** [ludwig-ai/ludwig#1925]
The ludwig codebase makes extensive use of methods which return either tuples or dictionaries.  Wherever it is reasonable to do so, these should be refactored to use structured data types (i.e. `dataclasses`)

---

Examples:

Multiple returns as tuple:
```python
       (training_set, validation_set, test_set, training_set_metadata) = self.preprocess(...)
```

Dictionaries with hard-coded keys
```
        self.predictions_key = PREDICTIONS
        self.probabilities_key = PROBABILITIES
        self.logits_key = LOGITS

        return {
            self.probabilities_key: probabilities,
            self.predictions_key: predictions,
            self.logits_key: logits,
        }
```

Dictionaries with programmatically constructed keypaths:
```python
    for of_name, of_preds in preds.items():
        for pred_name, pred_values in of_preds.items():
            if pred_name not in EXCLUDE_PRED_SET:
                key = f"{of_name}_{pred_name}"
                predictions[key].append(pred_values)
```

**Comment by justinxzhao** [comment]
Potentially related: #1655

**Comment by dantreiman** [comment]
Good point.  We'll need to be careful when we do this refactoring to ensure that everything we do is torchscript-compatible.
