### ISSUE TITLE
Ludwig fails to install on Python 3.10 and Windows 10

### ISSUE THREAD

**Issue by aabmets** [ludwig-ai/ludwig#2025]
Running `pip install ludwig` on Python 3.10 and Windows 10 produces the following error:

```
Collecting scikit-learn<1.0
  Using cached scikit-learn-0.24.2.tar.gz (7.5 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [46 lines of output]
      Partial import of sklearn during the build process.
      INFO: No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      Traceback (most recent call last):
      /---/
      distutils.errors.DistutilsPlatformError: 
      Microsoft Visual C++ 14.0 or greater is required. 
      Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

When I fork ludwig and try to install dependencies from the local requirements.txt file, 
everything works fine and scikit-learn version **1.0.5** is installed. 
Why is `pip` using scikit-learn version **0.24.2**?
The error message persists even when the MS build tools have been installed.

**Comment by w4nderlust** [comment]
@aabmets thank you for this. I guess the issue has to do with 3.10 and newer versions of scikit-learn. Will need to test out if increasing the version of scikit-learn breaks tests somewhere and adjust accordingly. Will get back to you soon. Glad you were anyway able to use Ludwig already with a newer version of scikit-learn installed.
