### ISSUE TITLE
Add additional in-training evaluation metrics for binary and category output features.

### ISSUE THREAD

**Issue by justinxzhao** [ludwig-ai/ludwig#2067]
There's larger set of statistics that we calculate at prediction time, i.e. from [calculate_overall_stats](https://github.com/ludwig-ai/ludwig/blob/master/ludwig/features/binary_feature.py#L310-L338).

We should add these as in-training evaluation metrics, assuming they are relatively inexpensive to compute.

**Comment by w4nderlust** [comment]
Some of them are expensive, some are less. I would say at least the basic ones like p, r, f1 and things we believe people would want to use for validation, should be there.
