### ISSUE TITLE
load_util package in automl example can not be imported

### ISSUE THREAD

**Issue by Jeffwan** [ludwig-ai/ludwig#2136]
**Describe the bug**

I tried to follow automl guidance to run an example but encounter follow issues. 
![image](https://user-images.githubusercontent.com/4739316/173508481-279c7c48-03d2-455d-b634-a7ab88b415bd.png)

I am using `ludwigai/ludwig:0.5.2` image.

**To Reproduce**

1. Follow guidance https://ludwig-ai.github.io/ludwig-docs/0.5/user_guide/automl/
2. Run `from load_util import load_mushroom_edibility` 

Please provide code, yaml config file and a sample of data in order to entirely reproduce the issue.
Issues that are not reproducible will be ignored.

**Expected behavior**
The example should work without additional dependencies. 

**Screenshots**

**Environment (please complete the following information):**

- OS: \[e.g. iOS\] MacOS
- Version \[e.g. 22\] 0.5.2
- Python version 3.8.13
- Ludwig version 0.5.2

**Additional context**

**Comment by amholler** [comment]
The script needs to be run from this context
https://github.com/ludwig-ai/experiments/tree/main/automl/validation/mushroom_edibility

**Comment by amholler** [comment]
@Jeffwan Please let me know if you need any further info.

**Comment by tgaddair** [comment]
I wonder if it would be possible to consolidate the [load_util](https://github.com/ludwig-ai/experiments/blob/main/automl/validation/mushroom_edibility/load_util.py) helper function into the `ludwig.datasets` module.

I'm thinking something like change `load_util.load_mushroom_edibility()` to be `ludwig.datasets.mushroom_edibility.load()`. 

Is the goal of the helper primarily to add the split column deterministically? That could be a good thing to add back to the ludwig dataset. What do you think @amholler @justinxzhao ?

**Comment by amholler** [comment]
Hi, @tgaddair Yes, the goal of the helper is to add the split column deterministically, and there's currently load_util
methods in the experiments repo for each autoML dataset that did not have all 3 splits deterministically defined.
It is a good idea to add this functionality to the ludwig repo (I got the same suggestion from @justinxzhao this morning).

**Comment by amholler** [comment]
https://github.com/ludwig-ai/ludwig/pull/2159

**Comment by justinxzhao** [comment]
This has been fixed, both across the experiments repo, as well as in the documentation:

https://ludwig-ai.github.io/ludwig-docs/0.5/user_guide/automl/
<img width="802" alt="image" src="https://user-images.githubusercontent.com/3459541/178897535-213f05fc-c796-4bb1-b39d-edd86c0b9751.png">
