### ISSUE TITLE
API for preprocessing only ?

### ISSUE THREAD

**Issue by yanisIk** [ludwig-ai/ludwig#217]
**Is your feature request related to a problem? Please describe.**
Problem: getting access to preprocessed data without training

**Describe the use case**
I would like to use ludwig but just to preprocess my data using the yaml file and skipping the training part.

**Describe the solution you'd like**
- CLI approach: 
`ludwig preprocess --data_csv path/to/file.csv --dataset_definition_definition path/to/def.yml`
- API approach:
```
from ludwig import LudwigPreprocessing

dataset_definition = {...}
preprocessor = LudwigPreprocessing(dataset_definition)
preprocessed_dataframe = preprocessor.preprocess(dataset_dataframe)
```

**Describe alternatives you've considered**
An alternative right now would be to use it as suggested, killing the process during the training step then using the generated preprocessed data.

**Comment by w4nderlust** [comment]
I'm curious, what is your usecase for this?
i could definitely add it to the backlog, but just want to understand how useful could this be in general.

In the mean time, there is an undocumented entry point for doing this: `ludwig/data/preprocessing.py` has a `__main__` that works like this:
```
usage: preprocessing.py [-h] -id DATASET_CSV [-ime TRAIN_SET_METADATA_JSON]
                        -od OUTPUT_DATASET_H5 -ome OUTPUT_METADATA_JSON
                        [-f FEATURES] [-p PREPROCESSING_PARAMETERS]
                        [-rs RANDOM_SEED]

This script takes csv files as input and outputs a HDF5 and JSON file
containing a dataset and the train set metadata associated with it

optional arguments:
  -h, --help            show this help message and exit
  -id DATASET_CSV, --dataset_csv DATASET_CSV
                        CSV containing contacts
  -ime TRAIN_SET_METADATA_JSON, --train_set_metadata_json TRAIN_SET_METADATA_JSON
                        Input JSON containing metadata
  -od OUTPUT_DATASET_H5, --output_dataset_h5 OUTPUT_DATASET_H5
                        HDF5 containing output data
  -ome OUTPUT_METADATA_JSON, --output_metadata_json OUTPUT_METADATA_JSON
                        JSON containing metadata
  -f FEATURES, --features FEATURES
                        list of features in the CSV to map to hdf5 and JSON
                        files
  -p PREPROCESSING_PARAMETERS, --preprocessing_parameters PREPROCESSING_PARAMETERS
                        the parameters for preprocessing the different
                        features
  -rs RANDOM_SEED, --random_seed RANDOM_SEED
                        a random seed that is going to be used anywhere there
                        is a call to a random number generator: data
                        splitting, parameter initialization and training set
                        shuffling
```
`preprocessing` and `features` are the same as the respective sections in the yaml file. Let me know if this covers your need for the moment.

**Comment by yanisIk** [comment]
My use case would be to use ludwig just to preprocess and then use H2O or any other AutoML library to build the model.

Ludwig being defined as an ML Toolbox, it would be nice to use some specifics tools and not the whole tools at once.

This undocumented script is exactly what I was looking for, didn't dig enough in the code, should have linked it first.

**Comment by dehdari** [comment]
This feature would also be useful for getting Ludwig to work with some model interpretability libraries, which perturb the input feature values a little bit before sending the modified data to the predictor.

**Comment by w4nderlust** [comment]
I see, good point. I will consider adding it in the next releases, as the functions are all already there, it's a matter of finding a nice way to expose them.

**Comment by cvarrichio** [comment]
Yes, I agree that additional interpretability would be a key enhancement for this product.  This is one way to achieve it, enabling compatibility with LIME and other methods.

**Comment by w4nderlust** [comment]
Starting from v0.2, the preprocessing is available for user to play around with, as now one can import whatever they like from `data.preprocessing`., although the only fully documented part of the code remains the API, so you can play with preprocessing, but it is not fully documented yet, in particular because we are working towards many changes in the preprocessing pipeline for v0.3.
