### ISSUE TITLE
Incorrect predictions are produced

### ISSUE THREAD

**Issue by jimthompson5802** [ludwig-ai/ludwig#2259]
**Describe the bug**
After merge of PR #2027, incorrect predictions are generated.

**To Reproduce**

1. Checkout repo to commit aa0c63b
1. Run this simple linear regression model

```
import logging
from typing import Callable, Union, Dict, Any, Optional
import shutil

import pandas as pd

from sklearn.datasets import make_regression
import matplotlib.pyplot as plt

import torch
from torch import Tensor


from ludwig.api import LudwigModel




# self test
if __name__ == "__main__":
    import numpy as np

    config = {
        "input_features": [
            {"type": "number", "name": "x00"},
        ],
        "output_features": [
            {
                "name": "y",
                "type": "number",
            },
        ],
        "trainer":{
            "epochs": 50,
            "learning_rate": 0.001,
            "optimizer": {"type": "sgd", "momentum": 0.9},
        },
    }

    # Generate some non-linear noisy training data
    n_points = 500
    np.random.seed(1919)
    x_train = np.linspace(-1, 1, n_points)[:, np.newaxis]
    y_train = x_train + 0.4 * x_train * np.random.randn(n_points)[:, np.newaxis]
    # plt.figure(1)
    # plt.scatter(x_train, y_train, alpha=0.2);
    # plt.xlabel('x')
    # plt.ylabel('y')
    # plt.savefig("raw2_data.png")
    df = pd.DataFrame(
        np.hstack([x_train.reshape(-1,1), y_train.reshape(-1,1)]),
        columns=["x00", "y"]
    )
    df.to_csv('data/train.csv', index=False)
    print(df.head(10))

    model = LudwigModel(
        config=config,
        logging_level=logging.WARN
    )

    shutil.rmtree("/tmp/results", ignore_errors=True)
    training_stats, preprocessed_data, results_dir = model.train(
        training_set="data/train.csv", output_directory="/tmp/results", random_seed=1919
    )

    for n, w in model.model.named_parameters():
        print(n, w)

    predictions = model.predict("data/train.csv")
    print(f"test data predictions head:\n{predictions[0].head(10)}")
    print(f"test data predictions head:\n{predictions[0].tail(10)}")

    plt.figure(4)
    plt.scatter(x_train, y_train, marker='.', alpha=0.2, label='data')
    y_preds = model.predict(df)
    y_hat = y_preds[0]["y_predictions"]
    plt.plot(x_train, y_hat, color='black', label='model $\mu$')
    plt.xlabel('x')
    plt.ylabel('y')
    plt.legend()
    plt.savefig("linear_regression_plot.png")


    print(model.model)

    from io import StringIO
    my_data = """x00
    -0.99
    0
    0.99
    """

    preds = model.predict(pd.read_csv(StringIO(my_data)))
    print(preds)


    print("all done")
```
This will produce this plot, which  is incorrect.
<img width="651" alt="image" src="https://user-images.githubusercontent.com/1425269/178448632-42c5ebf1-6b83-4b3a-a70e-36dcbaaf915f.png">

**Expected behavior**
Running the same program at the prior commit d0e8439  the plot looks like this, which is the expected result
<img width="643" alt="image" src="https://user-images.githubusercontent.com/1425269/178449058-317e0a53-0742-4f40-9612-f623a50fb2fd.png">

**Screenshots**

**Environment (please complete the following information):**

- OS: MacOS 12.4 with Docker Desktop 4.6.0 
- Python version 3.8
- Ludwig version. 0.6.dev

**Comment by justinxzhao** [comment]
The configs, aside from new required parameters, look identical. The ECD architecture also looks identical.

Perhaps there's something that changed in the training process.

CC: @jppgks

**Comment by jimthompson5802** [comment]
Not sure if this helps but here is another piece of the puzzle.  

If one instruments the code in `train_step()` after the `optimizer.step()` call to display parameter weights, I can see the weights change during training.

However, if the model parameters are displayed right after training, the parameter values do not match the parameter values in the last batch of the FINAL epoch.   

From what I can see the model parameter values after training are equal to the parameter values displayed in the last bach of the FIRST epoch.

Somehow when the `predict()` method is retrieving  non-current parameter weights.
