### ISSUE TITLE
AttributeError: module 'tensorflow_core.keras.layers' has no attribute 'Normalization'

### ISSUE THREAD

**Issue by christine-petunia** [ludwig-ai/ludwig#2289]
I work with Jupyter Lab. Tensorflow version: 2.0

AttributeError: module 'tensorflow_core.keras.layers' has no attribute 'Normalization'

**Comment by connor-mccorm** [comment]
Hey @christine-petunia, just wanted to check in and see if you had any updates on this front. Was wondering if you could try updating to the latest version of Ludwig: `0.5.4` and let us know if this fixes the issue.
