### ISSUE TITLE
TMP folder on a different drive breaks

### ISSUE THREAD

**Issue by fire** [ludwig-ai/ludwig#2295]
**Describe the bug**

**To Reproduce**

Store root on one file system and home in a different filesystem.

/home/username/.local/lib/python3.10/site-packages/ludwig/utils/checkpoint_utils.py

Please provide code, yaml config file and a sample of data in order to entirely reproduce the issue.
Issues that are not reproducible will be ignored.

**Expected behavior**

Not error out with errno-18-cross-device-link

**Screenshots**

**Environment (please complete the following information):**

- OS: Linux fedora 5.17.5-300.fc36.x86_64 #1 SMP PREEMPT Thu Apr 28 15:51:30 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
- Version 36
- Python version 3
- Ludwig version 0.5.4

**Additional context**
https://stackoverflow.com/questions/11578443/trigger-io-errno-18-cross-device-link

Try

Changing os.replace to shutil.move(tmp_path, save_path)

**Comment by dantreiman** [comment]
I merged this PR about 2 weeks ago, because I may have encountered the same issue:

https://github.com/ludwig-ai/ludwig/pull/2225

@fire Could you try the same run using the latest ludwig master and see if it is resolved?

**Comment by fire** [comment]
Is there docs on how to do that?

**Comment by w4nderlust** [comment]
You can. do `python -m pip install git+https://github.com/ludwig-ai/ludwig.git` (may need to uninstall and re-install or upgrade) and here are more details on hot to work with branches and specific commits: https://adamj.eu/tech/2019/03/11/pip-install-from-a-git-repository/

**Comment by fire** [comment]
Will wait for a new minor release then.

**Comment by tgaddair** [comment]
Hey @fire, this should be fixed now in v0.5.5. Please try it out and let us know how it goes!

**Comment by dalianaliu** [comment]
We just released v0.6. I'm closing this, and please reopen if you have questions.
