### ISSUE TITLE
Flakiness in `test_hyperopt_ray_horovod.py::test_hyperopt_executor`

### ISSUE THREAD

**Issue by geoffreyangus** [ludwig-ai/ludwig#2322]
Seeing `tests/integration_tests/test_hyperopt_ray_horovod.py::test_hyperopt_executor[scenario1]` fail intermittently.

Example CI test failure from [this PR](https://github.com/ludwig-ai/ludwig/pull/2310): https://github.com/ludwig-ai/ludwig/runs/7549814691?check_suite_focus=true. Re-running the failed jobs allowed the tests to pass successfully.

**Comment by tgaddair** [comment]
Possible duplicate of #2451.

**Comment by arnavgarg1** [comment]
Fixed by https://github.com/ludwig-ai/ludwig/pull/2599, closing
