### ISSUE TITLE
Batch Size: Auto Error

### ISSUE THREAD

**Issue by connor-mccorm** [ludwig-ai/ludwig#2326]
Error being thrown when `batch_size` is set to `auto` which is default from create_auto_config.

**Comment by tgaddair** [comment]
This was fixed in #2286. If this isn't in v0.5.4, we should make a hotfix.

**Comment by connor-mccorm** [comment]
Confirmed this was fixed in https://github.com/ludwig-ai/ludwig/pull/2286
