### ISSUE TITLE
Write out data split information as a separate file, i.e. splits.csv, separate from preprocessed data.

### ISSUE THREAD

**Issue by justinxzhao** [ludwig-ai/ludwig#2375]
At the moment, we don’t write the raw data splits to a separate file, i.e. (row #, split #). 

This can be useful for when the preprocessed data is too large to write to disk, yet a user may still might want to inspect offline which rows of their dataset were used in which data subsets of their modeling run.

One potential location for such metadata would be in the existing `training_set_metadata.json` file, or perhaps a separate `splits.csv` file.

**Comment by tgaddair** [comment]
We do actually write this information when `skip_saved_processed_inputs=False` [here](https://github.com/ludwig-ai/ludwig/blob/master/ludwig/data/preprocessing.py#L1723). Note that this only applies when we are using a dataset from a file, as opposed to a dataframe. So perhaps it could be extended to support the latter.

**Comment by justinxzhao** [comment]
@tgaddair Ah, thanks for the catch! We should be sure to include this in our documentation.
