### ISSUE TITLE
Reduce memory requirements for TabTransformerCombiner for situation of no categorical input features

### ISSUE THREAD

**Issue by jimthompson5802** [ludwig-ai/ludwig#2411]
Currently the constructor for `TabTransformerCombiner` always allocates a transformer stack.  However, the transformer stack is only used if categorical input features are in the training data.  If there are no categorical features, the algorithm does not use the transformer stack.   In addition to allocating unneeded memory, this complicates the unit test for this combiner.

Proposed change is to refactor the constructor to allocate the transformer stack only if categorical features are present in the input features.

**Comment by dalianaliu** [comment]
Piero and Jim already chatted about this. @jimthompson5802 what's the next step for this?

**Comment by dalianaliu** [comment]
Hi @jimthompson5802 looks like you have chatted with Piero. Would you like to resolve this or leave it open for next steps?

**Comment by jimthompson5802** [comment]
@dalianaliu   Once I'm done with the torchvision integraiton work, I can take a stab at this.
