### ISSUE TITLE
[Hyperopt] `num_samples` doesn't work well with only `grid_search` parameter spaces

### ISSUE THREAD

**Issue by arnavgarg1** [ludwig-ai/ludwig#2449]
Say you have the following search space:

```
    search_parameters = {
        "trainer.learning_rate": {"space": "grid_search", "values": [0.001, 0.005, 0.01]},
        output_feature_name + ".output_size": {"space": "grid_search", "values": [16, 21, 36]},
        output_feature_name + ".num_fc_layers": {"space": "grid_search", "values": [1, 3, 6]},
    }

    hyperopt_configs = {
        "parameters": search_parameters,
        "goal": "minimize",
        "output_feature": output_feature_name,
        "validation_metrics": "loss",
        "executor": {TYPE: "ray", "num_samples": 1},
        "search_alg": {TYPE: "variant_generator"},
    }
```

When `num_samples` is set to 1 in this case, it produces 27 trials as expected. However, if `num_samples` is set to 2, then it produces 54 trials, which essentially includes a duplicate of each of the 27 trials.

**Expected behavior**: Ludwig can detect this and modify `num_samples` to 1 if only grid_search parameters are being used in the search space to avoid duplication of trials.

**Comment by tgaddair** [comment]
My preference here would be:

1. If `num_samples` is not provided, default to 1 (I believe this is already the default, but if this ever changes, we should be sure to account for this case).
2. If the user specified `num_samples > 1` but is using only grid search, we should issue a warning to the user, but allow trials to proceed anyway. Reason being there may be some odd scenario where the user wants to run trials more than once, for example if there is some non-determinism in the training process they want to account for.
