### ISSUE TITLE
Tutorial colab notebooks fail

### ISSUE THREAD

**Issue by jimthompson5802** [ludwig-ai/ludwig#2450]
**Describe the bug**
The MNIST tutorial notebook fails with a colab kernel restart error at the start of the training cycle.
![image](https://user-images.githubusercontent.com/1425269/188345869-c1ff54ff-75be-41b5-8c61-e18cf4c1386f.png)
![image](https://user-images.githubusercontent.com/1425269/188345896-4bf54f69-dd86-4995-8b82-9ea9fd82a6d7.png)

**To Reproduce**

Run the MNIST Ludwig API [tutorial colab notebook](https://colab.research.google.com/github/ludwig-ai/ludwig-docs/blob/master/docs/examples/mnist_colab_notebooks/MNIST_Image_Classification_with_Ludwig_Python_API.ipynb) 

**Expected behavior**
Successful execution of the notebook

**Screenshots**
see above.

**Environment (please complete the following information):**

- OS: Ubuntu
- Version 18.04
- Python version 3.7
- Ludwig version 0.6.dev0

**Additional context**
This problem will probably affect the other tutorial notebooks.

The error appears related to the verison of `prototbuf` installed in colab vs the version required by Ludwig.  colab pre-installs `protobuf 3.9.2.`.  Ludwig `requirements.txt` specifies `protobuf 3.20.1`, which upgrades `protobuf` when Ludwig is installed on colab.

**Comment by jimthompson5802** [comment]
Possible work-around, uninstall tensorflow before installing ludwig, i.e.,
```
!pip uninstall -y tensorflow
!pip install git+https://github.com/ludwig-ai/ludwig.git#egg=ludwig  --quiet
```

**Comment by dalianaliu** [comment]
Thanks @jimthompson5802, we'll take a look. Have you resolved the issue?

**Comment by jimthompson5802** [comment]
@dalianaliu   from my perspective, uninstall tensorflow "fixed" the issue.  Kind of a hacky solution but it allowed me to continue testing.

No sure what else we can do at this time.

I'll close the issue.
