### ISSUE TITLE
TypeError: '>' not supported between instance of 'str' and 'int' when tune_for_memory is True

### ISSUE THREAD

**Issue by Jeffwan** [ludwig-ai/ludwig#2499]
**Describe the bug**
I tried to set tune_for_memory to True and meet TypeError. 

![image](https://user-images.githubusercontent.com/4739316/190315290-4a7c7aad-a53a-4568-a907-b4ebe8dc8481.png)

**To Reproduce**

```
    automl_config = create_auto_config(
        dataset=dataset_df,
        target=target_column,
        time_limit_s=time_limit_s,
        tune_for_memory=tune_for_memory,
        user_config=None,
        random_seed=default_random_seed,
        use_reference_config=False,
    )


    auto_train_results = train_with_config(
        dataset=dataset_df,
        config=automl_config,
        output_directory=output_dir,
        random_seed= default_random_seed,
    )

```

**Expected behavior**
tune_for_memory should be working without any expected error

**Environment (please complete the following information):**

- OS: \[e.g. iOS\] ludwigai/ludwig:nightly
- Version \[e.g. 22\] 
- Python version 3.8
- Ludwig version  nightly

**Comment by tgaddair** [comment]
Thanks @Jeffwan for pointing this out. We haven't been using `tune_for_memory` internally and it's experimental at the moment, but I managed to fix the issue in #2508. We should be able to land this into the 0.6 release tomorrow.
