### ISSUE TITLE
`LudwigModel.preprocess` with `skip_save_processed_input=False` and Ray backend returns flat Image/Audio features

### ISSUE THREAD

**Issue by geoffreyangus** [ludwig-ai/ludwig#2645]
**Describe the bug**
In order for the RayDatasetManager to conform to the PyArrow requirements when caching preprocessed input, `preprocess` currently flattens Image and Audio tensors. This is accounted for in [RayDatasetBatcher._prepare_batch](https://github.com/ludwig-ai/ludwig/blob/b168ca1aa5763bb38e4318a72ab86b29b63bb9de/ludwig/data/dataset/ray.py#L312-L315), where the tensors are reshaped to their original shape.

However, the returned values from `preprocess` remain flat. This seems unexpected from the user's perspective. `preprocess` called with a local backend returns the tensors in their proper shape.

**To Reproduce**
1. Initialize a LudwigModel with an Image or Audio feature and a Ray backend
2. Run `LudwigModel.preprocess` with `skip_save_processed_input=False`

This behavior can also be reproduced by simply running `tests/integration_tests/test_ray.py::test_ray_image` and inspecting the values of the DataFrames returned by the Ray backend after https://github.com/ludwig-ai/ludwig/pull/2637 is merged in. The workaround in the unit tests in that PR is to ensure that the tensors are flattened before comparing the outputs of `preprocess` run with both local and Ray backends.

**Expected behavior**
I expect the tensors to be returned from `preprocess` in their original shape.

**Comment by tgaddair** [comment]
Not sure we can do anything about this, as it's a limitation in PyArrow.
