### ISSUE TITLE
Add Kaggle tabular dataset and multiscale benchmarksfor multimodal learning

### ISSUE THREAD

**Issue by skanjila** [ludwig-ai/ludwig#2657]
**Is your feature request related to a problem? Please describe.**
Want to add the following datasets:
two sources to mine for good datasets:
Kaggle Tabular Playground Challenge - a monthly tabular data challenge:  https://www.kaggle.com/search?q=tabular+playground+series
 [MultiBench: Multiscale Benchmarks for Multimodal Representation Learning](https://arxiv.org/abs/2107.07502)

**Describe the use case**
We need to add more datasets to ludwig for general testing

**Describe the solution you'd like**
Same behavior to upload and download dataset APIs

**Describe alternatives you've considered**
There are lots of datasets to add so the alternative would be adding similar datasets

**Additional context**
N/A

**Comment by dalianaliu** [comment]
Hi @skanjila. We'll talk a look at this. Can you tell us more about the use case?

**Comment by dalianaliu** [comment]
Hi @skanjila, please go ahead and summit a PR. Let us know if you need any help.

I'm curious if you could share more about your use case?

**Comment by skanjila** [comment]
:( I'm a committer on Ludwig and actually started the datasets initiative with @tgaddair and @w4nderlust , this idea was actually proposed by @dantreiman , I am just working on the implementation of this till the model-hub starts getting incorporated
