### ISSUE TITLE
pass image in memory to predict API for image classification

### ISSUE THREAD

**Issue by Felix-N** [ludwig-ai/ludwig#268]
Is it possible to pass image(s) for classification prediction via API without writing them to the hard drive first?

**Comment by w4nderlust** [comment]
@Felix-N at the moment you can't, it's a limitation, I know, but we are working on a way around that, stay tuned.

**Comment by carlogrisetti** [comment]
@w4nderlust Do you have any hints on how this could be implemented and\or you already are working on something similar that can be helped upon?

It's basically the only missing feature (along with the unability to export models, but this will hopefully be added as a side effect of the TF2 porting) that forces me to go traditional TF\Keras on some projects.

Thanks!

**Comment by w4nderlust** [comment]
It took a while from the original request, but PR #1174 addresses this issue, closing it, please let us know if this works for you @Felix-N  .

**Comment by w4nderlust** [comment]
@carlogrisetti this should be a welcome feature for you too I believe ;)

**Comment by carlogrisetti** [comment]
It most definitely is!
Gonna test it as soon as I can :)
