### ISSUE TITLE
ValueError: invalid literal for int() with base 16 during data processing using minio

### ISSUE THREAD

**Issue by Jeffwan** [ludwig-ai/ludwig#2726]
**Describe the bug**

Seem there's an error thrown during cache checksum calculation. Seems it calculate the eTag of dataset and try to get original Hex representation.  Looks like hyphen ` 'b6e64f35b2cb730d93770942a59b2efa-2' ` is the problem but hyphen itself in ETag is correct which indicates multi parts. 
https://teppen.io/2018/06/23/aws_s3_etags/#what-is-an-s3-etag

~~I didn't see this problem in the past using minio~~(update: I uploaded files from browser in the past, which means multi-part uploading was not used). I recently come back to the project and notice it's not working suddenly.. Not sure if community has seen similar issues

**To Reproduce**

recently I create a new store for minio and notice it can not read and process minio files correctly. 

```
╒═══════════════╕
│ PREPROCESSING │
╘═══════════════╛

Backend config has num_cpu not set. provision_preprocessing_workers() is a no-op in this case.
Traceback (most recent call last):
  File "auto_train.py", line 384, in <module>
    run_automl_job(args.job_id, args.type, args.dataset, args.target, args.time_limit_s, args.tune_for_memory, args.artifact_storage_backend, args.object_storage_path, args.output_directory, args.object_storage_endpoint)
  File "auto_train.py", line 98, in run_automl_job
    train_cli(automl_config, dataset_df, output_directory=output_dir, random_seed=default_random_seed, callbacks=[EarlyStopCallback()])
  File "/usr/local/lib/python3.8/site-packages/ludwig/train.py", line 181, in train_cli
    model.train(
  File "/usr/local/lib/python3.8/site-packages/ludwig/api.py", line 449, in train
    preprocessed_data = self.preprocess(
  File "/usr/local/lib/python3.8/site-packages/ludwig/api.py", line 1294, in preprocess
    preprocessed_data = preprocess_for_training(
  File "/usr/local/lib/python3.8/site-packages/ludwig/data/preprocessing.py", line 1569, in preprocess_for_training
    cache = backend.cache.get_dataset_cache(config, dataset, training_set, test_set, validation_set)
  File "/usr/local/lib/python3.8/site-packages/ludwig/data/cache/manager.py", line 107, in get_dataset_cache
    key = self.get_cache_key(dataset, config)
  File "/usr/local/lib/python3.8/site-packages/ludwig/data/cache/manager.py", line 126, in get_cache_key
    return calculate_checksum(dataset, config)
  File "/usr/local/lib/python3.8/site-packages/ludwig/data/cache/util.py", line 11, in calculate_checksum
    "dataset_checksum": original_dataset.checksum,
  File "/usr/local/lib/python3.8/site-packages/ludwig/data/cache/types.py", line 77, in checksum
    return checksum(self.path)
  File "/usr/local/lib/python3.8/site-packages/ludwig/utils/fs_utils.py", line 181, in checksum
    return fs.checksum(path)
  File "/usr/local/lib/python3.8/site-packages/s3fs/core.py", line 573, in checksum
    return int(info["ETag"].strip('"'), 16)
ValueError: invalid literal for int() with base 16: 'b6e64f35b2cb730d93770942a59b2efa-2'
```

**Expected behavior**

data processing should not return error.

`python auto_train.py --target=recommended --time_limit_s=180 --type single_class --dataset=s3://openstudio-automl/dataset/rotten_tomatoes.csv`

preprocessing config

```
    'preprocessing': {   'oversample_minority': None,
                         'sample_ratio': 1.0,
                         'split': {   'probabilities': [0.7, 0.1, 0.2],
                                      'type': 'random'},
```

**Screenshots**

**Environment (please complete the following information):**
- OS: \[e.g. iOS\]
- Version \[e.g. 22\]
- Python version 3.8.13
- Ludwig version 0.6

**Additional context**

**Comment by Jeffwan** [comment]
preprocessing config

```
    'preprocessing': {   'oversample_minority': None,
                         'sample_ratio': 1.0,
                         'split': {   'probabilities': [0.7, 0.1, 0.2],
                                      'type': 'random'},
```

**Comment by tgaddair** [comment]
Hi @Jeffwan, I haven't seen this specific issue, but I have run into issues in the past when using Minio + fsspec where Minio believes there is an issue with the etag. 

In this case though I agree this looks an issue in s3fs. They should probably strip out the `-` in this case. Did you want to file an issue in the s3fs repo?

**Comment by Jeffwan** [comment]
@tgaddair Thanks for the confirmation. I did file a similar one in s3fs repo. https://github.com/fsspec/s3fs/issues/624.

**Comment by Jeffwan** [comment]
This has been patched in newer `s3fs` and I notice I am actually using an old version. Upgrading version works for me. Thanks!

**Comment by tgaddair** [comment]
Awesome! Glad you got it working!
