### ISSUE TITLE
Automl for multiple targets?

### ISSUE THREAD

**Issue by andife** [ludwig-ai/ludwig#2741]
Hello,

I wonder how it is possible to create multiple targets at automl on tables data. 
My data consists of three input columns and 3 output columns. How does the api of auto_train work?
Can someone provide a link?

Thank you

**Comment by justinxzhao** [comment]
Hi @andife,

The automl API is documented at https://ludwig.ai/latest/user_guide/automl/. [create_auto_config](https://ludwig.ai/latest/user_guide/automl/#create_auto_config) may be of interest.

Right now Ludwig AutoML only supports one target at a time.

Out of curiosity, do you have strong reasons to prefer 1 model that predicts on 3 outputs vs. 3 models, one for each output?
