### ISSUE TITLE
bug: Misleading error message for incorrect input feature names

### ISSUE THREAD

**Issue by ksbrar** [ludwig-ai/ludwig#2832]
**Describe the bug**
An error is raised if an input parameter is incorrect and not in the dataset. In Ludwig 0.5 a clear error was returned to indicate the problem but now only a `keyError` is raised, flummoxing a user trying to debug the problem.

**To Reproduce**

1. Run adult census income example https://ludwig.ai/latest/examples/adult_census_income/
2. Change an input feature name
3. Wait for error.

**Expected behavior**
A clear and concise error message.

**Additional context**
Original Slack discussion: https://ludwig-ai.slack.com/archives/C01PN6M2RSM/p1670612946929589

**Comment by arnavgarg1** [comment]
Thanks for raising this error @ksbrar!
