### ISSUE TITLE
LudwigModel `create_model` static method requires a `config_obj`, but it should take a dict or config obj

### ISSUE THREAD

**Issue by arnavgarg1** [ludwig-ai/ludwig#2859]
The `LudwigModel` api has a static `create_model` function that creates a BaseModel object. This is the API for the `create_model` function:

```def create_model(config_obj: ModelConfig, random_seed: int = default_random_seed) -> BaseModel:```

The problem with this is that it is a static method, but it expects a ModelConfig object which is only created in the LudwigModel constructor/initialization. This is a problem because this method is essentially not useful unless a LudwigModel object is first created and the config object is retrieved via `model.config_obj`.

Some solutions:

1. Allow this API to take a union of Dict, ModelConfig
2. If the object is of type dict, create the ModelConfig object by doing `ModelConfig.from_dict(config_obj)` and reassign it

**Comment by aseemk98** [comment]
Hi @arnavgarg1, I can take this up. Is this issue still persistent?

**Comment by aseemk98** [comment]
I've added a [PR](https://github.com/ludwig-ai/ludwig/pull/3333) for this. Thanks!

**Comment by aseemk98** [comment]
Hi @tgaddair @arnavgarg1 ,
I would really appreciate it if you could refer me to a different issue (or a feature addition)!
Thanks.
