### ISSUE TITLE
Possible using torch DDP(DistributedDataParallel)?

### ISSUE THREAD

**Issue by ericxsun** [ludwig-ai/ludwig#2886]
**Is your feature request related to a problem? Please describe.**
How could we train model with torch DDP?

**Comment by tgaddair** [comment]
Hey @ericxsun, adding DDP is something we've been considering lately, but haven't prioritized it since Horovod is currently supported and it's not clear what the added benefit of DDP would be for most users. Is there a reason you would prefer to use DDP instead of Horovod for distributed training in Ludwig?

**Comment by ericxsun** [comment]
Just be familiar with DDP and technical stack in the group is native PyTorch。Change to Horovod may not be possible.

**Comment by tgaddair** [comment]
Hey @ericxsun, are you also able to use Ray with Ludwig? If so, it shouldn't be a problem integrating the existing distributed training into your stack. The only issue would be making sure the environment has the right dependencies, however, we provide a Docker image ([ludwig-ray-gpu](https://hub.docker.com/r/ludwigai/ludwig-ray-gpu)) that has all the dependencies, including Horovod, pre-installed.

If you're not able to use Ray, you can still do distributed training, but not distributed data preprocessing, which limits the scale of the data you can use for training to something that can fit entirely in memory.

To integrate DDP into Ludwig there are really two main touch points. The first is the Ray Trainer, which would need to be changed to support Ray's `TorchConfig` [here](https://github.com/ludwig-ai/ludwig/blob/master/ludwig/backend/ray.py#L140). The other would the in [trainer.py](https://github.com/ludwig-ai/ludwig/blob/master/ludwig/trainers/trainer.py) where all the calls to `self.horovod` would need to be changed to the DDP equivalent API calls.

Let me know if you'd like to discuss this further, I'd be happy to put together a quick prototype using DDP at some point soon if it would be helpful.

**Comment by tgaddair** [comment]
Hey @ericxsun, I've implement an initial version of DDP integration with Ray in #2890. Let me know if this works for your use case. I will do some benchmarking to see how it compares with Horovod in terms of performance before landing.

**Comment by ericxsun** [comment]
Hi @tgaddair, sorry for late reply. Thank you so much. I'll try the **your implementation of DDP integration with Ray in https://github.com/ludwig-ai/ludwig/pull/2890**.  Thank you again.

**Comment by tgaddair** [comment]
Thanks @ericxsun, let me know if it works for you. I haven't done any testing to verify correctness yet beyond small local tests, so let me know if you encounter any issues!

**Comment by tgaddair** [comment]
I made some updates earlier that fixed gpu support. After running benchmarks, the performance was almost identical to Horovod, with and without AMP, so should be good to merge in the PR once it's reviewed.
