### ISSUE TITLE
Confused defined train_step in Trainer and evaluation_step/predict_step in Model?

### ISSUE THREAD

**Issue by ericxsun** [ludwig-ai/ludwig#2895]
**Is your feature request related to a problem? Please describe.**

Why is `train_step` defined in [Trainer](https://github.com/ludwig-ai/ludwig/blob/4498c8736958c67f5ed8248a55234df96b1257c7/ludwig/trainers/trainer.py#L215), but `evaluation_step/predict_step` are defined in [Model (ECD/Base)](https://github.com/ludwig-ai/ludwig/blob/4498c8736958c67f5ed8248a55234df96b1257c7/ludwig/models/base.py#L182)？ As I know, [the old version(and before 0.4.1) - the TF-one](https://github.com/ludwig-ai/ludwig/blob/v0.4.1/ludwig/models/ecd.py), they are both defined in ECD class（as the [Model (ECD/Base)](https://github.com/ludwig-ai/ludwig/blob/4498c8736958c67f5ed8248a55234df96b1257c7/ludwig/models/base.py#L182))

Thanks a lot.

**Comment by tgaddair** [comment]
Hey @ericxsun, it's something that we could probably change either way (put both in ECD or put both in the trainer / predictor). Putting the eval step in ECD is really just. matter of convenience, as it runs a forward pass and updates metrics on the model. But I think the more principled thing to do is move it out of ECD. Do you have a preference for one approach vs the other?

**Comment by ericxsun** [comment]
It would be more logical to put the `train_step` in the Trainer and the `evaluate_step/predict_step` in the Predictor.

- model topology, metric_fn, loss_fn, they are both belonging to the ECD
- Train/Predict are workflow steps, they just call fn(foward, metric, loss) of the Model

so it would be better to move them out of ECD

**Comment by tgaddair** [comment]
I agree it would make more sense, though it might be a bit of a refactor. We can probably leave it as is for now until we re-visit trainers and predictors in general, unless this is a blocker for your work, in which case happy to look into it!
