### ISSUE TITLE
Resume training in MLflow run not reading/writing from/to artifacts properly

### ISSUE THREAD

**Issue by Peetee06** [ludwig-ai/ludwig#2952]
**Describe the bug**
I am resuming the training of a model in an MLflow run. I started training using the MflowCallback and then interrupt it with CTRL+C. I created following script that will restart that run and resume training:

```python
def resume_training(run_id):
    """Resume training a model."""
    with mlflow.start_run(run_id=run_id) as run:
        # get params and model of the train run to resume
        params = run.data.params
        mlmodel_path = mlflow.get_artifact_uri()
        logged_thresholds_path = pathlib.Path(
            mlflow.get_artifact_uri("model/thresholds.json")
        )
        model_resume_path = mlmodel_path.replace("file://", "")

        csv_path = params.get("csv_path")
        model_config = params.get("model_config")
        thresholds = params.get("thresholds")
        deterministic = int(params.get("deterministic"))
        random_seed = int(params.get("random_seed"))
        tmpdir = tempfile.mkdtemp()

        if not logged_thresholds_path.exists():
            mlflow.log_artifact(thresholds, "model")

        allow_parallel_threads = deterministic == 0
        model = ludwig.api.LudwigModel(
            config=model_config,
            logging_level=logging.INFO,
            callbacks=[ludwig.contribs.mlflow.MlflowCallback()],
            allow_parallel_threads=allow_parallel_threads,
        )

        try:
            data = pd.read_csv(csv_path)
        except pd.errors.EmptyDataError:
            raise pd.errors.EmptyDataError(
                f"File {csv_path} is empty. Please check the data."
            )
        model.train(
            dataset=data,
            random_seed=random_seed,
            output_directory=tmpdir,
            model_resume_path=model_resume_path,
        )
```

Following screenshot shows the artifacts logged to the run resumed:
![image](https://user-images.githubusercontent.com/17020705/213165025-89666cdd-4ff0-4a35-9277-512f532a2bcc.png)

After preprocessing the data the output states following:
`Resuming training of model: [...]/mlruns/0/d3dd4d3d24204fe69b2c7a4727998afa/artifacts/model/training_progress.json`
And right after that I get:
`FileNotFoundError: [Errno 2] No such file or directory: '[...]/mlruns/0/d3dd4d3d24204fe69b2c7a4727998afa/artifacts/model/training_progress.json'`

ludwig assumes the `training_process.json` right under "model" in the run's artifacts. But it actually is in "model/model" (see Screenshot above.

If I alter the following line:
```python
mlmodel_path = mlflow.get_artifact_uri()
```
To:
```python
mlmodel_path = mlflow.get_artifact_uri("model")
```
The training works properly then, but the `description.json` file will be placed in `model` instead of the artifacts root:
![image](https://user-images.githubusercontent.com/17020705/213167489-b10424fa-cd65-42af-9350-2d515db98890.png)

**To Reproduce**

1. Start training a LudwigModel using MlflowCallback
2. Interrupt the training
3. Use above script to resume training

**Expected behavior**
The training should resume properly and the `description.json` file should be in the artifact root of the train run.

**Comment by arnavgarg1** [comment]
Hi @Peetee06, thanks for flagging this issue. I plan to get to it early next week and will let you know as soon as I have updates.
