### ISSUE TITLE
Normalizing Text 

### ISSUE THREAD

**Issue by simonefrancia** [ludwig-ai/ludwig#299]
Hi,
I have built with Ludwig support a sentiment regressor that has in input text and in output returns two float values. My model features configuration is this:

```
    "input_features": [ {"name": "lyrics_body", 
                        "type": "text" , 
                        "encoder": "rnn", 
                        "cell": "lstm", 
                        "bidirectional": "true"} ], 


    "output_features": [
                            {"name": "valence", 
                            "type": "numerical"  }, 

                            {"name": "arousal", 
                            "type": "numerical" }

                        ]

```

My question is: for text I give in input, do I have to normalize it, or this task is implemented inside? Do you think it could help improving performance of regressor?
Thanks

**Comment by w4nderlust** [comment]
It depends what do you mean by normalize. Ludwig provides a [bunch of `word_format` functions](https://uber.github.io/ludwig/user_guide/#spacy-based-word-format-options) that map from raw text to list of tokens. If you want to do something different than what they do you can implement your own.

Regarding improving the performance, depending on the task, a batter tokenizer may help, and also playing around with the different encoders and hyperparameters of the encoders, and also with the preprocessing and training parameters may be beneficial.

**Comment by justinxzhao** [comment]
Ludwig supports [several spacy and huggingface-based tokenizers](https://ludwig-ai.github.io/ludwig-docs/0.5/configuration/preprocessing/#tokenizers).
