### ISSUE TITLE
RunTimeError when running regression example with GBM model type

### ISSUE THREAD

**Issue by skunkwerk** [ludwig-ai/ludwig#3092]
**Describe the bug**
When running on a machine with a GPU, I get the following error:
(from hummingbird/ml/operator_converters/_tree_implementations.py:180):
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument mat2 in method wrapper_mm)

**To Reproduce**
Code and sample data below:

```
from ludwig.api import LudwigModel
import pandas as pd

url = 'http://archive.ics.uci.edu/ml/machine-learning-databases/auto-mpg/auto-mpg.data'
column_names = ['MPG', 'Cylinders', 'Displacement', 'Horsepower', 'Weight',
                'Acceleration', 'Model Year', 'Origin']

df = pd.read_csv(url, names=column_names,
                          na_values='?', comment='\t',
                          sep=' ', skipinitialspace=True)

ludwig_config = {
    "model_type": "gbm",
    "input_features": [        
        {
            "name": "Cylinders",
            "type": "number",
        },
        {
            "name": "Displacement",
            "type": "number",
        },
        {
            "name": "Horsepower",
            "type": "number",
        },
        {
            "name": "Weight",
            "type": "number",
        },
        {
            "name": "Acceleration",
            "type": "number",
        },
        {
            "name": "Model Year",
            "type": "number",
        },
        {
            "name": "Origin",
            "type": "category",
        },
    ],
    "output_features": [
        {
            "name": "MPG",
            "type": "number",
            "optimizer": {"type": "mean_squared_error"}
        }
    ],
}
model = LudwigModel(config=ludwig_config)
results = model.experiment(dataset=df)
```

**Expected behavior**
Should run without any errors (switching to model_type='ecd' works fine, for example)

**Screenshots**
N/A

**Environment (please complete the following information):**

- OS: Linux
- Version: 4.15.0-163-generic
- Python version: 3.8.5
- Ludwig version: 0.6.3 (from Dockerfile 'ludwigai/ludwig-ray-gpu:0.6.3')

Thanks for the amazing library!

**Comment by tgaddair** [comment]
Thanks for raising this issue and providing and repo script @skunkwerk!

@jeffkinnison can you take a look?

**Comment by skunkwerk** [comment]
I'm also sometimes getting a different error from the same code, and I'm not sure how it surfaces but it seems to be coming from Ray:

ValueError: The `num_actors` parameter is set to 0. Please always specify the number of distributed actors you want to use.
FIX THIS by passing a `RayParams(num_actors=X)` argument to your call to lightgbm_ray.

**Comment by jeffkinnison** [comment]
@skunkwerk Thanks for following up here! I'm looking into both of these issues, but in the meantime can you see if they repro in nightly? GBMs were heavily updated recently, including moving away from `hummingbird` training, so the original issue may have been fixed already.

**Comment by jeffkinnison** [comment]
I was just able to repro this in master. Looking into a fix now!
