### ISSUE TITLE
AutoML fails with GBM unless you specify a learning rate

### ISSUE THREAD

**Issue by skunkwerk** [ludwig-ai/ludwig#3093]
**Describe the bug**
When running auto_train on a small tabular dataset with default settings, I get this error:
"ValidationError: {'learning_rate': ['Not a valid number.']}" from marshmallow/schema.py:909
I believe it's because the default config using a learning rate of "auto"

**To Reproduce**
Code & data below:

```
# try autoML with GPUs & GBDT
import pandas as pd
from ludwig.automl import auto_train

url = 'http://archive.ics.uci.edu/ml/machine-learning-databases/auto-mpg/auto-mpg.data'
column_names = ['MPG', 'Cylinders', 'Displacement', 'Horsepower', 'Weight',
                'Acceleration', 'Model Year', 'Origin']

df = pd.read_csv(url, names=column_names,
                          na_values='?', comment='\t',
                          sep=' ', skipinitialspace=True)

auto_train_results = auto_train(
    dataset=df,
    target='MPG',
    time_limit_s=120,
    tune_for_memory=False,
    user_config={'model_type': 'gbm'}
)
```

**Expected behavior**
Should run fine, which you can do by specifying the learning rate:

```
# try autoML with GBDT (fails unless you specify learning_rate)
import pandas as pd
from ludwig.automl import auto_train

url = 'http://archive.ics.uci.edu/ml/machine-learning-databases/auto-mpg/auto-mpg.data'
column_names = ['MPG', 'Cylinders', 'Displacement', 'Horsepower', 'Weight',
                'Acceleration', 'Model Year', 'Origin']

df = pd.read_csv(url, names=column_names,
                          na_values='?', comment='\t',
                          sep=' ', skipinitialspace=True)

auto_train_results = auto_train(
    dataset=df,
    target='MPG',
    time_limit_s=120,
    tune_for_memory=False,
    user_config={'model_type': 'gbm', 
                 'trainer':
                {
                    'learning_rate': 0.001,
                }
    }
)
```

**Screenshots**
N/A

**Environment (please complete the following information):**

OS: Linux
Version: 4.15.0-163-generic
Python version: 3.8.5
Ludwig version: 0.6.3 (from Dockerfile 'ludwigai/ludwig-ray-gpu:0.6.3')

**Comment by tgaddair** [comment]
Hey @skunkwerk, thanks for the repro! I ran the script you provided locally with both v0.6.3 and the latest master. I was able to repro in v0.6.3, but not in master, so looks like this issue should be fixed in v0.7.0, which is scheduled to come out end of this week / early next week.

You can also try using the Ludwig nightly image for now to unblock. Let me know if that addresses the issue.

**Comment by skunkwerk** [comment]
Oh awesome, I'm building my docker image off the nightly tag now, will let you know if the issue resolves.

**Comment by skunkwerk** [comment]
I can confirm there is no error with the nightly docker image, so we I will close this issue.  Thanks!

**Comment by tgaddair** [comment]
Thanks for verifying the fix!
