### ISSUE TITLE
auto_train shouldn't require horovod

### ISSUE THREAD

**Issue by skunkwerk** [ludwig-ai/ludwig#3161]
**Describe the bug**
Using the autoML feature in auto_train seems to require horovod, but it should be possible to leverage autoML on a single machine without requiring horovod (which is very difficult to install).  If this is indeed by design, it should be called out as a requirement in the auto_train documentation.

the error is:
ModuleNotFoundError: Horovod isn't installed. To install Horovod with PyTorch support, run 'pip install 'horovod[pytorch]''. To install Horovod with TensorFlow support, run 'pip install 'horovod[tensorflow]''.

**To Reproduce**
Sample code:

```
from ludwig.automl import auto_train
from ludwig.datasets import mushroom_edibility
from ludwig.utils.dataset_utils import get_repeatable_train_val_test_split

mushroom_df = mushroom_edibility.load()
mushroom_edibility_df = get_repeatable_train_val_test_split(mushroom_df, 'class', random_seed=42)

auto_train_results = auto_train(
    dataset=mushroom_edibility_df,
    target='class',
    time_limit_s=120,
    tune_for_memory=False,
    user_config={'preprocessing': {'split': {'column': 'split', 'type': 'fixed'}}},
)

pprint.pprint(auto_train_results)
```

**Expected behavior**
auto_train should run successfully on a machine without Horovod installed.

**Environment (please complete the following information):**

- OS: Linux
- Python version: 3.8
- Ludwig version: 0.7 installed via pip, along with dask, hummingbird-ml, and lightgbm

thanks

**Comment by tgaddair** [comment]
Hey @skunkwerk, thanks for the feature request! Yes, this should be pretty doable. We should be able to have a fix in the next day or so, and include it in v0.7.1.
