### ISSUE TITLE
specify cache_dir when running auto_train

### ISSUE THREAD

**Issue by skunkwerk** [ludwig-ai/ludwig#3281]
**Is your feature request related to a problem? Please describe.**
There doesn't seem to be a way to set a cache_dir when using auto_train.  auto_train calls create_auto_config (which does accept a 'backend' parameter), but there is no 'backend' parameter to auto_train itself.

**Describe the use case**
I'm trying to run ludwig on a polyaxon cluster, but my auto_train jobs are failing because my code is in a read-only folder, and ludwig's auto_train is failing because it tries to create a lock file in the same folder:

a call like this:

```
auto_train_results = auto_train(
            dataset=self.training_data,
            target=self.config.get('label'),
            time_limit_s=self.config.get('time_limit'),
            tune_for_memory=False,
            gpus='0'
        )
```

results in:
PermissionError: [Errno 13] Permission denied: '/code/.lock_preprocessing'

**Describe the solution you'd like**
auto_train should have an additional parameter for 'backend', that is passed through to the call to create_auto_config.
if you could also comment in this thread on how to specify a local backend with a cache_dir path from Python (instead of a YAML file), that would be great.

**Describe alternatives you've considered**
haven't considered any

**Comment by tgaddair** [comment]
Hey @skunkwerk, apologies for the late response!

In the `auto_train` function, we have an additional parameter `**kwargs` which allows you to provide any arguments you want that will be passed down to the hyperopt function [here](https://github.com/ludwig-ai/ludwig/blob/master/ludwig/hyperopt/run.py#L63), which includes the `backend` param.

So it should be possible to call `auto_train` like so:

```
auto_train_results = auto_train(
            dataset=self.training_data,
            target=self.config.get('label'),
            time_limit_s=self.config.get('time_limit'),
            tune_for_memory=False,
            gpus='0'
            backend=backend,
        )
```

Let me know if you run into issues with this and we'll prioritize getting it fixed.
