### ISSUE TITLE
TypeError: forward() got an unexpected keyword argument 'token_type_ids'

### ISSUE THREAD

**Issue by pushkarraj** [ludwig-ai/ludwig#3328]
I am trying to fine tune bloom using your examples but  getting thi error TypeError: forward() got an unexpected keyword argument 'token_type_ids'

**Comment by tgaddair** [comment]
Hi @pushkarraj, thanks for the reporting the issue. Looks like something changed in our `auto_transformer` that we didn't catch in our tests. I put together a fix in #3329, feel free to try it out and let us know how it goes. We can also push a patch release when this lands.

**Comment by pushkarraj** [comment]
Thanks for the help
