### ISSUE TITLE
AttributeError: 'BloomModel' object has no attribute 'n_head'

### ISSUE THREAD

**Issue by pushkarraj** [ludwig-ai/ludwig#3350]
while finetuning bloom using the latest repo  this is the error that I am getting . This is after my #3329 bug fix.

**Comment by tgaddair** [comment]
Hey @pushkarraj, apologies for the delay getting back to you. Do you have a minimal repro I can run for this error? I haven't been able to reproduce it locally.

**Comment by pushkarraj** [comment]
This is my repo : https://github.com/pushkarraj/LLMs_finetuning.git

I have  been using latest ludwig repo  to fine tune series of bloom models.  I am using the file cluster.yamal to build a GPU cluster  using 3 x g4dn.2xlarge instances. Then i am using ludwig api from the file "main1.py" to start the finetuning. I have also tried using command prompt to start the fine-tuning , there i am getting a different problem #3353.

**Comment by tgaddair** [comment]
Thanks! Based on the repo, did using the smaller `bloom-560m` work successfully?

**Comment by pushkarraj** [comment]
yes it did, but failed on bloom-1b1.

**Comment by tgaddair** [comment]
Hey @pushkarraj, sorry for the delay in getting back to you on this! A quick update from our side: we just landed the new DeepSpeed backend, which should offer even greater scalability to very large models. We've successfully run this with bloom-3b on a machine with 4 A10g GPUs using the example linked below:

https://github.com/ludwig-ai/ludwig/tree/master/examples/llm_finetuning

Please try it out and let us know how it goes!
