### ISSUE TITLE
Warning: reader on shard 0 of the pipeline has been blocked more than 10.0s waiting for other readers to catch up. All pipeline shards must be read from concurrently.

### ISSUE THREAD

**Issue by pushkarraj** [ludwig-ai/ludwig#3353]
This is my config file to fine tune bloom1b1 model for classification task.

____________

`input_features:
- name: title
  type: text
  encoder:
    type: auto_transformer
    pretrained_model_name_or_path: bigscience/bloom-1b1
    trainable: true
    pretrained_kwargs: null
output_features:
- name: class
  type: category
trainer:
  learning_rate: 1.0e-05
  epochs: 3
  batch_size: auto
  max_batch_size: 16
backend:
  type: ray
  cache_dir: s3://ludwigconfig/ludwig_config/
  processor:
    type: dask
    parallelism: 64
    persist: true
  trainer:
    strategy: fsdp
  loader:
    fully_executed: false
    window_size_bytes: 500000000
`

#ludwig train --config lu_config.yaml --dataset new.csv

I am stuck at :

_______
Warning: reader on shard 0 of the pipeline has been blocked more than 10.0s waiting for other readers to catch up. All pipeline shards must be read from concurrently.
________

This continuously  goes on in a loop for infinity.

**Comment by tgaddair** [comment]
Hey @pushkarraj, can you share your Ray cluster configuration as well? Looks like one or more of the workers is getting stuck somewhere. I'll try and reproduce this on our end tomorrow. Thanks.

**Comment by pushkarraj** [comment]
This is my repo with latest updates : https://github.com/pushkarraj/LLMs_finetuning

you might have to make a little changes in order to run on your cloud. I would love to get a detailed answer here. If possible i can connect as well.

**Comment by tgaddair** [comment]
Hmm, wasn't able to produce this issue with my setup. When this hanging occurs, what is the state of the Ray cluster you see when running `ray status`?
