### ISSUE TITLE
Bug: RuntimeError: Caught exception during model preprocessing: 'NoneType' object has no attribute 'IndexFlatL2'

### ISSUE THREAD

**Issue by chayanray** [ludwig-ai/ludwig#3427]
**Describe the bug**
I am trying to run the LLM_few-shot example (https://github.com/ludwig-ai/ludwig/blob/master/examples/llm_few_shot_learning/simple_model_training.py) on google colab and getting the following error in the training stage. 

`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/ludwig/api.py](https://localhost:8080/#) in preprocess(self, dataset, training_set, validation_set, test_set, training_set_metadata, data_format, skip_save_processed_input, random_seed, **kwargs)
   1488                 # TODO (Connor): Refactor to use self.config_obj
-> 1489                 preprocessed_data = preprocess_for_training(
   1490                     self.config_obj.to_dict(),

9 frames
[/usr/local/lib/python3.10/dist-packages/ludwig/data/preprocessing.py](https://localhost:8080/#) in preprocess_for_training(config, dataset, training_set, validation_set, test_set, training_set_metadata, data_format, skip_save_processed_input, preprocessing_params, backend, random_seed, callbacks)
   1971         else:
-> 1972             processed = data_format_processor.preprocess_for_training(
   1973                 config,

[/usr/local/lib/python3.10/dist-packages/ludwig/data/preprocessing.py](https://localhost:8080/#) in preprocess_for_training(config, features, dataset, training_set, validation_set, test_set, training_set_metadata, skip_save_processed_input, preprocessing_params, backend, random_seed, callbacks)
    252 
--> 253         return _preprocess_df_for_training(
    254             config,

[/usr/local/lib/python3.10/dist-packages/ludwig/data/preprocessing.py](https://localhost:8080/#) in _preprocess_df_for_training(config, features, dataset, training_set, validation_set, test_set, training_set_metadata, preprocessing_params, backend, random_seed, callbacks)
   2180 
-> 2181     data, training_set_metadata = build_dataset(
   2182         config,

[/usr/local/lib/python3.10/dist-packages/ludwig/data/preprocessing.py](https://localhost:8080/#) in build_dataset(config, dataset_df, features, global_preprocessing_parameters, mode, metadata, backend, random_seed, skip_save_processed_input, callbacks)
   1233     logger.debug("handle text features with prompt parameters")
-> 1234     synthesized_dataset_cols = handle_features_with_prompt_config(
   1235         config, dataset_df, features, split_col=split_col, backend=backend

[/usr/local/lib/python3.10/dist-packages/ludwig/data/preprocessing.py](https://localhost:8080/#) in handle_features_with_prompt_config(config, dataset_df, features, backend, split_col)
   1778             }
-> 1779             retrieval_model, index_name = index_column(
   1780                 prompt_config["retrieval"],

[/usr/local/lib/python3.10/dist-packages/ludwig/data/prompt.py](https://localhost:8080/#) in index_column(retrieval_config, col_name, dataset_cols, backend, split_col)
    111         # Build index if index name is not provided and index for this df does not already exist in cache
--> 112         retrieval_model.create_dataset_index(df, backend, columns_to_index=[col_name])
    113         logger.info(f"Saving index to cache directory '{index_cache_directory}' with name '{index_name}'")

[/usr/local/lib/python3.10/dist-packages/ludwig/models/retrieval.py](https://localhost:8080/#) in create_dataset_index(self, df, backend, columns_to_index)
    133         embeddings = self._encode(row_strs, backend)
--> 134         self.index = faiss.IndexFlatL2(embeddings.shape[1])
    135         self.index.add(embeddings)

AttributeError: 'NoneType' object has no attribute 'IndexFlatL2'

The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)
[<ipython-input-135-f12a42dc45d2>](https://localhost:8080/#) in <cell line: 6>()
      4     preprocessed_data,  # tuple Ludwig Dataset objects of pre-processed training data
      5     output_directory,  # location of training results stored on disk
----> 6 ) = model.train(
      7     dataset=df,experiment_name="simple_experiment", model_name="simple_model", skip_save_processed_input=True)
      8 

[/usr/local/lib/python3.10/dist-packages/ludwig/api.py](https://localhost:8080/#) in train(self, dataset, training_set, validation_set, test_set, training_set_metadata, data_format, experiment_name, model_name, model_resume_path, skip_save_training_description, skip_save_training_statistics, skip_save_model, skip_save_progress, skip_save_log, skip_save_processed_input, output_directory, random_seed, **kwargs)
    539                         )
    540 
--> 541                 preprocessed_data = self.preprocess(
    542                     dataset=dataset,
    543                     training_set=training_set,

[/usr/local/lib/python3.10/dist-packages/ludwig/api.py](https://localhost:8080/#) in preprocess(self, dataset, training_set, validation_set, test_set, training_set_metadata, data_format, skip_save_processed_input, random_seed, **kwargs)
   1506             return PreprocessedDataset(proc_training_set, proc_validation_set, proc_test_set, training_set_metadata)
   1507         except Exception as e:
-> 1508             raise RuntimeError(f"Caught exception during model preprocessing: {str(e)}") from e
   1509         finally:
   1510             for callback in self.callbacks:

RuntimeError: Caught exception during model preprocessing: 'NoneType' object has no attribute 'IndexFlatL2'`

**Expected behavior**
Should allow training with the dataset provided.

**Environment (please complete the following information):**

- OS: Colab
- Python version 3.10
- Ludwig version 0.8

**Additional context**
<img width="958" alt="image" src="https://github.com/ludwig-ai/ludwig/assets/29117565/9faafe75-7120-49a5-b815-6049b02034f0">

**Comment by geoffreyangus** [comment]
Hello @chayanray– Yes, it looks like you may have to download the `llm` subpackage for Ludwig. I see that you are on `0.8.dev`. If you therefore installed by git cloning the repository, you can do this by installing using 

```
pip install -e '.[llm]'
```

in your virtual environment. Let me know if that works, thanks!

**Comment by chayanray** [comment]
@geoffreyangus , thanks for the quick reply, but still getting the same error. I am attaching the notebook for reference.
[Ludwig_Few_Shot_Training.ipynb.zip](https://github.com/ludwig-ai/ludwig/files/11632335/Ludwig_Few_Shot_Training.ipynb.zip)

**Comment by tgaddair** [comment]
Hey @chayanray, my guess is that one of `faiss` or `sentence_transformers` isn't installed in your environment. We can improve the error messaging around this so it correctly tells you which package is missing, but can you try running this in your environment and let us know what it shows:

```
pip show faiss-cpu
pip show sentence-transformers
```

If either package is missing, try installing them directly:

```
pip install faiss-cpu sentence-transformers
```

**Comment by chayanray** [comment]
Hi @tgaddair, installing faiss-cpu seems to have solved the issue.  Thanks.

However even with training, it seems to have an accuracy of 0.33. Prediction has the default 'Neutral' everytime. What am I doing wrong here? It seems that training is not happening at all.

**Comment by tgaddair** [comment]
I'll let @geoffreyangus chime in to validate, but I believe the example script we put together is using a very small model for demo purposes that might be too small to do the task well (`facebook/opt-350m`). In our internal tests, we used much larger models, and specifically an instruction tuned model.

For example, I would suggest changing the `model_name` to something larger like `tiiuae/falcon-7b`, which should be able to fit in memory on a single GPU when performing inference.
