### ISSUE TITLE
Image Classification: Config

### ISSUE THREAD

**Issue by AnaMiguelRodrigues1** [ludwig-ai/ludwig#3462]
The Config. 
![image](https://github.com/ludwig-ai/ludwig/assets/121572477/a525510f-9603-4812-bdeb-ffcb3b3d88f4)
It starts a syntax error, it should actually be: 
  config = {
  'input_features': [
    {
      'name': 'image_path',
      'type': 'image',
      'preprocessing': {'num_processes': 4},
      'encoder': 'stacked_cnn',
      'conv_layers': [
        {'num_filters': 32, 'filter_size': 3, 'pool_size': 2, 'pool_stride': 2},
        {'num_filters': 64, 'filter_size': 3, 'pool_size': 2, 'pool_stride': 2, 'dropout': 0.4}
      ],
     'fc_layers': [{'output_size': 128, 'dropout': 0.4}]
    }
    ],
    'output_features': [{'name': 'label', 'type': 'binary'}],
    'trainer': {'epochs': 5}
    }

**Comment by arnavgarg1** [comment]
Hi @AnaMiguelRodrigues1, thanks for filing this issue and a proposed fix!

I just wanted to understand a few things:

1. What version of Ludwig are you running?
2. What is the error that you're seeing?

**Comment by AnaMiguelRodrigues1** [comment]
I using the most recent version, ludwig==0.8.dev0.
The error is syntax error, it's just the 'encoder' field is not defined correctly within the config.

**Comment by arnavgarg1** [comment]
Got it! Would you like to contribute the fix to Ludwig?

**Comment by AnaMiguelRodrigues1** [comment]
I would love to correct it, but in the official page of Ludwig ( https://ludwig.ai/latest/examples/mnist/ ), i do not have permissions to change the website and correct config.
