### ISSUE TITLE
Missing documentation for Ludwig Explainer

### ISSUE THREAD

**Issue by Exitare** [ludwig-ai/ludwig#3465]
**Is your feature request related to a problem? Please describe.**
There seems to be no documentation at all about the [explainer class](https://github.com/ludwig-ai/ludwig/blob/master/ludwig/explain/explainer.py) on the [official homepage](https://ludwig.ai/latest/). 
Without the documentation it is difficult to understand how to use the explainer in the correct and intended way. 
I got it to work, however, the explained attributes of the model do not make any sense at all and are even the same for two different models. 
I cannot use shap to get feature importances/attributes, because the Ludwig predict function returns a tuple which is not accepted by shap, so I have to rely on the explainer provided by Ludwig.

**Describe the use case**
The documentation should describe how to use the built-in explainer of Ludwig, provide use cases and examples.

**Describe the solution you'd like**
A dedicated page describing the explainer on the official homepage.

**Comment by connor-mccorm** [comment]
Hello @Exitare, I will be working on creating docs for the explainer class this week. Will keep you posted on my progress as I work through this!

**Comment by Exitare** [comment]
Thank you so much! If you need any help, please let me know! Thanks for the support!

**Comment by connor-mccorm** [comment]
Hi @Exitare just wanted to let you know that this is still on my radar! Apologies for the delay, have had a lot of things come up this past week but will try and get to this ASAP.

**Comment by Exitare** [comment]
Thanks for the update :)

**Comment by connor-mccorm** [comment]
Hi @Exitare, apologies for the delay here. Unfortunately I've been swamped with other priorities. I had a conversation internally and given that the feature is currently in an experimental API state as indicated by https://github.com/ludwig-ai/ludwig/blob/1b0774fd12d627bd8f4c7e7d4008795e517e6d68/ludwig/explain/gbm.py#L9C37-L9C37 and https://github.com/ludwig-ai/ludwig/blob/1b0774fd12d627bd8f4c7e7d4008795e517e6d68/ludwig/explain/captum.py#L153C37-L153C37, we actually are not able to put together comprehensive docs together on this until it's at least in a beta supported state. If you have specific questions about your implementation or the results you are getting from the explainer, I am happy to answer those to help you achieve your goals.
