### ISSUE TITLE
Bug in the Tutorial of Tabular Data Classification

### ISSUE THREAD

**Issue by haoyuejudy** [ludwig-ai/ludwig#3482]
Dear, 

When I try to run codes of Tabular Data Classification using Colab, I find that I cannot train the model in the Train the Model part. The error message is as follows. What could be the reason for this?

ValueError: Unexpected keyword arguments: `confidence_penalty`, `positive_class_weight`, `robust_lambda`

**Comment by jeffkinnison** [comment]
Hi @haoyuejudy, Thanks for bringing this to our attention! I'm looking into this now and will let you know when it's resolved.

**Comment by jandolezal** [comment]
Started exploring `ludwig` today (its really great!) and faced similar issue. `pip install torchmetrics==0.11.4` fixed this issue for me.
