### ISSUE TITLE
Testing new llm feature with mosaicml/mpt-7b-8k, bigscience/bloomz-3b and openlm-research/open_llama_3b_v2

### ISSUE THREAD

**Issue by fire** [ludwig-ai/ludwig#3485]
**Describe the bug**
I want to test the various llms with ludwig.

**To Reproduce**

1. `git clone https://github.com/V-Sekai-fire/itch.io-Scrapy-Project`
1. `pip install -r requirements_local.txt`
2. `cd recommend`
3. `python3 recommend.py`
1. Unable to train.
1. See error.

PEFT failed for many of them. Without PEFT, the gpu memory card overflows.

For mpt there's a requirement to override security evaluation.

Note that the extremely low sample rates are for testing.

**Expected behavior**

I expect to be able to train and inference on the new models. The example given in the llama colab is not opensource. The model requires a HF token and agreement to Meta Inc terms.

**Screenshots**

**Environment (please complete the following information):**

- OS: wsl on windows
- Version 10
- Python version Python 3.10.6
- Ludwig version git+https://github.com/ludwig-ai/ludwig.git#egg=ludwig[llm]

**Additional context**

**Comment by fire** [comment]
Some logs: 

```bash
==================================================
Trainable Parameter Summary For Fine-Tuning
Fine-tuning with adapter: lora
trainable params: 2,457,600 || all params: 1,825,367,040 || trainable%: 0.1346359360142714
==================================================
Traceback (most recent call last):
  File "/mnt/c/Users/fire/Desktop/itch.io-Scrapy-Project/recommend/recommend.py", line 90, in <module>
    train_stats = model.train(dataset="items_games_5.csv") # trust_remote_code=True
  File "/home/fire/.local/lib/python3.10/site-packages/ludwig/api.py", line 604, in train
    with self.backend.create_trainer(
  File "/home/fire/.local/lib/python3.10/site-packages/ludwig/backend/base.py", line 199, in create_trainer
    return trainer_cls(config=config, model=model, **kwargs)
  File "/home/fire/.local/lib/python3.10/site-packages/ludwig/trainers/trainer_llm.py", line 401, in __init__
    super().__init__(
  File "/home/fire/.local/lib/python3.10/site-packages/ludwig/trainers/trainer.py", line 179, in __init__
    self.model = self.distributed.to_device(self.model)
  File "/home/fire/.local/lib/python3.10/site-packages/ludwig/distributed/base.py", line 50, in to_device
    return model.to_device(device if device is not None else get_torch_device())
  File "/home/fire/.local/lib/python3.10/site-packages/ludwig/models/llm.py", line 252, in to_device
    self.model = PeftModel.from_pretrained(
TypeError: PeftModel.from_pretrained() missing 1 required positional argument: 'model_id'
```

**Comment by tgaddair** [comment]
Hey @fire, thanks for trying out the new LLM fine-tuning! I ran your script on a t4 GPU (g4dn.4xlarge instance in AWS) without any issues. What GPU are you using in your tests?

It looks like the issue here may be due to dependency versions. Can you share your versions of:

- `transformers`
- `peft`
- `bitsandbytes`

Thanks.

**Comment by fire** [comment]
It may be required to use git+https://github.com/huggingface/peft and `peft-0.5.0.dev0`

**Comment by fire** [comment]
Still erroring on `TypeError: PeftModel.from_pretrained() missing 1 required positional argument: 'model_id'`.

**Comment by fire** [comment]
Requirement already satisfied: transformers in /home/fire/.local/lib/python3.10/site-packages (4.31.0)

Requirement already satisfied: bitsandbytes in /home/fire/.local/lib/python3.10/site-packages (0.40.2)

**Comment by fire** [comment]
```
                if self.config_obj.adapter:
                    from peft import PeftModel

                    self.model = AutoModelForCausalLM.from_pretrained(
                        self.model_name,
                        **model_kwargs,
                    )
                    self.model = PeftModel.from_pretrained(
                        tmpdir,
                        torch_dtype=torch.float16,
                    )
```

Removing does something.

```
                    self.model = PeftModel.from_pretrained(
                        tmpdir,
                        torch_dtype=torch.float16,
                    )
```

**Comment by fire** [comment]
I wasn't able to get the model inferencing, but maybe the LLM isn't able to solve this problem with the data provided theoretically.

Hope this was useful for other people.

**Comment by tgaddair** [comment]
Hey @fire, I think I see the issue. I'm guessing your machine has more than one GPU? It looks like there was a bug with this code path that should be fixed in https://github.com/ludwig-ai/ludwig/pull/3478.

**Comment by tgaddair** [comment]
https://github.com/ludwig-ai/ludwig/pull/3486 should also allow you to use multiple GPUs for quantized training, which should allow you to use larger models / batch sizes.
