### ISSUE TITLE
Model weights are not getting creating after training completes

### ISSUE THREAD

**Issue by SumanthDatta-Kony** [ludwig-ai/ludwig#3551]
[ludwig_0_8_error.zip](https://github.com/ludwig-ai/ludwig/files/12453797/ludwig_0_8_error.zip)
In Ludwig 0.8.x , post training the model weights are not seen in teh results/experimentname/model folder. This is reproducible with ray cluster (head+worker) setup.  Training completes successfully . But model weights file is not found.

After training completes we see this error as well, but there is no impact on the training i think. Not sure if  thsi is the actual root cause.

**Executing DAG InputDataBuffer[Input] -> TaskPoolMapOperator[MapBatches(<lambda>)]
2023-08-25 10:10:52,094	ERROR checkpoint_manager.py:170 -- The requested checkpoint is not available on this node, most likely because you are using Ray client or disabled checkpoint synchronization. To avoid this, 
enable checkpoint synchronization to cloud storage by specifying a `SyncConfig`. The checkpoint may be available on a different  node - 
please check this location on worker nodes: /root/ray_results/TorchTrainer_2023-08-25_10-08-06/TorchTrainer_4940a_00000_0_2023-08-25_10-08-06/checkpoint_000000
Traceback (most recent call last):
  File "trip_fare.py", line 32, in <module>
    results = model.train(df, None, None, None, None, None,
  File "/opt/foresight_venv/lib/python3.8/site-packages/ludwig/api.py", line 636, in train
    train_stats = trainer.train(
  File "/opt/foresight_venv/lib/python3.8/site-packages/ludwig/backend/ray.py", line 521, in train
    ckpt = TorchCheckpoint.from_checkpoint(trainer_results.checkpoint)
  File "/opt/foresight_venv/lib/python3.8/site-packages/ray/air/checkpoint.py", line 447, in from_checkpoint
    local_path=other._local_path,
AttributeError: 'NoneType' object has no attribute '_local_path'**

Please find the attached zip file , extarct the zip file , run trip_fare2.py , ray cluster environment is a must.

**Comment by tgaddair** [comment]
Hey @SumanthDatta-Kony, can you confirm the version of Ray you're using?

**Comment by SumanthDatta-Kony** [comment]
ray 2.3.0

**Comment by Infernaught** [comment]
Hi @SumanthDatta-Kony. Is trip_fare2.py the same script that generated the error? I'm noticing a discrepancy with the line numbers in the file and the line number in your error message. I'm also hitting a separate error due to mixed dtypes in the trip_fare.csv file (specifically for the "pickup_zipcode" and "dropoff_zipcode" columns).

**Comment by Infernaught** [comment]
@SumanthDatta-Kony Do you know how your ray cluster environment is set up? I'm having a bit of difficulty reproducing your error. If you could please post more of the stack trace, that would be great.

**Comment by SumanthDatta-Kony** [comment]
yes trip_fare2.py script generated the error.  My ray environment is a cluster with head node and worker node . The results are published to the mlflow later.

**Comment by SumanthDatta-Kony** [comment]
Model weights file is getting created at the end of training, Ludwig training uses ray for distributed training,  ludwig  acts as a ray client , ray client  is giving an exception at the end of training .
