### ISSUE TITLE
ludwig_llama2_7b_finetuning_4bit.ipynb crashes

### ISSUE THREAD

**Issue by silvacarl2** [ludwig-ai/ludwig#3563]
Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/ludwig/api.py](https://localhost:8080/#) in preprocess(self, dataset, training_set, validation_set, test_set, training_set_metadata, data_format, skip_save_processed_input, random_seed, **kwargs)
   1490                 # TODO (Connor): Refactor to use self.config_obj
-> 1491                 preprocessed_data = preprocess_for_training(
   1492                     self.config_obj.to_dict(),

21 frames
UnboundLocalError: local variable 'tokens' referenced before assignment

The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/ludwig/api.py](https://localhost:8080/#) in preprocess(self, dataset, training_set, validation_set, test_set, training_set_metadata, data_format, skip_save_processed_input, random_seed, **kwargs)
   1508             return PreprocessedDataset(proc_training_set, proc_validation_set, proc_test_set, training_set_metadata)
   1509         except Exception as e:
-> 1510             raise RuntimeError(f"Caught exception during model preprocessing: {str(e)}") from e
   1511         finally:
   1512             for callback in self.callbacks:

RuntimeError: Caught exception during model preprocessing: local variable 'tokens' referenced before assignment

any ideas?

**Comment by arnavgarg1** [comment]
> RuntimeError: Caught exception during model preprocessing: local variable 'tokens' referenced before assignment

What version of `transformers` are you on?

**Comment by silvacarl2** [comment]
at the top of the sample google colab it says this:

!pip uninstall -y tensorflow --quiet
!pip install "ludwig[llm]" --quiet

should i load instead latest transformers?

**Comment by silvacarl2** [comment]
ok, thx, this works: pip install git+https://github.com/huggingface/transformers@main
