### ISSUE TITLE
local variable 'tokens' referenced before assignment

### ISSUE THREAD

**Issue by randy-tsukemen** [ludwig-ai/ludwig#3568]
**Describe the bug**
LLM finetuning tutorial notebook failed.

**To Reproduce**

1. Open [ludwig_llama2_7b_finetuning_4bit.ipynb](https://colab.research.google.com/drive/1c3AO8l_H6V_x37RwQ8V7M6A-RmcBf2tG?usp=sharing)
2. Replace the huggingface tokens
3. Run all notebook cell
4. See error `RuntimeError: Caught exception during model preprocessing: local variable 'tokens' referenced before assignment`

**Expected behavior**
Notebook shouldn't fail.

**Screenshots**
![圖片](https://github.com/ludwig-ai/ludwig/assets/25134035/50b5eb33-4e42-4b66-923e-fa1a5e4446ce)
**Environment (please complete the following information):**

- OS: google colab

**Comment by arnavgarg1** [comment]
Thanks for flagging this issue @randy-tsukemen. Could you give this branch a try? https://github.com/ludwig-ai/ludwig/pull/3569
It downgrades the transformers package version to `4.31.0`.
