### ISSUE TITLE
Changes made for clarity and brevity

### ISSUE THREAD

**Issue by DonMiller9294** [ludwig-ai/ludwig#3573]
#if PY_VERSION_HEX >= 0x03090000  // New in Python 3.9
inline PyFrameObject* PyThreadState_GetFrame(PyThreadState* threadState) {
   if (threadState && threadState->frame && Py_REFCNT(threadState->frame) > 0) {
     Py_XINCREF(threadState->frame);
     return threadState->frame;
   }
   return nullptr;
}

Hey i hope you are well, I switched the condition in the #if directive to check for Python 3.9 and newer. This makes the code inside the function the default behavior and reduces indentation. The null pointer checks are combined in the if statement. This improves readability and reduces redundancy. I also used Py_REFCNT(threadState->frame) to check the reference count directly. This makes the code more concise and readable.

**Comment by tgaddair** [comment]
Hi @DonMiller9294, was this meant to be a PR?

**Comment by DonMiller9294** [comment]
Yes my mistake.

**Comment by tgaddair** [comment]
No worries! Will go ahead and close this issue, then.
