### ISSUE TITLE
Load LORA adapter for inference

### ISSUE THREAD

**Issue by kv-gits** [ludwig-ai/ludwig#3589]
It is possible to train model with lora and build adapter. But I did not find in docs how to load and apply adapter to base model for inference. Is it possible? If not, is this planned?

**Comment by tgaddair** [comment]
Thanks for raising the issue @kv-gits! This should be fixed by https://github.com/ludwig-ai/ludwig/pull/3572, is that right @Infernaught ?

**Comment by Infernaught** [comment]
Yes, that PR is the one that should address pretrained lora weight loading. I'm waiting on some last bits of feedback for that PR before we land it, but if you want to try it @kv-gits, here's the branch the changes were made on: [https://github.com/ludwig-ai/ludwig/tree/pretrained_adapter_weights](https://github.com/ludwig-ai/ludwig/tree/pretrained_adapter_weights)

**Comment by arnavgarg1** [comment]
Hi @kv-gits - I wanted to follow up and see if you were able to try Ludwig 0.8.6 and see if your issue was resolved?
