### ISSUE TITLE
microsoft/phi-1_5

### ISSUE THREAD

**Issue by TashaSkyUp** [ludwig-ai/ludwig#3630]
**Is your feature request related to a problem? Please describe.**
seems passing trust_remote_code = True does not work.

**Describe the use case**
would really love to use this with 
microsoft/phi-1_5

**Describe the solution you'd like**
replacing  lama 7b wiht microsoft/phi-1_5 in the readme example to work.

**Describe alternatives you've considered**

**Additional context**
Just trying to use the example in the readme and notebook but with  microsoft/phi-1_5

**Comment by arnavgarg1** [comment]
Hi @TashaSkyUp, thanks for flagging this issue. 

Let me create a patch fix for this in the next few hours! I will respond back once I create a fix so you can give it a try.

**Comment by arnavgarg1** [comment]
Hi @TashaSkyUp, quick update - I've started working on some code to support these kinds of models that require custom code: https://github.com/ludwig-ai/ludwig/pull/3632

I will continue working on it today and will let you know when you can try using it from my branch. Once this is ready, it should be as easy as passing in:

```yaml
model_parameters:
    trust_remote_code: true
```

to your Ludwig config

**Comment by TashaSkyUp** [comment]
Thank you very much @arnavgarg1. I'm looking forward to the patch!

**Comment by sebastianschramm** [comment]
Also interested in a fix that makes phi-1_5 work.

**Comment by arnavgarg1** [comment]
Great to hear there is so much interest - I will try and get this working in the next 24 to 48 hours. Stay tuned and I appreciate your patience as I add support for them!

**Comment by arnavgarg1** [comment]
Hey @TashaSkyUp and @sebastianschramm! I finally have a PR up to support Phi-1 and Phi-1.5 specifically with Ludwig: https://github.com/ludwig-ai/ludwig/pull/3831
