### ISSUE TITLE
Unable to finetune a GPTQ model

### ISSUE THREAD

**Issue by mani1491** [ludwig-ai/ludwig#3652]
**Describe the bug**
I am trying to finetune an already quantized model (GPTQ) using ludwig but have been running into the following error:
AttributeError: 'BitsAndBytesConfig' object has no attribute 'get_loading_attributes'

**To Reproduce**
import yaml

config_str = """
model_type: llm
base_model: TheBloke/Llama-2-13B-GPTQ

quantization:
  bits: 4

adapter:
  type: lora

generation:
  temperature: 0.1
  max_new_tokens: 256

prompt:
  template: |
    ### Instruction:
    {instruction}

    ### Input:
    {input}

    ### Response:

input_features:
  - name: prompt
    type: text
    preprocessing:
      max_sequence_length: 256

output_features:
  - name: output
    type: text
    preprocessing:
      max_sequence_length: 256

trainer:
  type: finetune
  learning_rate: 0.0001
  batch_size: 2
  gradient_accumulation_steps: 3
  epochs: 15
  learning_rate_scheduler:
    warmup_fraction: 0.01

preprocessing:
  global_max_sequence_length: 512
  split_probabilities: [0.9,0.1, 0.0]
  sample_ratio: 1
"""

config = yaml.safe_load(config_str)

import logging
from ludwig.api import LudwigModel
model = LudwigModel(config=config, logging_level=logging.INFO)

results = model.train(dataset=df)

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**

- OS: \[e.g. iOS\]
- Version \[e.g. 22\]
- Python version
- Ludwig version

**Additional context**

**Comment by arnavgarg1** [comment]
Hi @mani1491, thanks for flagging this issue. 

May I know what version of Ludwig you're currently running?

It would also be great if you can tell me the package versions for `transformers` and `bitsandbytes` that you're currently running as well.

**Comment by mani1491** [comment]
Hi @arnavgarg1, here are the versions:
ludwig 0.8.4
transformers: 4.33.2
bitsandbytes: 0.40.2

**Comment by tgaddair** [comment]
To the best of my knowledge, we don't yet support fine-tuning a GPTQ model. It is possible, but would just need a little work from our side to enable it.

**Comment by mani1491** [comment]
@tgaddair Thanks for the reply. If GPTQ models are not supported at the moment, is there any way to finetune(with ludwig qlora) a llama-2 7B  on a free google colab instance(15GB GPU)? The notebook is running out of memory even for a small dataset.

**Comment by Titanssword** [comment]
> @tgaddair Thanks for the reply. If GPTQ models are not supported at the moment, is there any way to finetune(with ludwig qlora) a llama-2 7B on a free google colab instance(15GB GPU)? The notebook is running out of memory even for a small dataset. If that is not expected, I want to know if I am missing anything.

I followed this instruction [https://ludwig.ai/latest/getting_started/llm_finetuning/](https://ludwig.ai/latest/getting_started/llm_finetuning/) ，Using the colab and change the runtime into T4 GPU, it works.

**Comment by Titanssword** [comment]
> To the best of my knowledge, we don't yet support fine-tuning a GPTQ model. It is possible, but would just need a little work from our side to enable it.

Hi, I'd like to work on this and contribute to this project, can you provide some guidance?
