### ISSUE TITLE
Export computer-vision model to CoreML

### ISSUE THREAD

**Issue by saad-palapa** [ludwig-ai/ludwig#3660]
**Is your feature request related to a problem? Please describe.**
I would like to be able to export computer-vision models to CoreML that runs on Apple devices.

By using CoreML, we can run models on an Apple silicon's CPU, GPU, and Neural Engine. This enables us to run things in the most performant way on Apple devices.

**Describe the use case**
[CoreML](https://onnx.ai/) is a format that would be an addition to torchscript. It runs in all Apple devices.

**Describe the solution you'd like**
I would like to create CoreML as an option when exporting. We should offer quantization options.

**Describe alternatives you've considered**
There is another [feature request](https://github.com/ludwig-ai/ludwig/issues/3659) for ONNX that is similar to this feature request.

ONNX works on iOS, but is not the most preformat way to run models on Apple devices.

**Additional context**
Join our slack channel: `#computer-vision`

**Comment by tgaddair** [comment]
Thanks for looking into this @skanjila !
