### ISSUE TITLE
when using another llm like gpt2 it returns ValueError: If `eos_token_id` is defined, make sure that `pad_token_id` is defined.

### ISSUE THREAD

**Issue by mohammad-gh009** [ludwig-ai/ludwig#3661]
**Describe the bug**
when I want to use another llm(for example gpt2) it returns the following error:
ValueError: If `eos_token_id` is defined, make sure that `pad_token_id` is defined.

**To Reproduce**

1. Go to (https://colab.research.google.com/drive/1Ly01S--kUwkKQalE-75skalp-ftwl0fE?usp=sharing)
2. set up gpt2 as llm
3. go to <Perform Inference> section
4. and run the code it will produce the above error

Please provide code, yaml config file and a sample of data in order to entirely reproduce the issue.
Issues that are not reproducible will be ignored.

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
I used Colab T4 and the latest Ludwig version
- OS: \[e.g. iOS\]
- Version \[e.g. 22\]
- Python version
- Ludwig version

**Additional context**

**Comment by Infernaught** [comment]
This is the PR: https://github.com/ludwig-ai/ludwig/pull/3667. Waiting on another to be merged before merging this one.
