### ISSUE TITLE
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument mat1 in method wrapper...

### ISSUE THREAD

**Issue by karanjakhar** [ludwig-ai/ludwig#3681]
**Describe the bug**
I followed the steps from "how to contribute" and setting up Lugwig locally for development. When I run pytest I get 
![Screenshot from 2023-09-30 13-15-33](https://github.com/ludwig-ai/ludwig/assets/29913676/476bb267-bdbd-4e7b-bac6-e21366e79a85)

**Environment (please complete the following information):**

- OS: Ubuntu
- Version: 20.04
- Python version: 3.10
- Ludwig version: 0.8

**Comment by tgaddair** [comment]
Hey @karanjakhar, some of the tests have known issues when running on GPU. We have a PR in progress to fix these tests:

https://github.com/ludwig-ai/ludwig/pull/3578

As a temporary workaround, can you try running these tests on CPU? It should work to do something like:

```
CUDA_VISIBLE_DEVICES="" pytest ...
```

cc @jeffkinnison

**Comment by karanjakhar** [comment]
Most of these are solved with your suggestion. But I am getting this now:
![Screenshot from 2023-10-01 14-29-21](https://github.com/ludwig-ai/ludwig/assets/29913676/9cf7d082-050f-4b8f-8220-1c7fa1dbae0b)
