### ISSUE TITLE
llama2_7b_finetuning_4bit example: `LudwigModel.create_model(self.config_obj, random_seed=random_seed)` hangs

### ISSUE THREAD

**Issue by DavidFarago** [ludwig-ai/ludwig#3682]
**Describe the bug**
When calling `python train_alpaca.py` or `./run_train.sh` from the llama2_7b_finetuning_4bit example, there is no output after `Downloading shards: 100%` for >1 hour, and no GPU utilization.

**To Reproduce**
* start a 1 x A100 80GB machine (I did this on runpod).
* install conda 4.12.0, create and activate a Python 3.10 virtual env 
* continue with the steps described in the readme of https://github.com/ludwig-ai/ludwig/tree/master/examples/llama2_7b_finetuning_4bit
* both `python train_alpaca.py` and `./run_train.sh` hand at the same place (see "screenshots" below).

**Expected behavior**
The model continues after "Downloading shards:", instead of hanging there for >1h without any output and without runpod showing me any GPU utilization.

**Screenshots**
```
Warnings and other logs:
> /workspace/anaconda3/envs/ludwig310/lib/python3.10/site-packages/ludwig/api.py(595)train()
-> self.model = LudwigModel.create_model(self.config_obj, random_seed=random_seed)
(Pdb) n
Loading large language model...
Downloading (…)fetensors.index.json: 100%|█████████████████| 26.8k/26.8k [00:00<00:00, 50.3MB/s]
Downloading (…)of-00002.safetensors: 100%|██████████████████| 9.98G/9.98G [00:54<00:00, 184MB/s]
Downloading (…)of-00002.safetensors: 100%|██████████████████| 3.50G/3.50G [00:19<00:00, 181MB/s]
Downloading shards: 100%|█████████████████████████████████████████| 2/2 [01:13<00:00, 36.92s/it]
```

**Environment (please complete the following information):**

- OS: Ubuntu
- Version 22.04.2 LTS
details (lsb_release -a):
  * No LSB modules are available.
  * Release:	22.04
- Python version: 3.10.13 via conda 
- Ludwig version: ludwig                    0.8.4                    pypi_0    pypi

**Comment by justinxzhao** [comment]
Hi @DavidFarago,

While it can take a while for the downloaded model to load into tensors on GPU, >1 hour is far too long. To eliminate the possibility that it's HF downtime, could you double check the script and try re-running again in a clean `runpod`?

I'm not experiencing hanging in either the Colab notebook's T4 https://colab.research.google.com/drive/1c3AO8l_H6V_x37RwQ8V7M6A-RmcBf2tG?usp=sharing#scrollTo=JfZq1-qbulcg or my own GPU environment.

It could also be worth reaching out to the `runpod` folks to see if they have any suggestions on their side.

**Comment by DavidFarago** [comment]
Thanks for the fast reply. 

I started with another clean A100 runpod, and made the following changes:
* conda env with Python 3.9 instead of 3.10
* `pip install ludwig[full]` instead of `pip install ludwig; pip install ludwig[llm]`

Now it is working.

**Comment by arnavgarg1** [comment]
Hey @DavidFarago - is this safe to mark as resolved?

**Comment by DavidFarago** [comment]
Yes, this never occurred again, while runpod (monitoring) was fishy in several other situations. So I am pretty sure this problem was caused by runpod, not ludwig.
