### ISSUE TITLE
ImportError: Using `load_in_8bit=True` requires Accelerate: `pip install accelerate` and the latest version of bitsandbytes `pip install -i https://test.pypi.org/simple/ bitsandbytes` or pip install bitsandbytes` 

### ISSUE THREAD

**Issue by NishaDeepak** [ludwig-ai/ludwig#3695]
The following error arises while training the model:

ImportError: Using `load_in_8bit=True` requires Accelerate: `pip install accelerate` and the latest version of bitsandbytes `pip install -i https://test.pypi.org/simple/ bitsandbytes` or pip install bitsandbytes` 

The code is as follows:

!pip install ludwig
!pip install ludwig[llm]

import yaml
from ludwig.api import LudwigModel
import logging

qlora_fine_tuning_config = yaml.safe_load(
"""
model_type: llm
base_model: tiiuae/falcon-7b-instruct

input_features:
  - name: instruction
    type: text

output_features:
  - name: output
    type: text

prompt:
  template: >-
    Below is an instruction that describes a task, paired with an input
    that provides further context. Write a response that appropriately
    completes the request.

    ### Instruction: {instruction}

    ### Input: {input}

    ### Response:

generation:
  temperature: 0.1
  max_new_tokens: 512

adapter:
  type: lora

quantization:
  bits: 4

preprocessing:
  global_max_sequence_length: 512
  split:
    type: random
    probabilities:
    - 1
    - 0
    - 0
  eos_token_id: eos_token
  pad_token_id: pad_token

trainer:
  type: finetune
  epochs: 5
  batch_size: 1
  eval_batch_size: 2
  gradient_accumulation_steps: 16
  learning_rate: 0.0004
  learning_rate_scheduler:
    warmup_fraction: 0.03
"""
)

model = LudwigModel(config=qlora_fine_tuning_config, logging_level=logging.INFO)
results = model.train(dataset=df)

The error mentioned above arises in this particular step.

The model was expected to get trained but unable to do so.

**Environment (please complete the following information):**

- OS: Windows 11
- Version 22H2
- Python 3.10
- Ludwig 0.8.4

Please find the attached dataset and yaml file
[LUDWIG dataset and yaml.zip](https://github.com/ludwig-ai/ludwig/files/12830568/LUDWIG.dataset.and.yaml.zip)

**Comment by Infernaught** [comment]
Hi @NishaDeepak. Are you running this locally on a CPU?

This error generally occurs during quantized fine-tuning when done in an environment without a GPU. Have you tried running this in Google Colab with a T4 GPU runtime?

**Comment by NishaDeepak** [comment]
Thank you @Infernaught. The above mentioned issue is resolved after running it in a T4 GPU runtime.
