### ISSUE TITLE
TPU support?

### ISSUE THREAD

**Issue by minimaxir** [ludwig-ai/ludwig#37]
Since Ludwig is running on TensorFlow, it can run on a TPU, which can be useful especially combined with the free TPU provided by [Colaboratory](https://colab.research.google.com/).

Is there a way to provide the appropriate TPU-connector URL to a Ludwig model? (for both training and inference).

**Comment by w4nderlust** [comment]
I've never used TPUs my self yet, but looking at [this colab](https://colab.research.google.com/notebooks/tpu.ipynb), it seems pretty straightforward to add an argument to specify a TPU address.
Any takers? :)

**Comment by sam-qordoba** [comment]
@w4nderlust finding the TPU doesn't seem too bad, but will all the different model options automatically use the TPU?

**Comment by w4nderlust** [comment]
What do you mean by "finding the TPU"?
There's nothing CPU or GPU specific in the models (a part from the option to force loaging of pretrained embeddings on CPU), so in theory everything should work fine directly on the TPU too.

If there are tf operations that are used by a model that are not implemented on the TPU (I'm not aware of any, but haven't tested so can't be sure), then that specific model would not be trained on the TPU, but that would be the case if you implemented in TF by hand, so there's really nothing I can do about it a part from hoping the TF team implements them.
