### ISSUE TITLE
wandb get stuck in running and finally lead to OOM

### ISSUE THREAD

**Issue by MarselScheer** [ludwig-ai/ludwig#3701]
**Describe the bug**
When I use --wandb training completes but the wandb-run get stuck in running-state (and the console also is blocked) and finally the machine crashes due to OOM.

**To Reproduce**

Config:

```
input_features:
    - name: age
      type: number
output_features:
    - name: income
      type: binary
```

```
docker run --gpus all -i -t --rm ludwigai/ludwig-ray-gpu:0.8.4 /bin/bash
pip install wandb==0.15.12  (which is the latest version at the moment)
# provide wandb-creds
ludwig train --config ludwig.yaml --dataset ludwig://adult_census_income --random_seed 1 --wandb
```

Also tried `pip install wandb==0.12.10`  (tried this version because of  https://github.com/ludwig-ai/ludwig/blob/ccd8d82459bee7a30aa5aa2256897a69bfc37445/requirements_test.txt#L6)

**Expected behavior**

- wandb-run reaches the finished-state (and then the console is not blocked anymore)
- RAM is freed 

**Screenshots**
```
╒══════════╕
│ FINISHED │
╘══════════╛

wandb: Waiting for W&B process to finish... (success).
```

But it does not finishes and while waiting it keeps consuming more and more memory till the machine crashes (each dot is one second)
![image](https://github.com/ludwig-ai/ludwig/assets/8074083/1037c678-1394-4386-825d-8d2ace4498dd)

Note, that even when I use CTRL-C to abort the execution, more and more RAM gets allocated, so I have to actually leave the docker-container!

**Environment (please complete the following information):**

- ludwigai/ludwig-ray-gpu:0.8.4
- wandb==0.15.12/0.12.10

**Comment by MarselScheer** [comment]
Using the PythonAPI would lead to the same behaviour. However, one can explicitly call wandb.init() and wandb.finish() as follows

```
import logging
import wandb
from ludwig.contribs.wandb import WandbCallback
from ludwig.datasets import adult_census_income
from ludwig.api import LudwigModel

config = {
    "input_features": [
        {
            "name": "age",
            "type": "number",
        }
    ],
    "output_features": [
        {
            "name": "income",
            "type": "category",
        }
    ],
}

wandb.init(project="experiment") 
m = LudwigModel(config=config, callbacks=[WandbCallback()], logging_level=logging.INFO)
m.experiment(
    dataset=adult_census_income.load(),
    random_seed=1,
)
wandb.finish()
```

and then it works.

**Comment by justinxzhao** [comment]
Hi @MarselScheer,

Thank you for reporting your experience using wandb on Ludwig.

I'm not very familiar with the wandb integration, but I have noticed that the `wandb.finish()` is missing from the implementation of the wandb callback. Perhaps that's what explains why you didn't encounter an OOM in your second setup.

**Comment by justinxzhao** [comment]
Could you try patching https://github.com/ludwig-ai/ludwig/pull/3710 to see if you observe the same OOM in your first setup?

**Comment by MarselScheer** [comment]
At first I thought it solves the problem, because the first two runs ended as one would expect (first time additional 5GB were allocated and it took 1 or 2 minutes to finish. The second time it was finishing within seconds). After that it didnt work anymore?!?
Although, it does not solves the issue, it improves the situation, because if I now abort the execution with CTRL+C the memory is freed and I do not have to exit the container. And in general, I think if the callback calls wandb.init() it should also call wandb.finish(). So from that point of view you could merge the PR altough it does not solves the problem itself.

However, I also played around with the callback and the line that causes the issues seems to be https://github.com/ludwig-ai/ludwig/blob/2772e9a36fffc1bc9f7d8403a0fbca1ca5b8258e/ludwig/contribs/wandb.py#L47. Commenting this line solves the OOM-problem in all runs that I did. 

I also investigate the runs on wandb especially the very first two ones that somehow successfully completed (using wandb.save()). The only differences seems to be that those two runs have this artifact-folder (containing only 1 file)
![image](https://github.com/ludwig-ai/ludwig/assets/8074083/dd0755c5-619d-4952-9086-307b1cecbeea)
pointing only to one parquet-file, with this content
![image](https://github.com/ludwig-ai/ludwig/assets/8074083/df5f3d2b-2e6f-402a-b3da-9f3815af6514)

Not sure what you expect what wandb.save() should upload, but to me it currently looks like this information is already logged and wandb.save() is not necessary. However, I assume that this should actually save amongst other things the model itself.
