### ISSUE TITLE
model_load_path not working in PythonAPI

### ISSUE THREAD

**Issue by MarselScheer** [ludwig-ai/ludwig#3705]
**Describe the bug**
model_load_path of LudwigModel.experiment() is ignored

The reason is that experiment() passes `model_load_path` to LuwdigModel.train() in https://github.com/ludwig-ai/ludwig/blob/ccd8d82459bee7a30aa5aa2256897a69bfc37445/ludwig/api.py#L1341C69-L1341C69 and since train() has no explicit model_load_path parameter it puts it into kwargs and train() then passes kwargs to preprocess() which does not uses kwargs.

Workaround for now seems to be 

```
m = LudwigModel.load(...)
m.experiment(...)
```

**Comment by Infernaught** [comment]
Hi @MarselScheer! Thank you for catching this! The workaround you mentioned is actually the correct way of doing this, and `model_load_path` should not be a parameter in `experiment()`. I will fix this shortly.
