### ISSUE TITLE
RuntimeError: Could not infer dtype of NoneType

### ISSUE THREAD

**Issue by NishaDeepak** [ludwig-ai/ludwig#3720]
The following error arises while training the model:

RuntimeError: Could not infer dtype of NoneType

The code is as follows:

!pip install ludwig
!pip install ludwig[llm]

import yaml
from ludwig.api import LudwigModel
import logging

qlora_fine_tuning_config = yaml.safe_load(
"""
model_type: llm
base_model: tiiuae/falcon-7b-instruct

input_features:

name: instruction
type: text
output_features:

name: output
type: text
prompt:
template: >-
Below is an instruction that describes a task, paired with an input
that provides further context. Write a response that appropriately
completes the request.

### Response:
generation:
temperature: 0.1
max_new_tokens: 512

adapter:
type: lora

quantization:
bits: 4

preprocessing:
global_max_sequence_length: 512
split:
type: random
probabilities:
- 1
- 0
- 0
eos_token_id: eos_token
pad_token_id: pad_token

trainer:
type: finetune
epochs: 5
batch_size: 1
eval_batch_size: 2
gradient_accumulation_steps: 16
learning_rate: 0.0004
learning_rate_scheduler:
warmup_fraction: 0.03
"""
)

model = LudwigModel(config=qlora_fine_tuning_config, logging_level=logging.INFO)
results = model.train(dataset=df)

The error mentioned above arises in this particular step.

The model was expected to complete its training.

Environment (please complete the following information):

OS: Windows 11
Version 22H2
Python 3.10
Ludwig 0.8.5

Am running the above code on GPU T4 runtime High RAM.

Please find the attached dataset, yaml file and also some screenshots of the training and error.
[LUDWIG dataset and yaml.zip](https://github.com/ludwig-ai/ludwig/files/12878734/LUDWIG.dataset.and.yaml.zip)

**Comment by jeffkinnison** [comment]
Hi @NishaDeepak while we dig into this could you try the following:

1. Moving the `eos_token_id` and `pad_token_id` to the `generation` section of the config or
2. Removing `eos_token_id` and `pad_token_id` from the config altogether

The `RuntimeError` is raised during an operation involving `pad_token_id`, so one or both of the options above may unblock you.
