### ISSUE TITLE
Integration tests e and slow tests are broken on master

### ISSUE THREAD

**Issue by arnavgarg1** [ludwig-ai/ludwig#3734]
Here's the latest run from the master branch: 

- Integration Tests E: https://github.com/ludwig-ai/ludwig/actions/runs/6539082960/job/17756382109 
- Slow Tests: https://github.com/ludwig-ai/ludwig/actions/runs/6539082956/job/17756417256 

For Integration Tests E, it seems like some test is causing an OOM or segfault potentially since we can't even view the run history for the tests that actually ran, but when you push a commit, you can see the tests run until they OOM. From what I've seen, the `test_ray_gbm` tests run but whatever comes right after it seems like it's causing hanging behavior. 

For slow tests, it seems like some other tests are hogging CPU resources so they're not being made available for this test: `tests/integration_tests/test_automl.py::test_train_with_config_remote[s3]`

**Comment by alexsherstinsky** [comment]
#self-assign

**Comment by alexsherstinsky** [comment]
A solution is proposed in #3737 -- please review.  Thank you. /cc @arnavgarg1

**Comment by alexsherstinsky** [comment]
Quick experiment: The test `tests/integration_tests/test_automl.py::test_train_with_config_remote[s3]` -- when run locally (Mac OS M1) by itself -- takes 1 minute and 43 seconds.  It always runs successfully to completion.

**Comment by alexsherstinsky** [comment]
The pull request #3748 has been merged -- thanks, @justinxzhao !
