### ISSUE TITLE
config and model missing in Trainer

### ISSUE THREAD

**Issue by jetaudio** [ludwig-ai/ludwig#3749]
When using deepspeed backend, Error occur: Trainer __init__ missing 2 positional config and model. Fixing in line 321 of ludwig/backend/base.py: add missing variable.
This is the code I used:

> qlora_fine_tuning_config = yaml.safe_load(
>"""
model_type: llm
base_model: alexsherstinsky/Mistral-7B-v0.1-sharded
>input_features:
>  - name: instruction
>    type: text
>output_features:
>  - name: output
>    type: text
>prompt:
>  template: >-
>    Below is an instruction that describes a task, paired with an input
>    that provides further context. Write a response that appropriately
>    completes the request.
>    Instruction: {instruction}
>    Input: {input}
>    Response:
>generation:
>  temperature: 0.1
>  max_new_tokens: 512
>adapter:
>  type: qlora
>quantization:
>  bits: 4
>preprocessing:
>  global_max_sequence_length: 512
>  split:
>    type: random
>    probabilities:
>    - 0.9
>    - 0.05
>    - 0.05
>trainer:
>  type: finetune
>  epochs: 1
>  batch_size: 1
>  eval_batch_size: 2
>  gradient_accumulation_steps: 16
>  learning_rate: 0.0004
>  learning_rate_scheduler:
>    warmup_fraction: 0.03
>backend:
>  type: deepspeed
>  zero_optimization:
>    stage: 3
>    offload_optimizer:
>      device: nvme
>      nvme_path: ./offload
>      pin_memory: true
>      fast
>"""
>)
>model = LudwigModel(config=qlora_fine_tuning_config, logging_level=logging.INFO,backend='deepspeed')
>results, _ , _ = model.train(dataset=df)`

**Comment by justinxzhao** [comment]
Hi @jetaudio,

Thanks for proposing a fix with https://github.com/ludwig-ai/ludwig/pull/3750.

The PR looks fine to me, but it would be good to get a quick look from @tgaddair and @arnavgarg1 who worked on the original deepspeed integration.

**Comment by tgaddair** [comment]
Thanks for the PR, @jetaudio! Closing this issue as #3750 has been landed :)
