### ISSUE TITLE
Windows Support needed

### ISSUE THREAD

**Issue by omnific9** [ludwig-ai/ludwig#3755]
**Describe the bug**
The current ludwig does not seem to work on Windows, as the underlying bitsandbytes library does not work on Windows. There are third-party compilations of bitsandbytes. Would you please consider updating this library so that ludwig can be run on Windows?

**To Reproduce**
Run the notebook on Windows

**Expected behavior**
Should work

**Screenshots**
![image](https://github.com/ludwig-ai/ludwig/assets/10455335/2d684c9f-c3ce-4856-8346-c9417f6d0279)

**Environment (please complete the following information):**

- OS: Windows
- Version: 11
- Python version: 3.10.12
- Ludwig version: 0.8.6

**Additional context**
N/A

**Comment by arnavgarg1** [comment]
Hi @omnific9! Thanks for raising this issue.

Do you have links to third party compilations that work on windows?

**Comment by omnific9** [comment]
@arnavgarg1 bear with me as I explain this:

I believe this worked for me 

```
pip install bitsandbytes --prefer-binary --extra-index-url=https://jllllll.github.io/bitsandbytes-windows-webui
```

However, in the interim I also tried https://pypi.org/project/bitsandbytes-windows/

While I'm 80% sure the former method works, there's a chance that the latter one works. You might need to try both.

Thanks for your attention!
