### ISSUE TITLE
 ModuleNotFoundError: No module named 'ray.air.checkpoint'

### ISSUE THREAD

**Issue by andysingal** [ludwig-ai/ludwig#3765]
**Describe the bug**

**To Reproduce**

1. Click on '....'
1. Scroll down to '....'
1. See error

Please provide code, yaml config file and a sample of data in order to entirely reproduce the issue.
Issues that are not reproducible will be ignored.

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**

- OS: \[e.g. iOS\]
- Version \[e.g. 22\]
- Python version
- Ludwig version

**Additional context**

```
import logging
import pprint

from ludwig.automl import create_auto_config
from ludwig.datasets import mushroom_edibility
from ludwig.utils.dataset_utils import get_repeatable_train_val_test_split

mushroom_df = mushroom_edibility.load()
mushroom_edibility_df = get_repeatable_train_val_test_split(mushroom_df, 'class', random_seed=42)

auto_config = create_auto_config(
    dataset=mushroom_edibility_df,
    target='class',
    time_limit_s=7200,
    tune_for_memory=False,
    user_config={'preprocessing': {'split': {'column': 'split', 'type': 'fixed'}}},
)

pprint.pprint(auto_config)
```

**Comment by justinxzhao** [comment]
Hi @andysingal, which version of ray are you using? Ludwig requires ray v2.3.1.

**Comment by andysingal** [comment]
> Hi @andysingal, which version of ray are you using? Ludwig requires ray v2.3.1.

Thanks for your instant reply, i used https://pypi.org/project/ray/

**Comment by justinxzhao** [comment]
Hi @andysingal,

In order to use datasets hosted on kaggle, you'll need to make sure that your Kaggle credentials are set up properly and you've logged into kaggle to agree to the rules of the competition: https://ludwig.ai/latest/user_guide/datasets/dataset_zoo/#kaggle-datasets

**Comment by andysingal** [comment]
> Hi @andysingal,
> 
> In order to use datasets hosted on kaggle, you'll need to make sure that your Kaggle credentials are set up properly and you've logged into kaggle to agree to the rules of the competition: https://ludwig.ai/latest/user_guide/datasets/dataset_zoo/#kaggle-datasets

Thanks for your response , but i am still having challenges with datasets provided by your product as mentioned in the initial comments

**Comment by justinxzhao** [comment]
@andysingal The error in your previous comment is:

```
OSError: Could not find kaggle.json. Make sure it's located in /root/.kaggle. Or use the environment method.
```

Even though you are using Ludwig, the dataset itself is hosted by Kaggle, so you'll need to ensure you have the right kaggle credentials set up in order to load the dataset through Ludwig.

Does this file exist in your development environment?
```
ls ~HOME/.kaggle/kaggle.json
```

**Comment by andysingal** [comment]
> File "/usr/local/lib/python3.10/dist-packages/ludwig/datasets/kaggle.py", line 10, in create_kaggle_client
>     from kaggle import api
>   File "/usr/local/lib/python3.10/dist-packages/kaggle/__init__.py", line 23, in <module>

let me check, i am pretty sure i added it.. Let me add it again and share update to you . Thanks

**Comment by SarthakNikhal** [comment]
Can I help in resolving this issue?

**Comment by iulianastroiavlad** [comment]
Hi, is this issue solved? I tried the example from here: https://ludwig.ai/latest/getting_started/hyperopt/, to test the hyperopt (using **ray version 2.3.1**), but still I get the same initial error: **ImportError: cannot import name 'Checkpoint' from 'ray.air'**

**Comment by andysingal** [comment]
I do, but still have to try it out . I added your ai software in my article
:
https://medium.com/illuminations-mirror/mlops-leveraging-large-language-models-for-streamlining-machine-learning-from-development-to-4023e08846bf

**Comment by majsterkovic** [comment]
I am encountering the same problem with the `ray `module
