### ISSUE TITLE
preprocess_for_training Caught exception during model preprocessing: maximum recursion depth exceeded while getting the str of an object

### ISSUE THREAD

**Issue by Bdl-1989** [ludwig-ai/ludwig#3767]
**Describe the bug**
preprocess_for_training Caught exception during model preprocessing: maximum recursion depth exceeded while getting the str of an object
**To Reproduce**

sample from github:

results = model.train(dataset=df)
print(results)

Please provide code, yaml config file and a sample of data in order to entirely reproduce the issue.
Issues that are not reproducible will be ignored.

import yaml

config_str = """
model_type: llm
base_model: /mnt/d/AI/Models/llama-7b-hf

quantization:
  bits: 4

adapter:
  type: lora

prompt:
  template: |
    ### Instruction:
    {instruction}

    ### Input:
    {input}

    ### Response:

input_features:
  - name: prompt
    type: text
    preprocessing:
      max_sequence_length: 256

output_features:
  - name: output
    type: text
    preprocessing:
      max_sequence_length: 256

trainer:
  type: finetune
  learning_rate: 0.0001
  batch_size: 1
  gradient_accumulation_steps: 16
  epochs: 3
  learning_rate_scheduler:
    warmup_fraction: 0.01

preprocessing:
  sample_ratio: 0.1
"""

config = yaml.safe_load(config_str)

**Expected behavior**

**Screenshots**
![image](https://github.com/ludwig-ai/ludwig/assets/48614612/4c3ea28f-2a44-465e-b9dd-5b81bdcb79e3)

**Environment (please complete the following information):**

- OS: windows wsl(ubuntu 22)
- Version \[e.g. 22\]
- Python version
![image](https://github.com/ludwig-ai/ludwig/assets/48614612/951b3e3d-1645-4d93-8a5b-aa52bd571d96)

- Ludwig version
![image](https://github.com/ludwig-ai/ludwig/assets/48614612/75f6995a-f36f-4bd1-bd72-d4c21144d08a)

**Additional context**

**Comment by justinxzhao** [comment]
@Bdl-1989 Odd error. Are you able to use the tokenizer for `/mnt/d/AI/Models/llama-7b-hf` on your outside of Ludwig?

```
from transformers import AutoTokenizer
import pandas as pd

tokenizer = AutoTokenizer.from_pretrained("/mnt/d/AI/Models/llama-7b-hf")

# Example DataFrame
df = pd.DataFrame({
    'text_column': [
        "Here is the first text to encode",
        "And here is the second one",
        # ... other texts
    ]
})

# Tokenize the text column
tokenized_column = df['text_column'].apply(lambda x: tokenizer.encode_plus(x, return_tensors='pt', truncation=True, padding='max_length', max_length=512))
```
