### ISSUE TITLE
Ludwig: Fine-Tune Mistral-7b missing LudwigModel import and/or definition

### ISSUE THREAD

**Issue by noahgift** [ludwig-ai/ludwig#3884]
**Describe the bug**
Ludwig: Fine-Tune Mistral-7b missing LudwigModel import and/or definition.

**To Reproduce**

1. Go to 'https://colab.research.google.com/drive/1i_8A1n__b7ljRWHzIsAdhO7u7r49vUm4#scrollTo=k-dtCIj73498'
1. Run Cells in cola
1. Scroll down to 'qlora_fine_tuning_config = yaml.safe_load(' cell and notice LudwigModel not defined
1. see error

Please provide code, yaml config file and a sample of data in order to entirely reproduce the issue.
Issues that are not reproducible will be ignored.

**Expected behavior**

**Screenshots**
![Screenshot 2024-01-16 at 1 19 36 PM](https://github.com/ludwig-ai/ludwig/assets/58792/44fb648b-ea76-4dc1-81c9-08bb5c629858)

**Environment (please complete the following information):**

- OS: \[e.g. iOS\]
- Version \[e.g. 22\]
- Python version
- Ludwig version

**Additional context**

**Comment by arnavgarg1** [comment]
Hey @noahgift - thanks for flagging this issue and sorry you ran into it. I'm taking a look right now and will get back to you once I know what's going on and find a fix.

**Comment by arnavgarg1** [comment]
@noahgift I was able to repro and I see the problem - just a few missing imports. Let me update the notebook so that it runs correctly.

**Comment by noahgift** [comment]
> @noahgift I was able to repro and I see the problem - just a few missing imports. Let me update the notebook so that it runs correctly.

Thank you so much!  Putting this into a Coursera Duke course on LLMOps!

**Comment by alexsherstinsky** [comment]
I only just saw this -- did I really not include imports into the notebook?  Not sure how this could have happened if it ran fine.   In fact, I just checked [the original source of this notebook](https://colab.research.google.com/drive/1GWabrlCE25OKG615HejV8wRcHMhOKKZi?usp=sharing), and all the imports seem to be there.  Apologies, @noahgift, for any confusion and lost productivity.  Thank you!

**Comment by arnavgarg1** [comment]
@alexsherstinsky Thanks for checking! I believe this is a notebook I created a few months ago after our collaboration when Mistral first came out and I may have missed some imports. It was meant to a be a lean/stripped down version of the original notebook adapted and blogpost, but adapted for the code alpaca dataset in conjunction with fine-tuning on Llama-2-7b/13b as can be seen in the Ludwig README. 

I'm also surprised that I missed some imports, but I've updated the notebook now to have the right imports! Just making sure that the training parameters are adjusted so that the notebook has good inference performance when it's run!

**Comment by alexsherstinsky** [comment]
@arnavgarg1 Now I see what is going on!  Thank you very much for clarifying!  Whew! 😄

**Comment by arnavgarg1** [comment]
@noahgift Alright, things should be fixed up! Are you able to give it a try now?

**Comment by noahgift** [comment]
> @noahgift Alright, things should be fixed up! Are you able to give it a try now?

Perfect!  Just verified it worked.   Appreciate it!  Such a great example of why Ludwig is cool.  Love anything non-meta as an example!
