### ISSUE TITLE
Temporarily disable expensive text metrics

### ISSUE THREAD

**Issue by arnavgarg1** [ludwig-ai/ludwig#3953]
This issue has been created to track that the following text metrics have been temporarily disabled because they are expensive to compute:

1. BLEU
2. ROUGE
3. WordErrorRate
4. CharacterErrorRate

We can re-enable them at a different time by allowing users to customize which metrics they want to see during training, leaving the onus on the user to decide how much extra time they are willing to spend training to get more training metrics.

For reference, this is how BLEU and ROUGE scale with a sample of 200 rows over different sequence lengths:

![image](https://github.com/ludwig-ai/ludwig/assets/106701836/8838a151-1c49-4a65-88df-a6ae0fd3f843)

**Comment by alexsherstinsky** [comment]
Closing, since the PR has been merged.
