### ISSUE TITLE
Add Ludwig config json to output directory containing model weights

### ISSUE THREAD

**Issue by sanjaydasgupta** [ludwig-ai/ludwig#3961]
**Is your feature request related to a problem? Please describe.**
Reproducing other users' experiences is important in many contexts, so automatically publishing the Ludwig config along with a fine-tuned model's weights on huggingface will be a helpful step. This objective can be achieved by just adding a json file containing the ludwig configuration to the output directory that also contains the model weights.

**Describe the use case**
The primary motivation is to facilitate reproduction of other users' experiments. Publishing the Ludwig configuration is a first step in this direction.

**Describe the solution you'd like**
Modify the code of method `Ludwig.api.train()` as follows:

1. Add a new parameter `save_ludwig_config_with_weights: bool = False` that the caller can use to indicate whether or not they want to upload the user-provided ludwig config to HF along with the model weights.
2. After the lines that save the model weights to the output directory (line# 768) add code to save a _json_ or _yaml_ file containing the user-provided config to the directory containing the model weights.

No other change is necessary as the existing code that uploads model weights and other associated files to HF (in/under `Ludwig.api.upload_to_hf_hub(...)`) automatically picks up all _json_ and _yaml_ files from the output directory.

**Describe alternatives you've considered**
~Modifying the code under `LudwigModel`'s [upload_to_hf_hub(...)](https://github.com/ludwig-ai/ludwig/blob/master/ludwig/api.py) is the only option. The changes should add a file containing the configuration (either _ludwig_config.yaml_ or _ludwig_config.json_ -- to be decided) to the experiment's _model/model_weights_ directory. The implementation of `upload_to_hf_hub` already looks for and uploads all _yaml_ and _json_ files in the _model/model_weights_ directory to huggingface.~

~Users may not always want to upload the configuration, so an additional parameter `upload_config: bool = False` for `upload_to_hf_hub(...)` will be added to select the required behavior.~

**Additional context**
This is similar to the feature described [here](https://twitter.com/HamelHusain/status/1740235746630570348?s=20).

**Comment by sanjaydasgupta** [comment]
#take

**Comment by sanjaydasgupta** [comment]
#take

**Comment by alexsherstinsky** [comment]
Implemented in #3965
