### ISSUE TITLE
phi 3 error

### ISSUE THREAD

**Issue by tahaAmineMiri** [ludwig-ai/ludwig#3999]
hi i'm getting error while try to fine-tune phi 3

![Screenshot 2024-04-24 175119](https://github.com/ludwig-ai/ludwig/assets/115357166/ac778b50-4234-46da-9f4d-8d846fd26388)

![Screenshot 2024-04-24 174635](https://github.com/ludwig-ai/ludwig/assets/115357166/dec5aaef-743b-4d15-9f37-b71f52b167f0)

**Comment by savi8sant8s** [comment]
I had the same error

**Comment by hiCreo-John** [comment]
Has anyone solved this issue?

**Comment by arnavgarg1** [comment]
Hi @hiCreo-John, are you still running into this issue? What version of transformers, PEFT and Ludwig are you using?

**Comment by hiCreo-John** [comment]
Thank you for answering my question.
  Is there a solution to this issue?

Name: ludwig
Version: 0.10.3

Name: peft
Version: 0.11.1

John

**Comment by rlleshi** [comment]
@arnavgarg1 I'm also running into this issue. Any updates?

**Comment by arnavgarg1** [comment]
@rlleshi Can you try this branch?

https://github.com/ludwig-ai/ludwig/pull/4014
