### ISSUE TITLE
Working with Video Data

### ISSUE THREAD

**Issue by SivamPillai** [ludwig-ai/ludwig#449]
Is it possible to use the Ludwig framework to make predictions on sampled video data?

Consider a case where I would like to predict an outcome based on say 30 video frames. This is possible using a framework like keras using layers such as ConvLSTM, Conv3D, etc. With Ludwig I see the image datatype only allows for 2D+channel data format as input.

I would like to know if there is a way of achieving the above goal using the existing framework.
If yes, are there any documentation available? If no, is this a feature that will be considered for future updates?

Happy to contribute!

**Comment by carlogrisetti** [comment]
You can always split the video input in frames and process each single one separately or, if you need some sort of correlation between two frames as in your example, process a single "composite" frame N-fold in width with the second, third, fourth, nth frame pasted after each other.
You can just use numpy with something like  np.concatenate((frame1, frame2), axis=1) to have a single array with all the frames stitched together.
In your example you can have 29 frames stitched together as input data, and the 30th frame as output and train based on those, but as of now there are no image output features, so it would basically be a numerical array output.

That's how I would approach that, taken that you only have access to the current implementation

**Comment by w4nderlust** [comment]
At the moment Ludwig does not support video data.
@carlogrisetti 's suggestion is a more than reasonable workaround, but anyway, video data is something we are considering.
Adding to the feature requests, but contributions are welcome, in particular by someone with direct expertise on videos. I can provide guidance and directions if someone want to pick up this task. Audio features took just a couple days to implement with this guidance by someone with speech experience, I would expect a similar amount of time to be required by someone with video expertise to add video features.

**Comment by abhiTronix** [comment]
Hello, awesome project. If you need easy and flexible option for video processing in python, then you can look my [VidGear](https://github.com/abhiTronix/vidgear) python library that provide support for both OpenCV and FFmpeg backends for decoding and encoding video files in real-time and other unique features. Good luck.

**Comment by w4nderlust** [comment]
@abhiTronix thanks! Will consider it when we will get to it for sure!
