### ISSUE TITLE
Failed to install ludwig in  python:3.6-alpine3.9 due to tensorflow  version mismatch error

### ISSUE THREAD

**Issue by priyaJagan90** [ludwig-ai/ludwig#459]
Hi,

I couldn't install ludwig in python:3.6-alpine3.9 as tensorflow version 1.13.1 mismatches with the tensorflow version 1.14.0 in the requirement.txt file. Can you please set the tensorflow version to 1.13.1 and 1.14.0 to make it compatible with python 3.6 and python 3.7

**Comment by tqa236** [comment]
I have a similar problem but in my case it the constraint scikit-image=0.14.2 that causes an error. Is it possible to relax these constraints a little?

**Comment by msaisumanth** [comment]
@priyaJagan90 I think making that change will break a lot of things since we migrated the code to use 1.14. Were you able to make this work locally by switching to 1.13.1?

**Comment by justinxzhao** [comment]
Ludwig version has moved to PyTorch.
