### ISSUE TITLE
Forcing distributed Evaluation

### ISSUE THREAD

**Issue by tboo** [ludwig-ai/ludwig#507]
Hi there -

I occasionally still run into this [issue](https://github.com/horovod/horovod/issues/403) which seems to be Horovod related and specific to GPU distributed training:

```
[2019-08-28 08:31:55.292536: W horovod/common/operations.cc:764] One or more tensors were submitted to be reduced, gathered or broadcasted by subset of ranks and are waiting for remainder of ranks for more than 60 seconds. This may indicate that different ranks are trying to submit different tensors or that only subset of ranks is submitting tensors, which will cause deadlock. 
Stalled ranks:
0: [optimizer/DistributedAdamOptimizer_Allreduce/HorovodAllreduce_optimizer_gradients_AddN_0, optimizer/DistributedAdamOptimizer_Allreduce/HorovodAllreduce_optimizer_gradients_AddN_2_0, optimizer/DistributedAdamOptimizer_Allreduce/HorovodAllreduce_optimizer_gradients_AddN_4_0, optimizer/DistributedAdamOptimizer_Allreduce/HorovodAllreduce_optimizer_gradients_AddN_6_0, optimizer/DistributedAdamOptimizer_Allreduce/HorovodAllreduce_optimizer_gradients_class_predictions_class_add_grad_tuple_control_dependency_1_0, optimizer/DistributedAdamOptimizer_Allreduce/HorovodAllreduce_optimizer_gradients_image_path_conv_0_add_grad_tuple_control_dependency_1_0 ...]
1: [optimizer/DistributedAdamOptimizer_Allreduce/HorovodAllreduce_optimizer_gradients_AddN_0, optimizer/DistributedAdamOptimizer_Allreduce/HorovodAllreduce_optimizer_gradients_AddN_2_0, optimizer/DistributedAdamOptimizer_Allreduce/HorovodAllreduce_optimizer_gradients_AddN_4_0, optimizer/DistributedAdamOptimizer_Allreduce/HorovodAllreduce_optimizer_gradients_AddN_6_0, optimizer/DistributedAdamOptimizer_Allreduce/HorovodAllreduce_optimizer_gradients_class_predictions_class_add_grad_tuple_control_dependency_1_0, optimizer/DistributedAdamOptimizer_Allreduce/HorovodAllreduce_optimizer_gradients_image_path_conv_0_add_grad_tuple_control_dependency_1_0 ...]
2: [optimizer/DistributedAdamOptimizer_Allreduce/HorovodAllreduce_optimizer_gradients_AddN_0, optimizer/DistributedAdamOptimizer_Allreduce/HorovodAllreduce_optimizer_gradients_AddN_2_0, optimizer/DistributedAdamOptimizer_Allreduce/HorovodAllreduce_optimizer_gradients_AddN_4_0, optimizer/DistributedAdamOptimizer_Allreduce/HorovodAllreduce_optimizer_gradients_AddN_6_0, optimizer/DistributedAdamOptimizer_Allreduce/HorovodAllreduce_optimizer_gradients_class_predictions_class_add_grad_tuple_control_dependency_1_0, optimizer/DistributedAdamOptimizer_Allreduce/HorovodAllreduce_optimizer_gradients_image_path_conv_0_add_grad_tuple_control_dependency_1_0 ...] 
```

I am observing that stall especially with (very) small batch sizes. The stall occurs during evaluation of the training set. Horovod/Ludwig seems to wait for evaluation results from all GPUs previously used for training but the evaluation of small batch sizes is often carried out on one (or some) GPUs but not all. If I increase the `eval_batch_size` independent of `batch_size` I get more cards busy to perform evaluation (but again, not all). With very large images the batch size is fairly limited, however.

When all cards are being utilized for evaluation (that happens in my case only when batch sizes are large) I do not run into this issue. So I am wondering if there is a way to force the distribution of the evaluation to the same number of GPUs that is used for training. Because the number of cards used for evaluations seems rather arbitrary to me.

You should be able to reproduce that problem if you are choosing a batch size of 1 or 2 and train on more than 1 GPU.

Ludwig 0.2.1 (image classification tasks)
OpenMPI 4.0.1
Horovod 0.16
4xTesla V100 PCIe (but I also observed similar behavior on an 8x V100 SMX2 infrastructure)

**Comment by w4nderlust** [comment]
@alsrgv Have you ever encountered this? Any suggestion on what could be the cause?

**Comment by w4nderlust** [comment]
@tboo could you try to open an issue in the Horovod repo referring to this? I'm having trouble replicating this.

**Comment by justinxzhao** [comment]
The latest Ludwig version has moved to PyTorch. Please re-open this issue if it can be reproduced on Ludwig 0.5+.
