### ISSUE TITLE
is there any way I can train my model faster?

### ISSUE THREAD

**Issue by Kantshun** [ludwig-ai/ludwig#513]
It seems that ludwig can't use my computer resource effectively while training a model. Is there any way I can use so that ludwig can occupy more cpu and gpu resource? It's using less than one half of compute capability of my computer right now.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/31396222/64267371-db0b2580-cf68-11e9-9bb3-0069113d7574.png)

**Environment (please complete the following information):**
 - OS: win10
 - Version professional
- Python version:3.7
- Ludwig version:master

**Comment by w4nderlust** [comment]
Increase your batch size
