### ISSUE TITLE
Support TFRecord format

### ISSUE THREAD

**Issue by yu-iskw** [ludwig-ai/ludwig#519]
**Is your feature request related to a problem? Please describe.**
CSV and HDF5 is not good to deal with  a large data like millions of images. Technically, we can store a large number of images in machine(s). However, it is not good when we want to do experiments with different parameters in parallel.

With modern tensorflow, it would be great to load data with TFRecord especially google cloud storage. So, we should not store datasets in machines physically.

**Describe the use case**
If we can read a large data with TFRecord as stream especially on google cloud storage, we can casually run experiments on anywhere. We don't need to care about how to prepare datasets on machines.

**Describe the solution you'd like**
It would be great to support TFRecord data type. And reading TFRecord files on GCS directly would be best.

**Describe alternatives you've considered**
I don't have any alternate solution.

**Comment by w4nderlust** [comment]
We are going in a different direction, using Petastorm instead, that is a more generic solution than TFRecords.

**Comment by yu-iskw** [comment]
@w4nderlust That sounds interesting. I didn't know petastorm. It would be better than TFRecord, since it supports pytorch as well.

Does petastorm support google cloud storage rather than HDFS?

**Comment by justinxzhao** [comment]
Ludwig has migrated to PyTorch
