### ISSUE TITLE
model output problem

### ISSUE THREAD

**Issue by Kantshun** [ludwig-ai/ludwig#526]
I trained a ludwig model to do some classification. my labels are strings such as 'cat','dog'. when I use my ludwig model to predict the label of my testing set, I found that Ludwig model output integers such as '0','1','2'instead of my string label. I suppose my model's output is the same type of the labels of my training data set, not number. I can't map my string label to ludwig model's integer label.
Is there anyway I can make my ludwig model's output in a right way?

**Comment by msaisumanth** [comment]
@Kantshun check out the train_set_metadata file in the model/ folder. For each output feature, 
you'll see the idx2str, which is the mapping between the 0/1/2.. to their category names. 

This is a simple change and we'll prioritize accordingly. Thanks for creating the issue.

**Comment by w4nderlust** [comment]
Ludwig should provide the output as strings, if it does not do it it means there's a problem. Can you please provide a fully reproducible example? With model definition and data sample or sythetic data?
