### ISSUE TITLE
Question: are unittests going to be open sourced?

### ISSUE THREAD

**Issue by sk-** [ludwig-ai/ludwig#57]
Are unittests going to be open sourced? At the moment only integration tests have been published.

On the positive side, the [Developers Guide](https://uber.github.io/ludwig/developer_guide/#tests) says:   

> Current test coverage is limited to several integration tests which ensure end-to-end functionality but we are planning to expand it.

which hints that more testing is yet to be added.

**Comment by msaisumanth** [comment]
Yes, we'll be doing that very soon.

**Comment by w4nderlust** [comment]
Will be working on it. The rationale at the moment is that this is a first `v0.x` release, which means that interfaces may change wildly in the first releases and converge gradually. So providing integration tests is a way to ensure functionality without tests getting much in the way of future changes, while unit tests are more constraining. With future releases and the convergence towards stable interfaces we plan to add unit tests too.

**Comment by justinxzhao** [comment]
Unit tests are all open sourced.
