### ISSUE TITLE
Deadlock with some datasets

### ISSUE THREAD

**Issue by mangleddata** [ludwig-ai/ludwig#610]
**Describe the bug**
Some datasets cause hangup with no progress being made. 

**To Reproduce**
Unfortunately, I don't know if I can provide a reproducer since the data is custom data. However, I am happy to provide log info or any other data that would be helpful. The log shows deadlock on 1st epoch 

1,0]<stdout>:╒══════════╕
[1,0]<stdout>:│ TRAINING │
[1,0]<stdout>:╘══════════╛
[1,0]<stdout>:
[1,0]<stdout>:
[1,0]<stdout>:Epoch   1
Training: 100% 377/377 [01:32<00:00,  4.07it/s][1,0]<stdout>:
Evaluation train: 100% 377/377 [00:25<00:00, 14.82it/s][1,0]<stdout>:

Train set = ~900K rows rows, 900 features
Valid set = ~100K rows

[1,0]<stderr>:[2020-01-10 19:52:29.658590: W horovod/common/stall_inspector.cc:105] One or more tensors were submitted to be reduced, gath
ered or broadcasted by subset of ranks and are waiting for remainder of ranks for more than 60 seconds. This may indicate that different r
anks are trying to submit different tensors or that only subset of ranks is submitting tensors, which will cause deadlock.
[1,0]<stderr>:Stalled ranks:
[1,0]<stderr>:0: [optimizer/DistributedAdamOptimizer_Allreduce/HorovodAllgather_optimizer_gradients_concat_0, optimizer/DistributedAdamOpt
imizer_Allreduce/HorovodAllgather_optimizer_gradients_concat_10_0, optimizer/DistributedAdamOptimizer_Allreduce/HorovodAllgather_optimizer
_gradients_concat_11_0, optimizer/DistributedAdamOptimizer_Allreduce/HorovodAllgather_optimizer_gradients_concat_1_0, optimizer/Distribute
dAdamOptimizer_Allreduce/HorovodAllgather_optimizer_gradients_concat_2_0, optimizer/DistributedAdamOptimizer_Allreduce/HorovodAllgather_op
timizer_gradients_concat_3_0 ...]
[1,0]<stderr>:1: [optimizer/DistributedAdamOptimizer_Allreduce/HorovodAllgather_optimizer_gradients_concat_0, optimizer/DistributedAdamOpt
imizer_Allreduce/HorovodAllgather_optimizer_gradients_concat_10_0, optimizer/DistributedAdamOptimizer_Allreduce/HorovodAllgather_optimizer
_gradients_concat_11_0, optimizer/DistributedAdamOptimizer_Allreduce/HorovodAllgather_optimizer_gradients_concat_1_0, optimizer/Distribute
dAdamOptimizer_Allreduce/HorovodAllgather_optimizer_gradients_concat_2_0, optimizer/DistributedAdamOptimizer_Allreduce/HorovodAllgather_op
timizer_gradients_concat_3_0 ...]

**Expected behavior**
Expect to make training progress.

**Environment (please complete the following information):**
 - OS: Ubuntu 
 - Version 18.04
- Python version 3.6.6
- Ludwig version 0.2.1

horovodrun  -v
0.18.2

Any pointers to overcome this ?

**Comment by w4nderlust** [comment]
@mangleddata you can find a script to generate synthetic data that look like your in `data/dataset_synthesizer.py`. If you can provide a synthetic dataset together with your model definition to reproduce the issue we would be happy to look into it. Also, being int a Horovod related issue, maybe @tgaddair may have suggestions.

**Comment by tgaddair** [comment]
Hey @mangleddata, how many worker processes are you using (`-np`)?  This kind of error suggests that the the amount of work being done is different between the workers.  Common causes are uneven distributions of the dataset (one worker gets extra batches per epoch, or one worker does validation while the others are proceeding with the next epoch).

**Comment by mangleddata** [comment]
@tgaddair I have 8 workers.  The dataset is balanced (two classes). Are there any ways to force a even distribution ? I will look into creating a reproducer w/ synthetic data. Not all datasets of similar nature cause it, so puzzled. What would be a useful feature is to shutdown if deadlock happens. Because overnight runs hang and it'd be better to shut down the run rather and may be move on to a different dataset.

**Comment by tgaddair** [comment]
@mangleddata, I mean is the dataset evenly divisible by 8 into an equal number of batches per epoch?  If not, that could be the issue.  We would typically truncate extra batches to ensure they are evenly split, I'm not sure if Ludwig accounts for this automatically (@w4nderlust, can you clarify?).

If you want Horovod to shutdown on deadlock, you can use the `--stall-check-shutdown-time-seconds` arg.  If you set it to a value greater than the warning time (default: 60 seconds), then it will shutdown after that many seconds have elapsed.

**Comment by mangleddata** [comment]
@tgaddair - Dataset may not be evenly divisible by 8. I have separate data for train, valid and test (in the ratio 80%, 10%, 10% roughly). 

Could certainly trim the train and valid to be evenly divisible by 8 (I assume both train and valid right?). The --stall-check-shutdown-time-seconds is a great tip. Thank you! Will try it.

**Comment by tgaddair** [comment]
@mangledata, yes, both train and validation (assuming you are using Horovod for validation as well, which is recommended).

**Comment by w4nderlust** [comment]
> @mangleddata, I mean is the dataset evenly divisible by 8 into an equal number of batches per epoch? If not, that could be the issue. We would typically truncate extra batches to ensure they are evenly split, I'm not sure if Ludwig accounts for this automatically (@w4nderlust, can you clarify?).

This is Ludwig's way to balance data:
https://github.com/uber/ludwig/blob/master/ludwig/utils/batcher.py#L163
Different workes may get up to one batch difference, but that hasn't been a problem so far. if you think that's the source of the problem i can investigate more.

**Comment by w4nderlust** [comment]
> @mangleddata, yes, both train and validation (assuming you are using Horovod for validation as well, which is recommended).

Yes Ludwig uses the same batcher for evaluation too: https://github.com/uber/ludwig/blob/master/ludwig/models/model.py#L1461:9

**Comment by mangleddata** [comment]
@tgaddair - Turned out the hang issue came back even after I trimmed down train/valid data to be evenly divisible by 8. I am trying my run again with `--stall-check-shutdown-time-seconds` parameter

**Comment by w4nderlust** [comment]
@mangleddata let me know if you have some data to reproduce the issue. The fact that it happens only in a specific scenario makes me think it's data related.

**Comment by mangleddata** [comment]
@w4nderlust I don't have a reproducer yet, but the data and model looks similar to the reproducer in https://github.com/uber/ludwig/issues/642. I am still working on getting a dataset for this ticket.

**Comment by justinxzhao** [comment]
Ludwig has migrated to PyTorch in 0.5, which could have implications on this issue. Please feel free to re-open if the issue is reproducible with the latest version of Ludwig.
