### ISSUE TITLE
Sagemaker Support

### ISSUE THREAD

**Issue by bcordo** [ludwig-ai/ludwig#614]
What would be the best way to use this with AWS sagemaker? Would it even make sense to use it with Sagemaker, or are the Ludwig features duplicates?

I have found this: https://kenza-ai.github.io/sagify/
And resources such as this: https://sagemaker.readthedocs.io/en/stable/using_tf.html

I just wanted to get people's opinions first.

**Comment by jenishah** [comment]
This feature would be extremely useful.

**Comment by w4nderlust** [comment]
Taken a look at it. It seems pretty straightforward to implement the train and predict functions in sagify. They will probably end up 1/2 lines of code each calling `LudwigModel.train` and LudwigModel.predict`.
This is a potential feature to add and if someone from the community wants to work on it, that would be great.

**Comment by jenishah** [comment]
I want to work on it, and I read the documentation for sagify.
Are we supposed to push the final docker image to ECS?

**Comment by brightsparc** [comment]
@jenishah I have published a sample on how to build, train and deploy a Ludwig model with Amazon SageMaker if you want to check it out: https://github.com/aws-samples/amazon-sagemaker-ludwig-transformer
