### ISSUE TITLE
How to use other languages with bert Encoder

### ISSUE THREAD

**Issue by charlanalves** [ludwig-ai/ludwig#619]
Describe the use case
is there some way to use other languages with Bert encoder?

Describe the solution you'd like
Something like this:
   input_features:
    -
        name: text
        type: text
        encoder: bert
        config_path: ./bert/bert_config.json
        checkpoint_path: ./bert/bert_model.ckpt
        do_lower_case: False
        preprocessing:
          tokenizer: bert          
          vocab_file: ./bert/vocab.txt
          padding_symbol: '[PAD]'
          unknown_symbol: '[UNK]'
          **word_format: portuguese_tokenize**
        level: word

**Comment by msaisumanth** [comment]
If you download the multilingual version of BERT (from https://github.com/google-research/bert), you maybe able to use it as is (```tokenizer: bert```). Could you please give that a try and let us know?

**Comment by msaisumanth** [comment]
The webpage says that if you download the Cased version, you should be able to run multilingual models without any code changes

**Comment by w4nderlust** [comment]
If you are loading a pretrained BERT model you'll need to use the associated BERT tokenizer, otherwise it will simply not work. Given that, as @msaisumanth is saying, you can use the multilingual versions of BERT for that, together with their respective tokenizer vocabulary.

**Comment by charlanalves** [comment]
First of all , thank you guys for your prompt reply!
I'll do what @msaisumanth said and let you know
