### ISSUE TITLE
Image Decoder

### ISSUE THREAD

**Issue by jplehmann** [ludwig-ai/ludwig#679]
I know this is a feature being worked on, but I didn't see an issue for it. 

E.g., I'd like to build a stacked CNN that removes noise from photos.

Any sense of how long until this is available?  Thanks!

**Comment by w4nderlust** [comment]
@jplehmann thank you for opening this, it is indeed something we have in the backlog, but we are currently focusing on other aspects (see https://github.com/uber/ludwig/projects/1 , the image output features are in the triage section).
It's difficult to give a timeline for this. It will likely not be in v0.3 which will likely come out in the next two months, but it is likely that image outputs, together with other outputs features (bounding box for object detection and timeseries) will be prioritize when the works for v0.4 begin.
As for any other feature, we welcome contribution, I can provide full guidance on how to go and implement the feature if someone is willing to help.

**Comment by jplehmann** [comment]
@w4nderlust I'm probably not the person to build this out right now, but thank you for the quick response (again) and info.  Really excited about this project.

**Comment by jeffin07** [comment]
@w4nderlust i would like to work on this issue

**Comment by w4nderlust** [comment]
@jeffin07 it would be great, but I would push it to after when we are done with TF2 porting, as this will require adding some modeling code.

**Comment by jeffin07** [comment]
@w4nderlust okay hope to work on this after TF2 porting

**Comment by qiagu** [comment]
Any update on this?
