### ISSUE TITLE
Ludwig custom algorithms

### ISSUE THREAD

**Issue by boulaziz** [ludwig-ai/ludwig#717]
Dear Piero,
I hope all is well in these difficult.
I started using Ludwig and I have to admit that it a very promising package.
I have tested with the iris data. It worked fine. Still I want to force Ludwig to use the specific algorithms below and compare their outcomes:

LR, LogisticRegression (solver='liblinear', multi_class='ovr')
LDA, LinearDiscriminantAnalysis
KNN, KNeighborsClassifier
CART, DecisionTreeClassifier
NB, GaussianNB
SVM, SVC(gamma='auto')

Could you please let me know if this is possible and how.

I thank you in advance.
Khaled Boulaziz

**Comment by w4nderlust** [comment]
@boulaziz thank you for your questions.
In the future release of Ludwig there will be a more abstract interface that would allow people to specify their own models more easily.
That said, Ludwig is a deep learning toolbox at the moment, and we do not plan to add or support non deep learning algorithms in the toolbox at the moment.
(You can do Logistic Regression for sure anyway, just use a binary output feature).
There are many other libraries that already support all those algorithms like scikit-learn, which works pretty well, so I suggest you to use that instead for non deep learning algorithms.
