### ISSUE TITLE
[Feature request] Model hub

### ISSUE THREAD

**Issue by flozi00** [ludwig-ai/ludwig#722]
An modelhub as huggingface transformers have too.
Basicly the same as huggingface transformers models hub is, just for ludwig.
Filtered by input and output features, so with the time more and more pretrained models are getting built with ludwig and the training process takes a lot less time than before.
The filtering could be done with the defitionion file as must have for the model description.
For the basic tasks like text classification, image classification etc I could train and share the models.

**Comment by w4nderlust** [comment]
This is a lovely idea and something I've been thinking about for a log while. I would also want to provide pretraines encoders, decoders and combiners.
This has not ahppened so far mostly because of the time it requires, but it is definitely something I want to do.
If someone from the community is interested in helping on this, I would be glad to direct and support them!

**Comment by flozi00** [comment]
Hey, sounds good.
We don't have time to help you with programming but we would upload pretrained models as much as we can.
At the moment we are especially building CV models.
I'd love to support this sinces Ludwig is a great opportunity to give prototyping tasks to my colleagues who don't have any idea about DL ;)
A pretty lazy solution would be an GitHub repo with json file containing links to this models.

**Comment by w4nderlust** [comment]
I would proably study how Hugging Face does it, as their solution works very well, and try to replicate it (or improve over it) to get this right once and for all, avoiding the super lazy solution, but I'm open to suggestions ;)

**Comment by flozi00** [comment]
@w4nderlust 
my first suggestion for a model hub 

example usage: 
base url with github pages: "https://flozi00.github.io/modelhub/" + folder (models / encoders / decoders / combiners) + username + modelname
https://flozi00.github.io/modelhub/models/flozi00/titanic_model.json

https://github.com/flozi00/modelhub

**Comment by w4nderlust** [comment]
Thank you, this is a very nice starting point :)

n alternative for the entries:
```
{
	"type": "model",  // model, encoer, combiner, decoder
	"path": "http://models.a-ware.io/titanic.zip",
	"ludwig_version": "0.3-alpha",
	"dataset_name": "titanic",
	"dataset_path": None,  //optional, for public datasets
	"tags": {...},  //useful for search in the future
	"description": "This model was trained from the ludwig tutorials",
}
```

**Comment by flozi00** [comment]
I am thinking about replacing the description with an markdown file as huggingface does for the description, comments, code snippets and model definition file in yaml format.

The type is already defined with the folders, is it necessary to do it twice ?
Today I would start with generating an merged list of all files, is it okay when the type get filled there automatically ?
When the list is ready I would start with an simple UI to display the models and making an search mask

**Comment by w4nderlust** [comment]
> I am thinking about replacing the description with an markdown file as huggingface does for the description, comments, code snippets and model definition file in yaml format.

Sounds good, curious to see how it looks like after the change ;)
 
> The type is already defined with the folders, is it necessary to do it twice ?

I wold say yes, i can see how it can seem redundant, but if in the future we want to place a little elasticsearch instance in front of it to do search, having the field may be useful.

> Today I would start with generating an merged list of all files, is it okay when the type get filled there automatically ?
> When the list is ready I would start with an simple UI to display the models and making an search mask

That sounds great, thank you!

**Comment by flozi00** [comment]
I tried this out and it seems like you can't create an PR using the GitHub Apis this way.
I found examples where users cloned repos or committed to existing but I found no way to create an PR programmatically without automating the browser using selenium or something similar.

What's the biggest size of an zipped model ?
GitHub allows uploading files smaller than 100mb, with Ludwig 0.2 I didn't find an model bigger than this.
I will try the hf_transformers branche later and check the size.

In this case we could use an GitHub repo + GitHub pages as download server, hopefully it is not forbidden for such an use case ^^

**Comment by w4nderlust** [comment]
> I tried this out and it seems like you can't create an PR using the GitHub Apis this way.
> I found examples where users cloned repos or committed to existing but I found no way to create an PR programmatically without automating the browser using selenium or something similar.

Got it. It's a shame, but it's fine to do without ;)

> What's the biggest size of an zipped model ?
> GitHub allows uploading files smaller than 100mb, with Ludwig 0.2 I didn't find an model bigger than this.
> I will try the hf_transformers branche later and check the size.
> 
> In this case we could use an GitHub repo + GitHub pages as download server, hopefully it is not forbidden for such an use case ^^

I don't think it's forbidden, but 100mb is a pretty small size. It may be fine for now, but probably in the future we want users to either post the models and we manage saving them somewhere and keeping hte links, or they can provide a link to download the zip and we have some code that downloads it. I would prefer the first option, but it looks like it requires infrastructure.

> Edit:
> Otherwise I would take the username from GitHub oauth, create an seperated folder named by the username and store the uploaded model there.
> Then the model is online and only the model card is missing.

That may be fine, but the 100mb limit would still be there.

**Comment by flozi00** [comment]
> That may be fine, but the 100mb limit would still be there.

There is no limit in this case.
We take the username by GitHub oauth, create an folder named by this, outside of the repo.
The models get stored on the hosting server then.
It's pretty similar to HF modelhub, anyone can upload models but the model cards needs to be reviewed from the team.

Which way to use ?
Hosted by GitHub pages or custom infrastructure ?

**Comment by flozi00** [comment]
The following might be a suggestion:
https://github.com/flozi00/modelhub/tree/master/models/flozi00

In this version the paths are relative and you can host it on any server, you just have to enter the base url in the client.
Only the UI needs PHP support.

The models can be checked before they are merged, the functionality can be done somehow via the github actions.

Via git lfs (https://docs.github.com/en/github/managing-large-files/configuring-git-large-file-storage) it should be possible to manage files larger than 100 MB, I would have to deal with that.

**Comment by w4nderlust** [comment]
This looks convincing :) If lfs allow for bigger files, that sounds pretty nice to me.

**Comment by flozi00** [comment]
Okay, then I will check the automated test using Github actions, trying to make the css looking better and then we could start integrating it into ludwig.

**Comment by flozi00** [comment]
```
import dload

def download_model(model_type, model_name, base_url = "https://models.a-ware.io/", base_path= "/tmp/ludwig/"):
    dload.save_unzip(base_url + model_type + "/" + model_name + ".zip" , base_path + model_type + "/" + model_name )


```

This library handles all the necceassary steps, the above function can successfully download and unzip the model from model hub.

**Comment by w4nderlust** [comment]
Looks pretty cool! Only thing I suggest: when creating paths, use `os.path.join()` as it will respect the current os path separator (the current code won't work on windows, but with my suggestion it will for instance).

**Comment by flozi00** [comment]
So, only the ludwig implementation is missing now.
The models can be stored everywhere (I will upload them to our S3 storage), the URL needs to be given in models json.
Every commit to the repo gets synced to the webserver instantly.
I will try to make the CSS looks better, could you insert the download function to ludwigs code ? I don't know where to do so exactly.
Actually I am training an address validation model for my work, after this I will train on kaggle datasets again.
