### ISSUE TITLE
Offer Ludwig as Anaconda application or package

### ISSUE THREAD

**Issue by panoptikon** [ludwig-ai/ludwig#724]
As a user of Anaconda – and not very proficient with lower-level code management – I'd like to install Ludwig from the Anaconda Navigator. 
The Orange framework can easily be installed from the Navigator home screen and it's ready to use. 
Having Ludwig properly installed in Anaconda by a smart automation will likely increase its adoption.

More tech info on building Anaconda Navigator applications here:
https://docs.anaconda.com/anaconda/navigator/tutorials/nav-app/

Thank you!

**Comment by w4nderlust** [comment]
This is a good idea. I'm not an Anaconda user myself, but will look into it. If someone is more familiar with Anaconda than I am and wants to contribute this, it would be great.
