### ISSUE TITLE
[Feature Request] Force balancing of output classes \ binary in preprocessing

### ISSUE THREAD

**Issue by carlogrisetti** [ludwig-ai/ludwig#818]
It often happens that data is unbalanced, and this leads to a model that reaches 80% accuracy very fast (ie: predicting that all items are true, just because 80% of the items are true), and the learning path towards an 80,1% is very very hard if not impossible to achieve in a timely manner.

I know this is not an ideal solution, since you would have to get more data regarding the minority class\binary to balance it out, but since ludwig has a preprocessing feature, this could be an useful tool to quickly get an estimate on how good of a model it could be if it had all the correct data, or on the other hand to easen the manual pruning of the overrepresented class\binary in the source data.

I have a scenario where input data for training is automatically fetched, and such a feature would play nice with the "force_split" parameter... something like "force_balance" specifying a class\binary output feature name, with a "balance_strategy" that could either be "pruning" which randomly chops off data pertaining to the class\binary in excess, or "cloning", which randomly repeats data pertaining to the class\binary least present

Of course, in the meantime, I'm going to implement this in the dataset fetching part of my code, but it might be a nice addition (and a quick one too, I suspect)

**Comment by w4nderlust** [comment]
this is a good feature, it would be worth adding it. We can find some time to prioritize it after the release of v0.3. If you'd like to contribute it, more than open to guide you.

**Comment by ifokeev** [comment]
Yeah, good idea

**Comment by w4nderlust** [comment]
@carlogrisetti @ifokeev the feature was recently added, Will also add a page in the docs to describe how to use it. it basically allows to over and under sample training datasets ;) @connor-mccorm worked on it. Closing the feature requests.
