### ISSUE TITLE
SQL data sources? or TFIO support?

### ISSUE THREAD

**Issue by elgalu** [ludwig-ai/ludwig#847]
Beyond CSV and WIP Parquet support, is it planned for example to leverage TF/IO https://github.com/tensorflow/io ?

**Comment by w4nderlust** [comment]
As a general rule, we want to support as many data sources as possible.
Obviously it's a matter of resources and prioritization ;)
Although preprocessing and adding data sources will be one of the main priorities of v0.3.
Mark this as a feature request, feel free to add the data formats and sources you wish Ludwig would support.
