### ISSUE TITLE
Port Ludwig to Google Coral Dev board

### ISSUE THREAD

**Issue by swayll** [ludwig-ai/ludwig#863]
Tried to install Ludwig to Coral Dev board, but have many errors. Please will port Ludwig to this platform.
Thank you for Ludwig!

**Comment by w4nderlust** [comment]
@swayll I'm not familiar with it, I'm guessing it is this one: https://coral.ai/products/dev-board/
On the website it suggests that " TensorFlow Lite models can be compiled to run on the Edge TPU".
Models from Ludwig are TF models, not TF Lite models.
I'm guessing you can try converting them to TF Lite models, but I have no experience with that.
I'll mark this as a feature request. Would gladly accept contributions from someone with TF Lite / IoT experience.
"
