### ISSUE TITLE
Deploy directly to AWS sage maker / Azure ML Studio / GCP

### ISSUE THREAD

**Issue by kaykumar** [ludwig-ai/ludwig#920]
**Is your feature request related to a problem? Please describe.**
A lot of custom work to deploy the model. 

**Describe the use case**
 I build this model using ludwig, now It will be great if I can provide my AWS /AZURE credentials and it gets deployed and an endpoint is returned, that will help with quick model deployments.

**Describe the solution you'd like**
Ludwig --experiment -- > Ludwig --deploy aws/azure/gcp

**Describe alternatives you've considered**
Build a docker image and deploy to Kubernetes

**Comment by w4nderlust** [comment]
Thanks, this is a good idea.
Added to the list of feature requests.
Would gladly accept contributions for this.

**Comment by shparki** [comment]
I can definitely help with the Sagemaker deployment automation piece.

**Comment by w4nderlust** [comment]
> I can definitely help with the Sagemaker deployment automation piece.

That would be great!

**Comment by kaykumar** [comment]
Is ludwig already saving the tf model in SavedModel format?

**Comment by w4nderlust** [comment]
> Is ludwig already saving the tf model in SavedModel format?

Yes, Ludwig can export the model as SavedModel, but you need to preprocess the incoming data in the right way and postprocess the model outputs correctly if you want the results to make sense, So uploading only the SavedModel wouldn't do it.

One option is to use the export Neuropod functionality, with also perfroms preprocessing and postprocessing.

An additional option is to use the `ludwig serve` command that spawns a Rest API that performs preprocessing, model inference and postprocessing.

**Comment by brightsparc** [comment]
Hi @kaykumar I have created an example on how to build, train and deploy a ludwig model with sagemaker including building a container from source so you have the latest ludwig code.
see: https://github.com/aws-samples/amazon-sagemaker-ludwig-transformer

**Comment by w4nderlust** [comment]
@brightsparc this is great, thank you so much! Do you mind if we reference this on the website in the exampels section as a deployment example?

**Comment by brightsparc** [comment]
@w4nderlust sure would be great to get these referenced.
