### ISSUE TITLE
Unable to install 

### ISSUE THREAD

**Issue by Bandit253** [ludwig-ai/ludwig#966]
I have tried a couple of times, on 2 versions of python, to install following instructions but it fails at installing neuropod

(venv) G:\_ludwig\venv\Scripts>pip install ludwig[full]
Collecting ludwig[full]
  Using cached ludwig-0.3.tar.gz (212 kB)
Collecting Cython>=0.25
  Using cached Cython-0.29.21-cp37-cp37m-win_amd64.whl (1.6 MB)
Collecting h5py>=2.6
  Using cached h5py-2.10.0-cp37-cp37m-win_amd64.whl (2.5 MB)
Collecting numpy>=1.15
  Using cached numpy-1.19.2-cp37-cp37m-win_amd64.whl (12.9 MB)
Collecting pandas>=0.19
  Using cached pandas-1.1.3-cp37-cp37m-win_amd64.whl (8.7 MB)
Collecting scipy>=0.18
  Using cached scipy-1.5.3-cp37-cp37m-win_amd64.whl (31.2 MB)
Collecting tabulate>=0.7
  Using cached tabulate-0.8.7-py3-none-any.whl (24 kB)
Collecting scikit-learn
  Using cached scikit_learn-0.23.2-cp37-cp37m-win_amd64.whl (6.8 MB)
Collecting tqdm
  Using cached tqdm-4.50.2-py2.py3-none-any.whl (70 kB)
Collecting tensorflow>=2.2
  Using cached tensorflow-2.3.1-cp37-cp37m-win_amd64.whl (342.5 MB)
Collecting tfa-nightly==0.12.0.dev20200820045606
  Using cached tfa_nightly-0.12.0.dev20200820045606-cp37-cp37m-win_amd64.whl (920 kB)
Collecting PyYAML>=3.12
  Using cached PyYAML-5.3.1-cp37-cp37m-win_amd64.whl (216 kB)
Collecting absl-py
  Using cached absl_py-0.10.0-py3-none-any.whl (127 kB)
Collecting xlwt
  Using cached xlwt-1.3.0-py2.py3-none-any.whl (99 kB)
Collecting xlrd
  Using cached xlrd-1.2.0-py2.py3-none-any.whl (103 kB)
Collecting openpyxl
  Using cached openpyxl-3.0.5-py2.py3-none-any.whl (242 kB)
Collecting pyarrow
  Using cached pyarrow-2.0.0-cp37-cp37m-win_amd64.whl (10.7 MB)
Collecting lxml
  Using cached lxml-4.6.1-cp37-cp37m-win_amd64.whl (3.5 MB)
Collecting soundfile
  Using cached SoundFile-0.10.3.post1-py2.py3.cp26.cp27.cp32.cp33.cp34.cp35.cp36.pp27.pp32.pp33-none-win_amd64.whl (689 kB)
Collecting scikit-image==0.14.2
  Using cached scikit_image-0.14.2-cp37-none-win_amd64.whl (24.6 MB)
Collecting uvicorn
  Using cached uvicorn-0.12.2-py3-none-any.whl (45 kB)
Collecting fastapi
  Using cached fastapi-0.61.1-py3-none-any.whl (48 kB)
Collecting pydantic
  Using cached pydantic-1.6.1-cp37-cp37m-win_amd64.whl (1.6 MB)
Collecting python-multipart
  Using cached python-multipart-0.0.5.tar.gz (32 kB)
**ERROR: Could not find a version that satisfies the requirement neuropod (from ludwig[full]) (from versions: none)
ERROR: No matching distribution found for neuropod (from ludwig[full])**

**Expected behavior**
Successfully installed

**Environment (please complete the following information):**
 - OS: Win10
-  Python 3.8.3, 3.7.4 
- Ludwig assume latest

**Comment by w4nderlust** [comment]
@Bandit253 thanks for noticing us about it, we'll look into it. My best guess is that the issue lies with neuropod and Win10, but I have to verify it.

As a temporary workaround, if you don't need neuropod specifically, i would suggest you install just `ludwig` and optionally all the subpackages that are useful for you usecase. `neuropod` is inclused in the `serve` subpackage at the moment, so if you don't install it you shouldn't be finding issues.
Let us know if this helped.

**Comment by Bandit253** [comment]
Thanks I will do that for now.
