### ISSUE TITLE
Replicating Keras architecture for text classification in Ludwig

### ISSUE THREAD

**Issue by AschHarwood** [ludwig-ai/ludwig#969]
Hi,

Thanks so much for the the impressive tool you've put together. I have an feed forward sequential model that has been performing quite well for my problem at hand, which is predicting hourly google search trend volume for particular keywords based on aggregated news articles (basically, I take all the tokens from articles that were published at a particular time and concatenate them into one long set of tokens).

I'm particularly interested in Ludwig because I have additional metadata that I would like to bring into my model, and it appears that the "combiner" feature could really simplify the problem. 

```
`
#download google news 128 dim pertained model
embedding = "https://tfhub.dev/google/nnlm-en-dim128/2"
#create hub layer
hub_layer = hub.KerasLayer(embedding, input_shape=[], dtype=tf.string, trainable=True)

#set up sequential model
model = tf.keras.Sequential()
model.add(hub_layer)
model.add(tf.keras.layers.Dense(16, activation='relu'))
model.add(tf.keras.layers.Dropout(0.2))
model.add(tf.keras.layers.Dense(8, activation='relu'))
model.add(tf.keras.layers.Dropout(0.2))
model.add(tf.keras.layers.Dense(4, activation='relu', kernel_regularizer=regularizers.l2(0.01)))
model.add(tf.keras.layers.Dropout(0.2))
model.add(tf.keras.layers.Dense(1))

#compile model
model.compile(optimizer='adam',
             loss=tf.keras.losses.BinaryCrossentropy(from_logits=True),
             metrics=['accuracy'])

#fit model
history = model.fit(X_train, y_train, epochs=5, verbose=1, validation_data=(X_test, y_test))
`
```

My goal would be to take this model and add additional input features. In Ludwig, it would look something like:

`model_definition = {
    'input_features': [
        { 'Keras squential model with google news word embeddings'
         },
    {'name':'avg_tone', 'type': 'numerical', 'encoder': 'dense'},
    {'name':'pos_words', 'type': 'numerical', 'encoder': 'dense'},
    {'name':'neg_words', 'type': 'numerical', 'encoder': 'dense'},
    {'name':'polarity', 'type': 'numerical', 'encoder': 'dense'},
    {'name':'act_ref_density', 'type': 'numerical', 'encoder': 'dense'},
    {'name':'self_group_density', 'type': 'numerical', 'encoder': 'dense'},
    {'name':'word_count', 'type': 'numerical', 'encoder': 'dense'}
    ],
    'output_features': [
        {'name': 'shifted_12h', 'type': 'binary'},
    ]
}
`

Any guidance would be greatly appreciated!

**Comment by w4nderlust** [comment]
@AschHarwood the specific model you are importing from the tensorflow hub is currently not supported in Ludwig. You can likely add it as a text encoder.
Alternatively you could use any of the sequence and text encoders that Ludwig already provides, both training them from scratch or using pretrained one, depending on your usecase and the amount of data you have available.
Let me know if you have further questions.

**Comment by AschHarwood** [comment]
@w4nderlust I appreciate you taking a look at this for me. I was able to apply the GLOVE model. However, I'm still struggling about how to replicate the basic architecture with three hidden layers with descending node size. Are there any examples you could point me toward to replicate this?

Thanks!
Asch

**Comment by w4nderlust** [comment]
You could replicate this part:
```
model.add(tf.keras.layers.Dense(16, activation='relu'))
model.add(tf.keras.layers.Dropout(0.2))
model.add(tf.keras.layers.Dense(8, activation='relu'))
model.add(tf.keras.layers.Dropout(0.2))
model.add(tf.keras.layers.Dense(4, activation='relu', kernel_regularizer=regularizers.l2(0.01)))
model.add(tf.keras.layers.Dropout(0.2))
```
by specifying the layers of the combiner as describide in `fc_layers` here: https://ludwig-ai.github.io/ludwig-docs/user_guide/#concat-combiner

It will look like:
```
combiner:
  fc_layers:
    - 
      fc_size: 16
      activation: relu
      dropout: 0.2

    - 
      fc_size: 8
      activation: relu
      dropout: 0.2

    - 
      fc_size: 4
      activation: relu
      dropout: 0.2
      weights_regularizer: l2
```

And then in the training section:
```
training:
  regularization_lambda: 0.01
```

**Comment by AschHarwood** [comment]
Hi, 
Somehow I missed this response. I really appreciate your help! Going to close this issue now. Thanks!
