### ISSUE TITLE
[Feature request] saved model example codes

### ISSUE THREAD

**Issue by flozi00** [ludwig-ai/ludwig#971]
I think a cool feature for model serving would be generating example codes for the export of saved model, which can be used in TF-JS and so on.
If you want to serve your model as webapp in JS and ludwig generates the function you only need to call, you don't even need to learn JS so much.
Only need to copy existing apps and insert the model + generated function in place where you need.
Same for other Plattforms and languages

**Comment by w4nderlust** [comment]
We'll consider this, thanks!
