### ISSUE TITLE
[Feature request] huggingface datasets

### ISSUE THREAD

**Issue by flozi00** [ludwig-ai/ludwig#972]
The huggingface datasets library contains very much datasets for NLP tasks, what about an native implementation of these ?
Lazy loading for example is already done by the library.

**Comment by w4nderlust** [comment]
Unfortunately it's not a sufficiently generic solution for Ludwig as it doesn't account for datatypes other than text.
That said, the library is very well done and we'll likely take inspiration from some design decisions.
