### ISSUE TITLE
Synthetic Time Series Data

### ISSUE THREAD

**Issue by DLWCMD** [ludwig-ai/ludwig#974]
**Is your feature request related to a problem? Please describe.**
Uber/Ludwig wishes to enhance its support for time series modeling and analysis. While there are many existing time series available for downloading, such as the LA Weather Archive used in a Ludwig TS example, a 'self-contained' Ludwig application would offer many benefits as a test bed for TS analysis with Ludwig, including comparison of various tools and methods. 

**Describe the use case**
A clear and concise description of what the use case for this feature is.
Incorporating user-configurable time series into Ludwig integrated with its various TS tools and methods, such as sequencing.

**Describe the solution you'd like**
I have developed Python code, based on the [Mackey-Glass equation](https://en.wikipedia.org/wiki/Mackey-Glass_equations]), which supports creating simulated (AKA 'synthetic') time series of any length and configuration (e.g., univariate, multivariate with user-defined prediction horizons). MG time series are designed to be chaotic and thus present a challenging test-bed for TS analysis and prediction and so should support creation of robust solutions. I would be happy to contribute my code and/or support Uber staff to incorporate it into Ludwig.

**Describe alternatives you've considered**
Integrate Ludwig with the University of California-Irving Machine Learning [Repository](https://archive.ics.uci.edu/ml/datasets.php?format=&task=&att=&area=&numAtt=&numIns=&type=ts&sort=nameUp&view=table), which includes over 100 time series collected from around the world.

**Additional context**
The proposed application could also be used to support development and testing of new Ludwig TS tools and methods.

**Comment by w4nderlust** [comment]
Thanks @DLWCMD for this feature request. At the moment when we generate synthetic datasets for timeseries we just use random values (as the intent is just to test if things work end to end rather than testing performance) amd what you are suggesting sounds like a nice improvement!
Would you have any interest in helping out implementing this? We can provide guidance in case ;)

**Comment by DLWCMD** [comment]
Good to hear from you, and yes, I would like to contribute. I have been working on understanding Mackey-Glass (MG) equation and generating sequences and time series from them. One of the benefits of using these equations is that the degree of “chaos,” that is the challenge of modeling and predicting the associated TS, can be varied by changing the equation parameters.

 

I have some examples that suggest how MG might be used, which I would be happy to share with you.

 

Thanks again for your response. I will say I am much impressed with Ludwig, which I was touting to my son, who works with ML/AI for Johns Hopkins Applied Physics Lab. I like the range of functionality, from no coding for basic situations, to extending through use of Python features. 

 

Talk soon.

 

David L. Wilt

3272 Bayou Road

Longboat Key FL 34228

dwilt1947@gmail.com

540-420-0844
