### ISSUE TITLE
Can I translate the README.md file into Korean?

### ISSUE THREAD

**Issue by rang21c** [ludwig-ai/ludwig#984]
Hello, I am a university student from Korea and I am interested in deep learning.

So I'd like to translate README.md file of this project.

If you are interested in this, please comment below. Thank you!

**Comment by w4nderlust** [comment]
@rang21c thank you for your interest! That sounds great. The only thing is that I wouldn't know how to expose it. What were you thinking? Another README_KR.md file? or something different?

**Comment by rang21c** [comment]
@w4nderlust 
Thank you for your comment!
I thought a lot about that part, and looked a lot of the case of other projects.

I think there are two main ways.
1. Creating README_KR.md file as you said
2. Attaching a Korean-translated GitHub link to the top of an existing README.md file
However, the second method seems to have some difficulties when other Koreans find errors and raise issues.

I will follow your decision and if you allow me to translate, I will complete the translation within a month.
Thank you!

**Comment by w4nderlust** [comment]
@rang21c thank you! So I would say let's go the first route, and if in the meantime we decide differently we can always change. To me the best idea would be to have such a separate file and link to it from the main one, but let's see how it shapes up before making a final decision ok? Looking forward your contribution!

**Comment by rang21c** [comment]
@w4nderlust 
Thank you for your permission!
I will do my best in this translation work and try to make more Koreans to know the convenience of Ludwig.
I will reply when the translation is complete.

**Comment by rang21c** [comment]
@w4nderlust 
Translation work almost done. 
Where can i link translated README file with original README file? (especially which line of original file)
Thank you

**Comment by w4nderlust** [comment]
I would say you can add a "Translated in Korean" link at the top of the main readme ;)

**Comment by rang21c** [comment]
Thank you 😄 
Then, I will look over the work for the last time and make pull request in a few days.
